export interface Business {
  slug: string;
  name: string;
  category: string;
  phone: string;
  address: string;
}

export const businesses: Business[] = [
  { slug: '20-laburnum-terrace', name: '20 laburnum terrace', category: 'mechanic', phone: '', address: '4 College Terrace, Londonderry BT48 7JG, UK' },
  { slug: 'a-l-c-joinery', name: 'A L C Joinery', category: 'joiner', phone: '028 7134 1386', address: '59 Sevenoaks, Londonderry BT47 6BD, UK' },
  { slug: 'a-e-car-wash-valeting', name: 'A&E Car Wash Valeting', category: 'car', phone: '07845 410997', address: '65 Rosemount Ave, Londonderry BT48 0HH, UK' },
  { slug: 'a1-mobile-mechanic-derry', name: 'A1 Mobile mechanic derry', category: 'mechanic', phone: '07487 664507', address: '36 Westland St, Londonderry BT48 9ET, UK' },
  { slug: 'ac-motors-direct-ltd', name: 'Ac Motors Direct Ltd', category: 'car', phone: '07742 792083', address: 'Unit 43, North West Business Complex, Beraghmore Road, Londonderry BT48 8SE, UK' },
  { slug: 'ad-joinery', name: 'Ad Joinery', category: 'joiner', phone: '', address: '14 Ardanlee, Ballynagard, Londonderry BT48 8RR, UK' },
  { slug: 'adorable-dogs', name: 'Adorable Dogs', category: 'dog', phone: '07753 117195', address: '20 Maydown Rd, Strathfoyle, Londonderry BT47 6UJ, UK' },
  { slug: 'aj-joinery', name: 'Aj joinery', category: 'joiner', phone: '', address: '82 Duncreggan Rd, Londonderry BT48 0AA, UK' },
  { slug: 'all-emergency-plumbing', name: 'all emergency plumbing', category: 'plumber', phone: '07955 050100', address: '28 Prehen Park, Londonderry BT47 2NY, UK' },
  { slug: 'all-furr-dogs', name: 'ALL FURR DOGS', category: 'dog', phone: '07779 028028', address: '1 Sheraton Park, Londonderry BT48 0AQ, UK' },
  { slug: 'aok-joinery', name: 'AOK Joinery', category: 'joiner', phone: '07825 517616', address: '51 Foxhill, The Bolies, Londonderry BT47 2TN, UK' },
  { slug: 'bareknuckle-barbershop', name: 'Bareknuckle Barbershop', category: 'barber', phone: '07803 842600', address: '173 Spencer Rd, Londonderry BT47 6AH, UK' },
  { slug: 'bark-n-baths', name: 'Bark N Baths', category: 'dog', phone: '07719 579277', address: 'Unit 6, Swilly House, Springtown Rd, Londonderry BT48 0GH, UK' },
  { slug: 'bc-auto-repair', name: 'BC Auto Repair', category: 'mechanic', phone: '07783 849000', address: 'Unit 4 Springtown Dr, Londonderry BT48 0LY, UK' },
  { slug: 'bearney-nurseries', name: 'Bearney Nurseries', category: 'nursery', phone: '07912 853039', address: '30a Liskey Rd, Strabane BT82 8NR, UK' },
  { slug: 'beauty-unlimited', name: 'Beauty Unlimited', category: 'beauty salon', phone: '028 7137 2117', address: '22a Great James St, Londonderry BT48 7DA, UK' },
  { slug: 'bell-p-j', name: 'Bell P J', category: 'painter', phone: '028 7135 1639', address: '2 Clonliffe Park, Londonderry BT48 8NT, UK' },
  { slug: 'best-buddies-groomers', name: 'Best Buddies Groomers', category: 'dog', phone: '07821 072599', address: '8 Glasgow Terrace, Londonderry BT48 0DP, UK' },
  { slug: 'black-paws-cattery', name: 'Black Paws Cattery', category: 'dog', phone: '07710 622053', address: '19 Rossdowney Gardens, Londonderry BT47 5PW, UK' },
  { slug: 'blissful-brush-dog-grooming', name: 'Blissful Brush Dog Grooming', category: 'dog', phone: '07749 317864', address: '22 Rossdowney Dr, Londonderry BT47 5PR, UK' },
  { slug: 'bmr-decorators', name: 'BMR DECORATORS', category: 'painter', phone: '07873 445963', address: '157 Gortin Manor, Newbuildings, Londonderry BT47 2TT, UK' },
  { slug: 'breidges-barbers', name: 'Breidges Barbers', category: 'barber', phone: '028 7137 2030', address: '47 Strand Rd, Londonderry BT48 7BN, UK' },
  { slug: 'brett-electrical', name: 'Brett Electrical', category: 'electrician', phone: '07706 820839', address: '65 Ivy Mead, Altnagelvin, Londonderry BT47 3WW, UK' },
  { slug: 'brooke-hairdressing', name: 'Brooke Hairdressing', category: 'hairdresser', phone: '028 7126 0003', address: '8 Castle St, Londonderry BT48 6HQ, UK' },
  { slug: 'bt48-barbering-for-men', name: 'Bt48 barbering for men', category: 'barber', phone: '07517 698045', address: '16 Carlisle Rd, Londonderry BT48 6JN, UK' },
  { slug: 'busters-barber-shop', name: 'Busters Barber Shop', category: 'barber', phone: '07594 749796', address: '21A Waterloo St, Londonderry BT48 6HA, UK' },
  { slug: 'busy-bee-playschool', name: 'Busy Bee Playschool', category: 'nursery', phone: '(074) 914 1176', address: 'Tara Rose, Townparks, Lifford, Co. Donegal, Ireland' },
  { slug: 'calm-yoga', name: 'CALM Yoga', category: 'yoga', phone: '07999 025918', address: 'Ebrington St, Londonderry BT47 6EQ, UK' },
  { slug: 'canine-barber-company', name: 'CANINE BARBER COMPANY', category: 'dog groomer', phone: '', address: '66 Strand Rd, Londonderry BT48 7PX, UK' },
  { slug: 'catwalk-dogs-grooming-salon-doggie-daycare', name: 'Catwalk Dogs Grooming Salon & Doggie Daycare', category: 'dog groomer', phone: '', address: 'Racecourse Rd, Londonderry BT48 7UD, UK' },
  { slug: 'ceo-performance-rehab', name: 'CEO Performance & Rehab', category: 'gym', phone: '07771 614654', address: '10c Captain Street Lower, Coleraine BT51 3DT, UK' },
  { slug: 'chicken-plaza', name: 'Chicken Plaza', category: 'takeaway', phone: '028 7141 3326', address: '27 Foyle St, Londonderry BT48 6AL, UK' },
  { slug: 'chop-shop-barbers', name: 'Chop Shop Barbers', category: 'barber', phone: '07715659209', address: '7 St Marys St, Newry BT34 2AA, UK' },
  { slug: 'choppers-barbers', name: 'Choppers Barbers', category: 'barber', phone: '028 7130 9400', address: '74 Bishop St, Londonderry BT48 6QE, UK' },
  { slug: 'city-auto-wholesale', name: 'City auto wholesale', category: 'car', phone: '07393 339272', address: 'Elagh Business Park East, 17 Buncrana Rd, Londonderry BT48 8LU, UK' },
  { slug: 'city-barbers', name: 'City barbers', category: 'barber', phone: '07500 357463', address: '9 Great James St, Londonderry BT48 7BZ, UK' },
  { slug: 'city-electrics-ireland-ltd', name: 'City Electrics Ireland Ltd', category: 'electrician', phone: '028 7135 3147', address: '19 Sandbank Cottages, Londonderry BT48 8LL, UK' },
  { slug: 'city-paints-wallpapers', name: 'City Paints & Wallpapers', category: 'painter', phone: '028 7128 0088', address: '5/6 Springtown Business Park, Londonderry BT48 0GY, UK' },
  { slug: 'city-roofing-ltd', name: 'City Roofing Ltd', category: 'roofer', phone: '028 7126 9648', address: '3 Pennyburn Industrial Estate, Londonderry BT48 0LU, UK' },
  { slug: 'city-turkish-barbers-derry', name: 'City Turkish Barbers Derry', category: 'barber', phone: '', address: '25 The Diamond, Londonderry BT48 6HP, UK' },
  { slug: 'cleanlyy', name: 'Cleanlyy', category: 'cleaner', phone: '028 7178 2153', address: 'Rhodemore Ltd, The Innovation Centre, Bay Rd, Londonderry BT48 7TG, UK' },
  { slug: 'clearflow', name: 'Clearflow', category: 'plumber', phone: '07845 877493', address: '80 Strabane Old Rd, Londonderry BT47 2EG, UK' },
  { slug: 'code', name: 'CODE', category: 'beauty salon', phone: '', address: '10/11, Craft Village, Londonderry BT48 6AR, UK' },
  { slug: 'collon-cars', name: 'Collon Cars', category: 'mechanic', phone: '028 7126 2952', address: 'Unit 12,13,14, Northland Road Industrial Estate, Northland Rd, Londonderry BT48 0LD, UK' },
  { slug: 'concept-carpentry-joinery', name: 'Concept Carpentry &Joinery', category: 'joiner', phone: '07903 152202', address: '563 Carnhill, Londonderry BT48 8BZ, UK' },
  { slug: 'crumley-patrick', name: 'Crumley Patrick', category: 'electrician', phone: '028 7131 2939', address: '18b Riverview Terrace, Londonderry BT47 2BL, UK' },
  { slug: 'crumlish-house-of-luxury-hair-extensions-makeup-artistry', name: 'Crumlish House Of Luxury Hair Extensions & Makeup Artistry', category: 'hairdresser', phone: '', address: 'Pump St, Londonderry BT48 6JG, UK' },
  { slug: 'curran-hepburn', name: 'Curran & Hepburn', category: 'electrician', phone: '07712 110048', address: '87 Spencer Rd, Londonderry BT47 6AE, UK' },
  { slug: 'd-m-groomers', name: 'D&M GROOMERS', category: 'dog', phone: '07927 443098', address: '53 Rosemount Ave, Londonderry BT48 0HL, UK' },
  { slug: 'dapper-dogs-mobile-grooming', name: 'Dapper Dogs Mobile Grooming', category: 'dog', phone: '07368 243039', address: 'Prehen Park, Derry BT47 2NY, UK' },
  { slug: 'darek-furniture', name: 'Darek furniture', category: 'joiner', phone: '07873 529748', address: '34 Ervey Ct, Londonderry BT47 3WN, UK' },
  { slug: 'dc-auto-repair-derry', name: 'DC Auto Repair Derry', category: 'mechanic', phone: '07544 061038', address: '19, Rathmore Business Park, Londonderry BT48 0LZ, UK' },
  { slug: 'derry-auto-electrics', name: 'Derry Auto Electrics', category: 'electrician', phone: '028 7126 1100', address: '102 Duncreggan Rd, Londonderry BT48 0AA, UK' },
  { slug: 'derry-electrics', name: 'Derry Electrics', category: 'electrician', phone: '07923 806636', address: '50 Elaghmore Prk, Londonderry BT48 8DX, UK' },
  { slug: 'derry-garden-services', name: 'Derry Garden Services', category: 'landscaper', phone: '07523 612005', address: 'Londonderry BT47 6BB, UK' },
  { slug: 'derry-tiler', name: 'Derry Tiler', category: 'tiler', phone: '028 7137 3386', address: '24 Four Seasons, Foyle Road, Londonderry, Derry BT48 6AX, UK' },
  { slug: 'dgs-roofing-services', name: 'Dgs roofing services', category: 'roofer', phone: '07928 033186', address: '67 Coney Rd, Londonderry BT48 8JN, UK' },
  { slug: 'diamond-brow-bar', name: 'Diamond Brow Bar', category: 'beauty salon', phone: '07751 099410', address: '4 Shipquay St, Londonderry BT48 6DN, UK' },
  { slug: 'district-47-barbering-company', name: 'District 47 Barbering Company', category: 'barber', phone: '07845 009876', address: '47 Carlisle Rd, Co, Londonderry BT48 6JJ, UK' },
  { slug: 'dl-electrical-services', name: 'DL Electrical Services', category: 'electrician', phone: '07368 409085', address: 'Beechwood Ave, Londonderry BT48 9LR, UK' },
  { slug: 'dm-gas-plumbing-heating', name: 'DM Gas - plumbing - heating', category: 'plumber', phone: '07514 734229', address: '367 Carnhill, Londonderry BT48 8BS, UK' },
  { slug: 'dmc-premier-tiling', name: 'DMC Premier Tiling', category: 'tiler', phone: '07738 003899', address: '55 Lincoln Ct, Waterside, Londonderry BT47 5NT, UK' },
  { slug: 'doherty-e-sons', name: 'Doherty E & Sons', category: 'builder', phone: '028 7135 1655', address: '6 Fir Rd, Londonderry BT48 8NB, UK' },
  { slug: 'donohoe-t', name: 'Donohoe T', category: 'builder', phone: '028 7126 7244', address: '19-21 Chamberlain St, Londonderry BT48 6LR, UK' },
  { slug: 'dragonfly-studio', name: 'Dragonfly Studio', category: 'yoga', phone: '07597 786126', address: 'Unit 9 ground floor, 18 Balliniska Rd, Londonderry BT48 0NA, UK' },
  { slug: 'dv-valeting-and-detailing', name: 'Dv valeting and detailing', category: 'car', phone: '07922 239323', address: 'Lenamore Rd, Londonderry BT48 8NA, UK' },
  { slug: 'ec-painters-decorators', name: 'Ec painters & decorators', category: 'painter', phone: '07873 673801', address: '30E McLean Rd, Campsie, Londonderry BT47 3XX, UK' },
  { slug: 'elite-cleaning-services', name: 'Elite Cleaning Services', category: 'cleaner', phone: '07756 059298', address: '45 Ashburn Ave, Londonderry BT47 5QE, UK' },
  { slug: 'elite-finish-valeting', name: 'Elite Finish Valeting', category: 'car', phone: '07399 208916', address: 'Aughlish Ct, Londonderry BT47 6JN, UK' },
  { slug: 'emc-autos-mobile-mechanic', name: 'Emc Autos Mobile Mechanic', category: 'mechanic', phone: '07871 717678', address: '80A Culmore Rd, Londonderry BT48 8JB, UK' },
  { slug: 'essential-hair-company', name: 'Essential Hair Company', category: 'hairdresser', phone: '028 7126 2427', address: '8-10 Great James St, Londonderry BT48 7DB, UK' },
  { slug: 'f-s-motors', name: 'F & S Motors', category: 'mechanic', phone: '028 7135 0565', address: '26 Lenamore Rd, Londonderry BT48 8NA, UK' },
  { slug: 'falcon-landscape-building-services', name: 'Falcon landscape building services', category: 'landscaper', phone: '', address: 'Castle View Park, Londonderry BT48 8DL, UK' },
  { slug: 'foyleside-garage', name: 'Foyleside Garage', category: 'mechanic', phone: '028 7134 9203', address: '2a York St, Londonderry BT47 6DX, UK' },
  { slug: 'g-mak-auto-service', name: 'G Mak Auto Service', category: 'mechanic', phone: '028 7126 5151', address: 'Iona Business Pk, Southway, Londonderry BT48 9AH, UK' },
  { slug: 'gemini-hair-studio', name: 'Gemini Hair Studio', category: 'hairdresser', phone: '028 7127 1122', address: '53 Carlisle Rd, Londonderry BT48 6JL, UK' },
  { slug: 'gmc-plumbing-and-heating-ltd', name: 'GMC plumbing and heating ltd', category: 'plumber', phone: '07989 350136', address: '8 Lyndhurst Rd, Londonderry BT47 5HS, UK' },
  { slug: 'groomin-marvelous', name: 'Groomin Marvelous', category: 'dog', phone: '07855 808932', address: '4 North Meadows, Londonderry BT48 0QB, UK' },
  { slug: 'h-carlin-decorators', name: 'H Carlin Decorators', category: 'painter', phone: '028 7135 4489', address: '1 Griffith Park, Londonderry BT48 8PE, UK' },
  { slug: 'hair-of-the-dog-grooming-salon-boutique', name: 'Hair of the Dog grooming Salon & boutique', category: 'dog', phone: '07857 745888', address: 'Skeoge Industrial Estate, Beraghmore Rd, Londonderry BT48 8SE, UK' },
  { slug: 'handmade-events', name: 'Handmade Events', category: 'florist', phone: '07762 452582', address: 'Enterpise House, 11 Great James St, Londonderry BT48 7BZ, UK' },
  { slug: 'harrison-electrical', name: 'Harrison Electrical', category: 'electrician', phone: '028 7134 2539', address: '78 Duke St, Londonderry BT47 6DQ, UK' },
  { slug: 'hasson-motors', name: 'Hasson Motors', category: 'mechanic', phone: '07751 322671', address: '27a Sheriffs Rd, Londonderry BT48 0JS, UK' },
  { slug: 'headz-co', name: 'Headz & Co', category: 'hairdresser', phone: '028 7134 8665', address: '15 Glendermott Rd, Londonderry BT47 6BB, UK' },
  { slug: 'hmvaleting', name: 'HMValeting', category: 'car', phone: '07594 366129', address: '6 Kavanagh Ct, Londonderry BT48 0PN, UK' },
  { slug: 'horton-electrical-services-ltd', name: 'Horton Electrical Services Ltd', category: 'electrician', phone: '028 7130 8858', address: '1 Bay Road Business Park, Londonderry BT48 7SH, UK' },
  { slug: 'igroom-dog-grooming-by-lisa-curran-springtown', name: 'IGROOM DOG GROOMING BY LISA CURRAN SPRINGTOWN', category: 'dog', phone: '07749 457323', address: 'Balliniska Rd, Springtown Rd, Londonderry BT48 0NA, UK' },
  { slug: 'instant-property-maintenance-ltd', name: 'Instant Property Maintenance Ltd', category: 'handyman', phone: '028 7131 3325', address: '5 Columba Ter, Londonderry BT47 6JT, UK' },
  { slug: 'jake-co', name: 'Jake&Co', category: 'barber', phone: '028 7116 3694', address: '4 Messines Terrace, The Collon, Londonderry BT48 7QZ, UK' },
  { slug: 'jfc-construction-ltd', name: 'JFC Construction Ltd', category: 'builder', phone: '028 7181 1477', address: '8e Courtauld Way, Campsie, Londonderry BT47 3XX, UK' },
  { slug: 'joinery-workshop-services-ltd', name: 'Joinery Workshop Services Ltd', category: 'joiner', phone: '07951 068053', address: 'Site 30, Springtown Industrial Estate, Unit F Springrowth Rd, Londonderry BT48 0LY, UK' },
  { slug: 'kara-construction', name: 'KARA CONSTRUCTION', category: 'joiner', phone: '07597 752723', address: '85 Monnaboy Rd, Londonderry BT47 3HP, UK' },
  { slug: 'kc-locksmiths', name: 'KC Locksmiths', category: 'locksmith', phone: '07528 758157', address: '11 Maybrook Park, Londonderry BT48 7TP, UK' },
  { slug: 'kebab-house', name: 'Kebab House', category: 'takeaway', phone: '028 7137 4500', address: '42 Shipquay St, Londonderry BT48 6DW, UK' },
  { slug: 'kee-kennels-cattery', name: 'Kee Kennels & Cattery', category: 'dog', phone: '07894 068609', address: '11 Kee Rd, Campsie, Londonderry BT47 3PT, UK' },
  { slug: 'ks-electrical-services-ltd', name: 'KS Electrical Services Ltd', category: 'electrician', phone: '028 7128 6777', address: 'Business Park, Unit 7 Bay Rd, Londonderry BT48 7SE, UK' },
  { slug: 'la-bella-salon', name: 'La Bella Salon', category: 'beauty salon', phone: '028 7131 1522', address: '51 Spencer Rd, Londonderry BT47 6AA, UK' },
  { slug: 'lux-hair-beauty-studio', name: 'LUX Hair & Beauty Studio', category: 'hairdresser', phone: '07710 797261', address: '143 Bishop St, Londonderry BT48 6UJ, UK' },
  { slug: 'lynch-builders', name: 'Lynch Builders', category: 'builder', phone: '028 7181 1385', address: '38 Coolagh Rd, Londonderry BT47 3EQ, UK' },
  { slug: 'm-c-plastering', name: 'M C Plastering', category: 'plasterer', phone: '07709 614094', address: '4 Copperfield Dr, Londonderry BT47 5DG, UK' },
  { slug: 'man-cave-barber-shop', name: 'Man Cave Barber Shop', category: 'barber', phone: '028 7136 7770', address: 'Whitehouse Retail, 65 Buncrana Rd, Londonderry BT48 8LB, UK' },
  { slug: 'marie-gillespie-hair-beauty-studio', name: 'Marie Gillespie Hair & Beauty Studio', category: 'hairdresser', phone: '028 7134 4284', address: 'Unit 1 Woodburn Shopping Centre, 1, Waterside, Londonderry BT47 5PS, UK' },
  { slug: 'mavericks-hair-extensions-beauty', name: 'Mavericks Hair Extensions & Beauty', category: 'hairdresser', phone: '028 7116 3266', address: 'Room 1, Unit 18, Northside Village Centre, Glengalliagh Rd, Londonderry BT48 8NN, UK' },
  { slug: 'maybrooke-renovations-and-extensions', name: 'maybrooke renovations and extensions', category: 'joiner', phone: '07387 882775', address: '28 Petrie Way, Londonderry BT47 3XX, UK' },
  { slug: 'mccann-decor-ltd', name: 'McCann Decor Ltd', category: 'painter', phone: '028 7135 2243', address: '59 Templeard, Ballynagard, Londonderry BT48 8FE, UK' },
  { slug: 'mccauley-auto-electrics', name: 'McCauley Auto Electrics', category: 'electrician', phone: '028 7135 1972', address: '64 Coney Rd, Londonderry BT48 8JP, UK' },
  { slug: 'mcquaid-electrical', name: 'Mcquaid Electrical', category: 'electrician', phone: '07388 877368', address: '269 Carnhill, Londonderry BT48 8BL, UK' },
  { slug: 'mental-street-food', name: 'Mental street food', category: 'restaurant', phone: '07429 491533', address: 'Happy landing carpark, Eglinton, Derry BT47 3PQ, UK' },
  { slug: 'meraki-hairdressing', name: 'Meraki Hairdressing', category: 'hairdresser', phone: '028 7128 2386', address: '28 Carlisle Rd, Londonderry BT48 6JW, UK' },
  { slug: 'miabella-beauty-bar', name: 'Miabella beauty bar', category: 'beauty salon', phone: '07895 490560', address: '88 Racecourse Rd, Londonderry BT48 8DS, UK' },
  { slug: 'michael-deery-hair', name: 'Michael Deery Hair', category: 'hairdresser', phone: '07498 688989', address: '6 Castle St, Londonderry BT48 6HQ, UK' },
  { slug: 'michael-tomasz-hairdressing', name: 'Michael Tomasz Hairdressing', category: 'hairdresser', phone: '028 7126 8172', address: 'Unit 3, Rock Mills, 126 Strand Rd, Londonderry BT48 7AD, UK' },
  { slug: 'michaels-barbers', name: 'Michaels Barbers', category: 'barber', phone: '07311492190', address: '24 Upper Water St, Newry BT34 1DJ, UK' },
  { slug: 'michelle-s-beauty-clinic-and-training-academy', name: 'Michelle’s Beauty Clinic and Training Academy', category: 'beauty salon', phone: '07598 567984', address: '26 Spencer Rd, Londonderry BT47 6AA, UK' },
  { slug: 'never-settle-strength-conditioning', name: 'Never Settle Strength & Conditioning', category: 'gym', phone: '07513 861585', address: '24C Ballyrashane Rd, Coleraine BT52 2NL, UK' },
  { slug: 'nicor-construction', name: 'Nicor Construction', category: 'builder', phone: '028 7188 0888', address: 'Unit 11, Bay Road Industrial Park, Bay Rd, Londonderry BT48 7SE, UK' },
  { slug: 'nor-den-electrical', name: 'Nor-Den Electrical', category: 'electrician', phone: '028 7137 7210', address: '3 Springtown Rd, Londonderry BT48 0LY, UK' },
  { slug: 'north-wesrt-garden-experts', name: 'North Wesrt Garden Experts', category: 'landscaper', phone: '028 7135 8828', address: '47 Papworth Ave, Londonderry BT48 8PT, UK' },
  { slug: 'north-west-joinery-ltd', name: 'North West Joinery Ltd', category: 'joiner', phone: '028 7135 5555', address: '5 Steelstown Rd, Londonderry BT48 8EU, UK' },
  { slug: 'northland-motors', name: 'Northland Motors', category: 'mechanic', phone: '028 7136 4141', address: 'Unit 2, Northland Road Industrial Estate, Londonderry BT48 0LD, UK' },
  { slug: 'northwest-mot-service-centre', name: 'NorthWest MOT & Service Centre', category: 'mot', phone: '07944 764742', address: 'Unit 2c, Altnagelvin Industrial Estate, Trench Rd, Londonderry BT47 2ED, UK' },
  { slug: 'notorious-street-food', name: 'Notorious Street Food', category: 'takeaway', phone: '', address: 'Northside Village Centre, Glengalliagh Rd, Londonderry BT48 8NN, UK' },
  { slug: 'number-8-the-townhouse-accommodation', name: 'Number 8 The Townhouse Accommodation', category: 'hotel', phone: '07921 841820', address: '8 Artillery St, Londonderry BT48 6RG, UK' },
  { slug: 'oakleaf-physio', name: 'Oakleaf Physio', category: 'physiotherapy', phone: '07894 249352', address: '14 Pennyburn Industrial Estate, Londonderry BT48 0LU, UK' },
  { slug: 'od-s-garage', name: 'Od-S Garage', category: 'mechanic', phone: '', address: 'Unit 12, B, Springtown Rd, Londonderry BT48 0LY, UK' },
  { slug: 'oven-cleaning-muckers', name: 'Oven Cleaning Muckers', category: 'cleaner', phone: '028 7100 0028', address: '103 Westlake Enagh, 103 Westlake, Strathfoyle, Londonderry BT47 6WE, UK' },
  { slug: 'p-lynch-plumbing-heating', name: 'P lynch Plumbing & heating', category: 'plumber', phone: '07790 864092', address: '193 Hatmore Park, Londonderry BT48 0AF, UK' },
  { slug: 'p-t-s-plumbing-trade-supplies', name: 'P T S Plumbing Trade Supplies', category: 'plumber', phone: '028 7130 6000', address: '40 Springtown Rd, Londonderry BT48 0LY, UK' },
  { slug: 'pampered-paws-k9', name: 'Pampered Paws K9', category: 'dog groomer', phone: '028 7131 3864', address: 'Unit 1, Ballyore Business Park, Victoria Rd, Newbuildings, Londonderry BT47 2TH, UK' },
  { slug: 'paul-kelly-personal-trainer-coach', name: 'Paul Kelly Personal Trainer/Coach', category: 'personal trainer', phone: '07716 093501', address: 'Unit 43, North West Business Complex Skeoge Industrial park, Londonderry BT48 8SE, UK' },
  { slug: 'paul-mc-gowan-fitness-derry', name: 'Paul Mc Gowan Fitness Derry', category: 'personal trainer', phone: '085 775 9877', address: 'Unit 1 & 2, Springtown Industrial Estate, Springrowth Rd, Londonderry BT48 0LY, UK' },
  { slug: 'pavier-joinery', name: 'Pavier Joinery', category: 'joiner', phone: '07818 866690', address: 'Belvoir Park, Londonderry BT48 8PQ, UK' },
  { slug: 'pjm-power-electrical-contractor', name: 'PJM Power Electrical Contractor', category: 'electrician', phone: '07521 052569', address: 'Ard Grange, Londonderry BT48 0SF, UK' },
  { slug: 'plant-a-seed-landscapes', name: 'Plant A Seed Landscapes', category: 'landscaper', phone: '07746 229281', address: '51a Cromore Gardens, Londonderry BT48 9TG, UK' },
  { slug: 'platinum-puppies', name: 'Platinum Puppies', category: 'dog', phone: '07488 238101', address: '20 Rathlin Gardens, Londonderry BT48 9UE, UK' },
  { slug: 'prime-decor', name: 'Prime Decor', category: 'painter', phone: '', address: '7 Abbots Walk, Londonderry BT48 9HA, UK' },
  { slug: 'professionail-beauty-salon', name: 'ProfessioNail Beauty Salon', category: 'beauty salon', phone: '07856 000020', address: '88 Spencer Rd, Waterside, Londonderry BT47 6AG, UK' },
  { slug: 'promastix-sealants', name: 'ProMastix Sealants', category: 'handyman', phone: '', address: '20c Balliniska Rd, Londonderry BT48 0NA, UK' },
  { slug: 'quayside-valeting', name: 'Quayside Valeting', category: 'car', phone: '07522 178525', address: 'Londonderry BT48 7PX, UK' },
  { slug: 'raise-the-bar-fitness-female-personal-training-derry', name: 'Raise The Bar Fitness Female Personal Training Derry', category: 'personal trainer', phone: '07856 890786', address: 'Raise The Bar Fitness Derry, Unit 5 Balliniska Rd, Springtown Dr, Londonderry BT48 0LY, UK' },
  { slug: 'raw-fitness-derry-ltd', name: 'Raw Fitness Derry Ltd', category: 'gym', phone: '07703 326018', address: '5, Londonderry BT48 0LU, UK' },
  { slug: 'ray-mallett-painting-decorating', name: 'Ray Mallett Painting & Decorating', category: 'painter', phone: '07925 771154', address: '437 Carnhill, Londonderry BT48 8BT, UK' },
  { slug: 'reps-gym', name: 'Reps gym', category: 'gym', phone: '07725714279', address: 'unit 8, 6 Derry Rd, Omagh BT78 5DR, UK' },
  { slug: 'rjb-joinery', name: 'RJB JOINERY', category: 'joiner', phone: '07591 887868', address: 'Unit A1, Ballinska Business Park, Springtown Industrial Estate, Londonderry BT48 0LY, UK' },
  { slug: 'rmc-sports-therapy', name: 'RMC Sports Therapy', category: 'physiotherapy', phone: '07875 725663', address: '23 Ashbrook Ct, Drumahoe, Londonderry BT47 3FA, UK' },
  { slug: 'rosta-coffee-bar', name: 'Rosta coffee bar', category: 'cafe', phone: '07845 556422', address: 'Carlisle Rd, Londonderry BT48 6JW, UK' },
  { slug: 'rustic-coffee-and-brunch', name: 'Rustic Coffee and Brunch', category: 'cafe', phone: '07856 598001', address: '16 Blucher St, Londonderry BT48 9DY, UK' },
  { slug: 'sage-hair-beauty', name: 'Sage Hair & Beauty', category: 'hairdresser', phone: '07596 590617', address: '98 Spencer Rd, Londonderry BT47 6AG, UK' },
  { slug: 'salon-one-hairdressing', name: 'Salon One hairdressing', category: 'hairdresser', phone: '028 7126 2781', address: '17 The, Craft Village, Shipquay St, Londonderry BT48 6AR, UK' },
  { slug: 'salon-sixteen', name: 'Salon Sixteen', category: 'hairdresser', phone: '028 7131 2504', address: '16 Clooney Terrace, Londonderry BT47 6AR, UK' },
  { slug: 'seamusmcclafferty', name: 'Seamusmcclafferty', category: 'painter', phone: '07706 033987', address: '7 Ballymore Park, Londonderry BT48 9BP, UK' },
  { slug: 'sho-vij-fitness-female-body-tone-coach-derry', name: 'Sho Vij Fitness Female Body Tone Coach Derry', category: 'personal trainer', phone: '07935 487075', address: 'Raw Fitness Derry Ltd, Pennyburn Industrial Estate, Londonderry BT47 0LU, UK' },
  { slug: 'speedy-clean', name: 'Speedy Clean', category: 'cleaner', phone: '028 7134 7822', address: '5 Blackburn Cres, Londonderry BT47 5QG, UK' },
  { slug: 'sperrin-detail', name: 'Sperrin Detail', category: 'car', phone: '07938 988541', address: 'Unit 30, Glenshane enterprise centre, 414a Ballyquin Rd, Dungiven, Londonderry BT47 4NQ, UK' },
  { slug: 'stewart-motors', name: 'Stewart Motors', category: 'mechanic', phone: '028 7126 7579', address: '43 Barry St, Londonderry BT48 7PJ, UK' },
  { slug: 'strand-electrics', name: 'Strand Electrics', category: 'electrician', phone: '028 7126 5012', address: 'Unit 19F Pennyburn Industrial Estate, Londonderry BT48 0LU, UK' },
  { slug: 'streaks-ahead', name: 'Streaks Ahead', category: 'hairdresser', phone: '028 7128 8222', address: '21 William St, Londonderry BT48 6EP, UK' },
  { slug: 'strive-performance-center-limited', name: 'Strive Performance Center limited', category: 'personal trainer', phone: '07564 477858', address: 'Unit 8 Elagh Business Pk, Coshquin, Londonderry BT48 8QP, UK' },
  { slug: 'summerland-stores', name: 'SUMMERLAND STORES', category: 'barber', phone: '07447 821727', address: '13-15 Foyle St, Londonderry BT48 6AL, UK' },
  { slug: 'swillyvalley-boarding-kennels-cattery', name: 'Swillyvalley Boarding Kennels & Cattery', category: 'dog', phone: '(074) 936 8145', address: 'Elaghbeg, Bridge End, Co. Donegal, F93 DR90, Ireland' },
  { slug: 'the-barber-shop', name: 'The Barber Shop', category: 'barber', phone: '07544 194746', address: '82 Spencer Rd, Londonderry BT47 6AA, UK' },
  { slug: 'the-beauty-sanctuary', name: 'The Beauty Sanctuary', category: 'beauty salon', phone: '07766054844', address: '21A Hospital Rd, Magherafelt BT45 5DG, UK' },
  { slug: 'the-cottage-craft-gallery-and-coffee-shop', name: 'The Cottage Craft Gallery and Coffee Shop', category: 'cafe', phone: '07783 882521', address: 'Unit 21 The, Craft Village, Shipquay St, Londonderry BT48 6AR, UK' },
  { slug: 'the-garage', name: 'The Garage', category: 'mechanic', phone: '', address: '24 Queens Quay, Londonderry BT48 7AS, UK' },
  { slug: 'the-handyman', name: 'The Handyman', category: 'handyman', phone: '028 7181 0941', address: '42 Woodvale Mews, Eglinton, Londonderry BT47 3FE, UK' },
  { slug: 'the-rack-gym', name: 'The Rack Gym', category: 'gym', phone: '07808868880', address: '45 Dromore Rd, Omagh BT78 1RB, UK' },
  { slug: 'the-shower-doctor', name: 'The Shower Doctor', category: 'plumber', phone: '07845 587908', address: '21 Ardlough Rd, Londonderry BT47 5SW, UK' },
  { slug: 'the-specky-detailers', name: 'The Specky Detailers', category: 'car', phone: '07523 224020', address: '12 Ebrington Park, Londonderry BT47 6JE, UK' },
  { slug: 'the-waterloo-barber', name: 'The Waterloo Barber', category: 'barber', phone: '028 7126 4749', address: '44 Waterloo St, Londonderry BT48 6HF, UK' },
  { slug: 'tj-mcconnell-and-sons', name: 'TJ McConnell and Sons', category: 'plumber', phone: '028 7136 3539', address: '32 Balliniska Rd, Londonderry BT48 0NA, UK' },
  { slug: 'traditional-turkish-barber', name: 'Traditional Turkish Barber', category: 'barber', phone: '07857 997747', address: '152 Spencer Rd, Londonderry BT47 6AH, UK' },
  { slug: 'transition-derry', name: 'Transition Derry', category: 'personal trainer', phone: '07843 956960', address: '5, Swilly House, Springtown Industrial Estate, Londonderry BT48 0LY, UK' },
  { slug: 'trendy-paws-by-craig-jan', name: 'Trendy Paws By Craig Jan', category: 'dog', phone: '07522 782066', address: '27 Grangewood Ct, Londonderry BT47 5WT, UK' },
  { slug: 'wallace-auto-repairs', name: 'Wallace Auto-repairs', category: 'mechanic', phone: '028 7141 7382', address: '4 Ferguson St, Londonderry BT48 6TA, UK' },
  { slug: 'whispers-hairdressing-salon', name: 'Whispers Hairdressing Salon', category: 'hairdresser', phone: '028 7126 0595', address: '16 The Diamond, Londonderry BT48 6HW, UK' },
  { slug: 'xtreme-cleaning-services-ni', name: 'Xtreme Cleaning Services ni', category: 'cleaner', phone: '07517 003144', address: 'Creggan St, Londonderry BT48 0EU, UK' },
  { slug: 'xtreme-gym', name: 'Xtreme Gym', category: 'personal trainer', phone: '028 7134 5044', address: '2 Distillery Brae, Londonderry BT47 6AN, UK' },
  { slug: 'yoga-pilates-wellbeing-centre', name: 'Yoga & Pilates wellbeing Centre', category: 'yoga', phone: '07738 067290', address: 'Northland Road Industrial Estate, 28-29 Templemore Business Park, Londonderry BT48 0LD, UK' },
  { slug: 'zolero', name: 'Zolero', category: 'beauty salon', phone: '028 7137 0279', address: '145 Bishop St, Londonderry BT48 6UJ, UK' },
  { slug: 'bangor-mobiles', name: 'Bangor mobiles', category: 'mobile mechanic', phone: '07788 217944', address: '4 Castle St, Bangor BT20 4ST, UK' },
  { slug: 'iva-michalak-photography', name: 'Iva Michalak Photography', category: 'freelance photographer', phone: '07823 779224', address: '4 Lewis Dr, Belfast BT4 1EN, UK' },
  { slug: 'louise-gallagher-curly-hair-specialist-wavy-straight-hair-expert', name: 'Louise Gallagher Curly Hair Specialist | Wavy / Straight Hair Expert', category: 'mobile hairdresser', phone: '07815 204489', address: 'Mckibbin House, Eastbank Rd, Carryduff, Belfast BT8 8BD, UK' },
  { slug: 'sd-catering', name: 'SD Catering', category: 'catering service', phone: '07715 392022', address: '203 Shankill Rd, Belfast BT13 1FT, UK' },
  { slug: 'diamond-dogs', name: 'Diamond Dogs', category: 'dog groomer', phone: '07411 858845', address: '317 Woodstock Rd, Belfast BT6 8PT, UK' },
  { slug: 'happy-catz-little-pawz-pet-hotel', name: 'Happy Catz & Little Pawz Pet Hotel', category: 'pet sitting', phone: '07568 599990', address: '26 Ballymoney Rd, Newtownards BT23 4TG, UK' },
  { slug: 'car-valet-belfast', name: 'Car Valet Belfast', category: 'mobile car wash', phone: '07856 560430', address: '24 Barbour Gardens, Dunmurry, Belfast BT17 9AB, UK' },
  { slug: 'wash-my-ride-car-wash-valeting-centre', name: 'Wash My Ride Car Wash & Valeting Centre', category: 'mobile car wash', phone: '07743 177150', address: '107a Bloomfield Rd S, Bangor BT19 7HR, UK' },
  { slug: 'the-compound-room', name: 'The Compound Room', category: 'personal trainer', phone: '07724 403227', address: 'Unit C4, 9 Ferguson Dr, Lisburn BT28 2EX, UK' },
  { slug: 'ashvale-landscapes', name: 'Ashvale Landscapes', category: 'gardening service', phone: '07889 352808', address: '11 Old Ballynahinch Rd, Lisnastrean, Lisburn BT27 5PE, UK' },
  { slug: 'sean-leonard-school-of-motoring', name: 'SEAN LEONARD SCHOOL OF MOTORING', category: 'driving instructor', phone: '07729 370384', address: '151 Galliagh Prk, Londonderry BT48 8DF, UK' },
  { slug: 'mobile-tech', name: 'Mobile Tech', category: 'mobile mechanic', phone: '07307 212120', address: '26 Botanic Ave, Belfast BT7 1JQ, UK' },
  { slug: 'sports-massage-belfast-relax-recover', name: 'Sports Massage Belfast | Relax & Recover', category: 'mobile massage therapist', phone: '07984 967464', address: 'Belvoir Community Hub, Drumart Square, Belfast BT8 7ET, UK' },
  { slug: 'a-new-start-driving-school', name: 'A New Start Driving School', category: 'driving instructor', phone: '07990 762133', address: 'Ormeau Rd, Ormeau, Belfast BT7 3LA, UK' },
  { slug: 'oh-my-dog-belfast', name: 'Oh My Dog Belfast', category: 'dog groomer', phone: '07939 881123', address: '13 Shore Rd, Belfast BT15 3PG, UK' },
  { slug: 'lg-decorators', name: 'LG DECORATORS', category: 'painter decorator', phone: '07729 802727', address: '12 Victoria Ct, Sydenham, Belfast BT4 1RQ, UK' },
  { slug: 'lean-n-mean-personal-training', name: 'Lean \'N\' Mean Personal Training', category: 'personal trainer', phone: '07895 110730', address: 'Unit 1 S Circular Retail Park, Bangor BT19 7AG, UK' },
  { slug: 'wallace-and-donut-cafe-lisburn', name: 'Wallace and Donut - Cafe Lisburn', category: 'baker', phone: '07951 608529', address: '45 Seymour St, Lisburn BT27 4SY, UK' },
  { slug: 'the-tiling-specialist-simon-corbett', name: 'The Tiling Specialist - Simon Corbett', category: 'tiling contractor', phone: '07766 194889', address: '48 Balmoral Square, Bangor BT19 7XL, UK' },
  { slug: 'holywood-celebrity-barbers', name: 'Holywood Celebrity Barbers', category: 'mobile barber', phone: '07397 188844', address: '355 Holywood Rd, Belfast BT4 2LR, UK' },
  { slug: 'mmc-cleaning-ni-carpet-cleaning-belfast-sofa-cleaning-belfast-interior-car-valeting-belfast', name: 'MMC Cleaning NI - Carpet Cleaning Belfast & Sofa Cleaning Belfast / Interior Car Valeting Belfast', category: 'mobile car wash', phone: '07745 199990', address: '16 Old Colin, Dunmurry, Belfast BT17 0AX, UK' },
  { slug: 'holywood-turkish-barber', name: 'Holywood Turkish Barber', category: 'mobile barber', phone: '07472 723632', address: '85 High St, Holywood BT18 9AE, UK' },
  { slug: 'tc-tyres-mobile-tyre-fitting-ni', name: 'Tc tyres & mobile tyre fitting Ni', category: 'mobile mechanic', phone: '07543 119191', address: '323 Oldpark Rd, Belfast BT14 6QS, UK' },
  { slug: 'albe-s-gluten-free-sweet-bakery', name: 'ALBe\'s Gluten Free Sweet Bakery', category: 'baker', phone: '07539 852772', address: '32 Central Ave, Bangor BT20 3AF, UK' },
  { slug: 'level-up-fitness', name: 'Level Up Fitness', category: 'personal trainer', phone: '07738 853633', address: '23 Henry Pl, Belfast BT15 2AY, UK' },
  { slug: 'mobile-zone-newtownards', name: 'Mobile Zone Newtownards', category: 'mobile mechanic', phone: '07375 755234', address: '40 High St, Newtownards BT23 7HZ, UK' },
  { slug: 'jm-autos', name: 'JM Autos', category: 'mobile mechanic', phone: '07747 612977', address: '29-31 Premier Dr, Belfast BT15 3LY, UK' },
  { slug: 'biscuit-paws-dog-grooming', name: 'Biscuit Paws Dog Grooming', category: 'dog groomer', phone: '07514 829971', address: '17B High St, Donaghadee BT21 0AA, UK' },
  { slug: 'stable-door-gourmet-burgers', name: 'Stable Door Gourmet Burgers', category: 'catering service', phone: '07876 198598', address: '34 High St, Holywood BT18 9AD, UK' },
  { slug: 'belfast-dog-groomers', name: 'Belfast Dog Groomers', category: 'dog groomer', phone: '07933 282976', address: '327 Ballysillan Rd, Belfast BT14 6RE, UK' },
  { slug: 'lifestyle-performance-gym', name: 'Lifestyle & Performance Gym', category: 'personal trainer', phone: '07549 770238', address: '2 Hannahstown Hill, Hannahstown, Belfast BT17 0LT, UK' },
  { slug: 'rsm-mechanics', name: 'RSM mechanics', category: 'mobile mechanic', phone: '07591 066877', address: 'Newtownabby BT37 9QJ, UK' },
  { slug: 'quality-car-wash-valeting', name: 'Quality car wash & valeting', category: 'mobile valeting', phone: '07708 580460', address: '36 Killynure Green, Carryduff, Belfast BT8 8FA, UK' },
  { slug: 'cammy-s-grooming-spa', name: 'Cammy\'s Grooming & Spa', category: 'dog groomer', phone: '07761 505809', address: '115 Matchett St, Belfast BT13 1QD, UK' },
  { slug: 'andyman-flatpacks', name: 'Andyman Flatpacks', category: 'handyman', phone: '07588 029029', address: '68 Rosebery Rd, Belfast BT6 8JE, UK' },
  { slug: 'grade-6-adi', name: 'Grade 6 ADI', category: 'driving instructor', phone: '07525 941583', address: '26 Duncairn Gardens, Belfast BT15 2GD, UK' },
  { slug: 'belfast-tree-garden-services-pruned-topped-removed', name: 'Belfast Tree & Garden Services - Pruned /Topped/Removed', category: 'gardening service', phone: '07707 832846', address: '30 Richardson Court, Belfast BT6 8DG, UK' },
  { slug: 'paint-rite-decorators', name: 'Paint Rite Decorators', category: 'painter decorator', phone: '07710 400015', address: 'St Marks Wood, Lisburn BT28 1AQ, UK' },
  { slug: 'antonio-made-in-naples-pizzeria-napoletana', name: 'Antonio made in Naples pizzeria napoletana', category: 'mobile catering', phone: '07454 858171', address: 'St George\'s Market, 192 Falls Rd, Belfast BT12 6AG, UK' },
  { slug: 'revive-massage-dundonald', name: 'Revive Massage Dundonald', category: 'mobile massage therapist', phone: '07874 380907', address: 'A8, inspire business centre, Dundonald, Belfast BT16 1QT, UK' },
  { slug: 'drive-with-gavin', name: 'Drive With Gavin', category: 'driving instructor', phone: '07514 214480', address: 'Manor Park, Bangor BT20 3LY, UK' },
  { slug: 'jack-in-a-box-dog-grooming', name: 'Jack in a Box Dog Grooming', category: 'dog groomer', phone: '07864 987299', address: '287 Newtownards Rd, Belfast BT4 1AG, UK' },
  { slug: 'merriam-driving-lessons-in-automatic-car', name: 'Merriam Driving Lessons in automatic car', category: 'driving instructor', phone: '07737 162999', address: '17 Bridge St, Lisburn BT28 1XZ, UK' },
  { slug: 'balieys-pad-boarding-kennels', name: 'Balieys Pad Boarding Kennels', category: 'pet sitting', phone: '07931 391298', address: '16 Bailie Rd, Bangor BT19 7QW, UK' },
  { slug: 'pooches-palace-bangor', name: 'Pooches Palace Bangor', category: 'dog groomer', phone: '07548 472586', address: '91 High St, Bangor BT20 5BD, UK' },
  { slug: 'transform-fitness', name: 'Transform Fitness', category: 'personal trainer', phone: '07415 004144', address: '22, Hannahstown Business Park, Hannahstown, Belfast BT17 0LT, UK' },
  { slug: 'rhs-robin-s-handyman-services', name: 'RHS Robin\'s handyman services', category: 'handyman', phone: '07784 550820', address: '11 Windsor Ave, Lisburn BT28 1EE, UK' },
  { slug: 'boyd-mechanical', name: 'Boyd Mechanical', category: 'mobile mechanic', phone: '07521 682529', address: '188 Church Rd, Holywood BT18 9RN, UK' },
  { slug: 'the-phoneshop-lisburn', name: 'The Phoneshop Lisburn', category: 'mobile mechanic', phone: '07599 877667', address: '4 Antrim St, Lisburn BT28 1AU, UK' },
  { slug: 'amc-property-maintenance', name: 'AMC Property Maintenance', category: 'landscaping', phone: '07714 030881', address: 'Navar Dr, Bangor BT19 7SW, UK' },
  { slug: 'lifted-by-laura-personal-training', name: 'Lifted by Laura - Personal Training', category: 'personal trainer', phone: '07808 834392', address: 'Unit 2, Lesley Retail Park, Boucher Rd, Belfast BT12 6HH, UK' },
  { slug: 'north-down-barbell-club', name: 'North Down Barbell Club', category: 'personal trainer', phone: '07594 422329', address: '39 Regent St, Newtownards BT23 4AA, UK' },
  { slug: 'sol-boyles-coaching', name: 'Sol Boyles Coaching', category: 'personal trainer', phone: '07581 060117', address: 'Address 3 Rathdown walk, Lisburn, BT28 2RB, Lisburn BT27 5EA, UK' },
  { slug: 'dirty-deeds-detailing', name: 'Dirty Deeds Detailing', category: 'car detailing', phone: '07584 834769', address: 'Gwynedd Body Shop, Lower Garage, Station Rd, Bangor LL57 1LZ, UK' },
  { slug: 'gsc-autofix', name: 'GSC Autofix', category: 'mobile mechanic', phone: '07921 464971', address: '28 Balloo Dr, Bangor BT19 7QY, UK' },
  { slug: 'groom-hq', name: 'Groom HQ', category: 'dog groomer', phone: '07841 977580', address: '287 Newtownards Rd, Belfast BT4 1AG, UK' },
  { slug: 'jay-s-garden-services', name: 'Jay\'s Garden Services', category: 'gardening service', phone: '07546 610875', address: '9 Belgravia Park, Bangor BT19 6XB, UK' },
  { slug: 'coco-deshed', name: 'Coco DeShed', category: 'mobile dog grooming', phone: '07882 661864', address: '88 Trillick St, Belfast BT5 4QZ, UK' },
  { slug: 'aim2drive-ni', name: 'Aim2drive ni', category: 'driving instructor', phone: '07802 404038', address: '20 Greer Park Ave, Belfast BT8 7YF, UK' },
  { slug: 'what-the-fluff-dog-grooming-sandy-row', name: 'What the Fluff dog grooming Sandy Row', category: 'dog groomer', phone: '07717 640608', address: '127 Sandy Row, Belfast BT12 5ET, UK' },
  { slug: 'burn-more-24', name: 'Burn More 24', category: 'personal trainer', phone: '07756 339372', address: '217-219 Templemore Ave, Belfast BT5 4FS, UK' },
  { slug: 'doggie-day-centre', name: 'Doggie Day Centre', category: 'pet sitting', phone: '07580 049418', address: '73A Green Rd, Bangor BT19 7QA, UK' },
  { slug: 'strength-and-mind-fitness-studio', name: 'Strength and Mind Fitness Studio', category: 'personal trainer', phone: '07476 036384', address: '243 Castlereagh Rd, Belfast BT5 5FL, UK' },
  { slug: 'mullaneycuts-mobile-barber', name: 'Mullaneycuts Mobile Barber', category: 'mobile barber', phone: '07934 845449', address: '21 Aghagay Meadows, Newtownbutler, Enniskillen BT82 8AE, UK' },
  { slug: 'kg-gardening', name: 'KG Gardening', category: 'gardening service', phone: '07883 590844', address: '11 Tower Rd, Conlig, Newtownards BT23 7PN, UK' },
  { slug: 'dani-orr-hair', name: 'Dani Orr Hair', category: 'mobile hairdresser', phone: '07859 921430', address: '129 High St, Holywood BT18 9LG, UK' },
  { slug: 'the-groomer', name: 'The Groomer', category: 'dog groomer', phone: '07763 684271', address: 'Unit 2, 734 Upper Newtownards Rd, Belfast BT16 1RJ, UK' },
  { slug: 'jon-s-tree-services-n-i', name: 'Jon\'s Tree Services N.I', category: 'tree surgeon', phone: '07729 189181', address: '19 Henderson Dr, Bangor BT19 1NR, UK' },
  { slug: 'spellbound-styles', name: 'Spellbound Styles', category: 'dog groomer', phone: '07394 587626', address: '144 Longstone St, Lisburn BT28 1TR, UK' },
  { slug: 'auto-hut', name: 'Auto Hut', category: 'mobile mechanic', phone: '07544 280172', address: '17 Cardy Cl, Bangor BT19 1AT, UK' },
  { slug: 'posh-pooches-dog-groomers-castlereagh', name: 'Posh Pooches Dog Groomers Castlereagh', category: 'dog groomer', phone: '07738 699554', address: '126 Orby Dr, Castlereagh, Belfast BT5 6BB, UK' },
  { slug: 'puppy-love-dog-parlour', name: 'Puppy Love Dog Parlour', category: 'dog groomer', phone: '07834 557032', address: '75 Mercer St, Lisburn BT27 5AJ, UK' },
  { slug: 'urban-jungle-tree-surgeons', name: 'Urban Jungle Tree Surgeons', category: 'tree surgeon', phone: '07528 812413', address: '16 Brianville Park, Bangor BT19 6DZ, UK' },
  { slug: 'for-pup-s-sake', name: 'For Pup\'s Sake', category: 'dog groomer', phone: '07517 669178', address: '53B Church St, Newtownards BT23 4AN, UK' },
  { slug: 'doggy-styling-dog-grooming', name: 'Doggy Styling Dog Grooming', category: 'dog groomer', phone: '07551 707936', address: '34 Sydenham Park, Belfast BT4 1PW, UK' },
  { slug: 'shiny-disco-paws-dog-grooming', name: 'Shiny Disco Paws Dog Grooming', category: 'dog groomer', phone: '07730 562930', address: 'Glenhoy Dr, Belfast BT5 5LB, UK' },
  { slug: 'piccolo-mondo', name: 'Piccolo Mondo', category: 'mobile catering', phone: '07710 856811', address: '10 Edenderry Rd, Belfast BT8 8LD, UK' },
  { slug: 'counter-culture-real-bread', name: 'Counter Culture Real Bread', category: 'baker', phone: '07526 758647', address: 'Unit 71, 2-4 Balloo Ave, Bangor BT19 7QT, UK' },
  { slug: 'neutral-auto-care', name: 'Neutral Auto Care', category: 'car detailing', phone: '07951 842343', address: 'Unit 12B, Lamon Estates, 149 Glen Rd, Comber, Newtownards BT23 5QU, UK' },
  { slug: 'kellys-family-bakery', name: 'Kellys Family Bakery', category: 'baker', phone: '07921 095701', address: '252 Whitewell Rd, Newtownabbey BT36 7NH, UK' },
  { slug: 'robbie-mullan-painting-and-decorating', name: 'Robbie Mullan painting and decorating', category: 'painter decorator', phone: '07858 395168', address: '1 Copeland Square, Donaghadee BT21 0JZ, UK' },
  { slug: 'top-dog-grooming', name: 'Top Dog Grooming', category: 'dog groomer', phone: '07308 969076', address: 'Noel’s Top Dog Grooming, Sloe Cottage, 42 Holywood Rd, Belfast, Newtownards BT23 4TQ, UK' },
  { slug: 'the-beauty-bar-comber', name: 'The Beauty Bar Comber', category: 'mobile beauty therapist', phone: '07384 408121', address: 'Bt235bg, The Beauty Bar, Coronation Cres, Comber, Newtownards BT23 5BG, UK' },
  { slug: 'daisy-ducks-dog-grooming', name: 'Daisy Ducks dog grooming', category: 'dog groomer', phone: '07413 005070', address: '13 Newton Heights, Belfast BT8 6HA, UK' },
  { slug: 'every-last-detail-ni', name: 'Every Last Detail NI', category: 'mobile car wash', phone: '07738 094556', address: '258 Lagmore Meadows, Dunmurry, Belfast BT17 0TJ, UK' },
  { slug: 'diamond-detailing', name: 'Diamond Detailing', category: 'car detailing', phone: '07912 608654', address: 'Dunmurry, Belfast BT17 9HN, UK' },
  { slug: 'garden-buddy', name: 'Garden Buddy', category: 'gardening service', phone: '07591 124249', address: 'Ravenhill Ave, Belfast BT6 8LL, UK' },
  { slug: 'jc-automotive', name: 'JC Automotive', category: 'mobile mechanic', phone: '07481 305301', address: '38a Beanstown Rd, Lisburn BT28 3NY, UK' },
  { slug: 'cat-bullock-personal-training', name: 'Cat Bullock Personal Training', category: 'personal trainer', phone: '07584 033145', address: '29 High St, Bangor LL57 1NP, UK' },
  { slug: 'unbreakable-fitness-nutrition', name: 'Unbreakable Fitness & Nutrition', category: 'personal trainer', phone: '07704 952026', address: 'Belsize Rd, Lisburn, BT27 BT27 4HY, UK' },
  { slug: 'ak-decking-and-fencing', name: 'AK Decking and Fencing', category: 'landscaping', phone: '07935 198445', address: '55 Drumbeg Dr, Lisburn BT28 1PX, UK' },
  { slug: 'just-jades-mobile-barber', name: 'Just Jades Mobile Barber', category: 'mobile hairdresser', phone: '07930 850827', address: 'Ballyquinton Gardens, Bangor BT19 1SG, UK' },
  { slug: 'jr-painting-and-decorating', name: 'JR Painting and Decorating', category: 'painter decorator', phone: '07732 000944', address: '62 Willowbrook Park, Bangor BT19 7GY, UK' },
  { slug: 'gadget-hub', name: 'Gadget Hub', category: 'mobile mechanic', phone: '07344 945477', address: '27 Holywood Rd, Belfast BT4 3BA, UK' },
  { slug: 'root-branch-tree-services-ltd', name: 'Root & Branch Tree Services Ltd.', category: 'tree surgeon', phone: '07307 852155', address: '67 Church Rd, Belfast BT8 7AN, UK' },
  { slug: 'dan-gilmore', name: 'Dan Gilmore', category: 'mobile mechanic', phone: '07979 247438', address: '7 Norbury St, Belfast BT11 8AD, UK' },
  { slug: 'kasey-s-drum-lessons', name: 'Kasey\'s Drum Lessons', category: 'music teacher', phone: '07817 055097', address: '20 Clara Rd, Belfast BT5 6FN, UK' },
  { slug: 'kd-kennels', name: 'Kd Kennels', category: 'pet sitting', phone: '07809 839799', address: '8b Agars Rd, Lisburn BT28 2TQ, UK' },
  { slug: 'supreme-cleaning', name: 'Supreme Cleaning', category: 'cleaning service', phone: '07459 482836', address: '8 Creeve Pl, Lisburn BT28 1UT, UK' },
  { slug: 'vanity-fur-by-lynn', name: 'Vanity Fur by Lynn', category: 'dog groomer', phone: '07305 180620', address: '2a Cotton Road Six Road Ends Facing, Nash\'s garden center, Bangor BT19 7QG, UK' },
  { slug: 'mall-details', name: 'MALL Details', category: 'mobile car wash', phone: '07400 902920', address: '10 Church Dr, Bangor BT20 3EE, UK' },
  { slug: 'all-seasons-garden-tree-services', name: 'All Seasons Garden Tree Services', category: 'gardening service', phone: '07711 538221', address: '13 Carlton Park, Bangor BT19 6WR, UK' },
  { slug: 'mona-tamim-beauty-salon', name: 'Mona Tamim Beauty Salon', category: 'mobile beauty therapist', phone: '07877 078292', address: '29 Mount Pleasant Dr, Newtownards BT23 4WL, UK' },
  { slug: 'a-star-cleaners', name: 'A star cleaners', category: 'cleaning service', phone: '07599 516681', address: 'Shackleton Walk, Newtownards BT23 4RE, UK' },
  { slug: 'belfast-cake-boutique', name: 'Belfast Cake Boutique', category: 'wedding cake maker', phone: '07935 648281', address: '1A Ballycraigy Rd, Glengormley, Newtownabbey BT36 5ZZ, UK' },
  { slug: 'mutt-hutt-ni-ltd', name: 'Mutt Hutt NI Ltd', category: 'pet sitting', phone: '07763 578169', address: '2 Hawe Rd, Bangor BT19 6NB, UK' },
  { slug: 'beauty-holistic-therapy', name: 'Beauty & Holistic Therapy', category: 'mobile beauty therapist', phone: '07514 200344', address: '117 Milltown Rd, Belfast BT8 7XP, UK' },
  { slug: 'evergreen-tree-surgery-landscaping', name: 'Evergreen Tree Surgery & Landscaping', category: 'landscaping', phone: '07955 214345', address: 'Unit 777, Moat House, 54 Bloomfield Ave, Belfast BT5 5AD, UK' },
  { slug: 'sandra-s-luscious-cakes', name: 'Sandra\'s Luscious Cakes', category: 'wedding cake maker', phone: '07561 829565', address: '27 Glenside Park, Drumbo, Lisburn BT27 5LG, UK' },
  { slug: 'em-car-valeting', name: 'Em car valeting', category: 'mobile valeting', phone: '07494 483951', address: 'Hollyvale, Mossley, Newtownabbey BT36 5NG, UK' },
  { slug: 'barkingham-palce', name: 'Barkingham palce', category: 'dog groomer', phone: '07752 315817', address: '69 Drumbeg Dr, Lisburn BT28 1QE, UK' },
  { slug: 'rpm-mobile-tyre-and-roadside-assistance', name: 'RPM mobile tyre and roadside assistance', category: 'mobile mechanic', phone: '07938 546525', address: 'Hillhall Rd, Hillhall, Lisburn BT28 1UR, UK' },
  { slug: 'inca-road-studios', name: 'Inca Road Studios', category: 'music teacher', phone: '07515 469273', address: 'Unit 35 Enterprise Cres, Lisburn BT28 2BP, UK' },
  { slug: 'tails-and-trails-bangor', name: 'Tails and Trails Bangor', category: 'dog groomer', phone: '07803 592805', address: '18 Hampton Park, Bangor BT19 7GL, UK' },
  { slug: 'dog-lead-go', name: 'Dog Lead Go!', category: 'pet sitting', phone: '07730 398300', address: '2 Hawthorne Ct, Bangor BT20 3HR, UK' },
  { slug: 'jd-hair-hair-stylist-hair-salon-mobile-hairdresser-lisburn', name: 'JD Hair | Hair Stylist | Hair Salon | Mobile Hairdresser | Lisburn', category: 'mobile hairdresser', phone: '07889 083774', address: '14a Seymour St, Lisburn BT27 4XF, UK' },
  { slug: 'kat-s-beauty-studio-mobile-beauty-services', name: 'KAT\'S Beauty Studio & Mobile Beauty Services', category: 'mobile beauty therapist', phone: '07706 758181', address: '8 Blackhall St, Kircubbin, Newtownards BT22 2QU, UK' },
  { slug: 'beauty-lane-lisburn', name: 'Beauty Lane Lisburn', category: 'mobile beauty therapist', phone: '07841 654687', address: '53 Glen Rd, Lisburn BT27 5JR, UK' },
  { slug: 'debbie-morton-beauty-and-holistic-therapies', name: 'Debbie Morton Beauty And Holistic Therapies', category: 'mobile beauty therapist', phone: '07800 588278', address: '29 Robbys Point, Donaghadee BT21 0JU, UK' },
  { slug: 'the-dog-stylists', name: 'The Dog Stylists', category: 'dog groomer', phone: '07885 974196', address: '21 Movilla St, Newtownards BT23 7JG, UK' },
  { slug: 'wash-n-wax-worx', name: 'Wash n Wax Worx', category: 'mobile car wash', phone: '07354 036065', address: '30 Comber Rd., Newtownards BT23 4QP, UK' },
  { slug: 'castlereagh-cleaning-company', name: 'Castlereagh Cleaning Company', category: 'cleaning service', phone: '07738 007914', address: 'Castlereagh Rd, Castlereagh, Belfast BT6 9NR, UK' },
  { slug: 'k-b-painting-decorating', name: 'K.B. Painting&Decorating', category: 'painter decorator', phone: '07552 563007', address: '90 Circular Rd, Newtownards BT23 4BW, UK' },
  { slug: 'ashview-dog-grooming', name: 'Ashview Dog Grooming', category: 'dog groomer', phone: '07473 229760', address: '25 Lisbarnet Rd, Lisbane, Newtownards BT23 6AW, UK' },
  { slug: 'kings-dog-groomers', name: 'Kings Dog Groomers', category: 'dog groomer', phone: '07903 868733', address: '239 Falls Rd, Belfast BT12 6FB, UK' },
  { slug: 'dog-gone-walking-ni', name: 'Dog Gone Walking NI', category: 'pet sitting', phone: '07597 373746', address: 'Inverwood Gardens, Belfast BT4 1RG, UK' },
  { slug: 'lisburn-photography-studio', name: 'Lisburn Photography Studio', category: 'wedding photographer', phone: '07933 628585', address: '63 Bachelors Walk, Lisburn BT28 1XN, UK' },
  { slug: 'advanced-tiling-bathroom-refurbs', name: 'Advanced Tiling & Bathroom Refurbs', category: 'tiling contractor', phone: '07763 652706', address: '18 Cuttles Ct, Comber, Newtownards BT23 5YR, UK' },
  { slug: 'the-beauty-spot-by-michelle', name: 'The Beauty Spot By Michelle', category: 'mobile beauty therapist', phone: '07979 930652', address: '1 Dairy hall lane, Newtownards, Bt23 4db, Newtownards BT23 4AE, UK' },
  { slug: 'donna-s-paw-parade', name: 'Donna\'s Paw Parade', category: 'pet sitting', phone: '07900 691957', address: '19 Ringhaddy Park, Newtownards BT23 8XQ, UK' },
  { slug: 'big-4-garden-maintenance', name: 'Big 4 Garden Maintenance', category: 'gardening service', phone: '07849 737430', address: '30 Blenheim Dr, Newtownards BT23 4RA, UK' },
  { slug: 'paws-in-safe-hands', name: 'Paws in Safe Hands.', category: 'pet sitting', phone: '07540 746840', address: '90 Broomhill Park, Coleraine BT51 3AN, UK' },
  { slug: 'mcdog-s-play-centre-lisburn', name: 'Mcdog\'s Play Centre Lisburn', category: 'pet sitting', phone: '07379 145201', address: '47 Waterloo Rd, Lisburn BT27 5NW, UK' },
  { slug: 'welcome-thai-message', name: 'Welcome Thai message', category: 'mobile massage therapist', phone: '07922 797794', address: 'McKeown St, Lisburn BT28 1BD, UK' },
  { slug: 'ya-filthy-animals-bangor', name: 'Ya Filthy Animals Bangor', category: 'dog groomer', phone: '07359 327196', address: 'Unit 29, 8 Balloo Dr, Bangor BT19 7QY, UK' },
  { slug: 'wellness-clinic', name: 'Wellness Clinic', category: 'mobile massage therapist', phone: '07763 742014', address: '4 Henalta Wood, Bangor BT19 1FQ, UK' },
  { slug: 'nuba-wax-car-wax-products-northern-ireland', name: 'Nuba Wax - Car Wax Products Northern Ireland', category: 'car detailing', phone: '07773 817115', address: '6 Clifton Mnr, Bangor BT20 5DZ, UK' },
  { slug: 'kennedy-tiling', name: 'Kennedy tiling', category: 'tiling contractor', phone: '07886 793650', address: '17 Fernbank Rd, Bangor BT19 6GA, UK' },
  { slug: 'beautybysiobhan', name: 'Beautybysiobhan', category: 'mobile beauty therapist', phone: '07814 380201', address: '18 South Street Access, via, car park, South St, Newtownards BT23 4JT, UK' },
  { slug: 'the-paw-wash', name: 'The Paw Wash', category: 'dog groomer', phone: '07596 590218', address: '2 Mill St, Newtownards BT23 4LU, UK' },
  { slug: 'ma-lawns-and-landscaping', name: 'MA Lawns And Landscaping', category: 'gardening service', phone: '07583 696780', address: '47 River Hill Ln, Newtownards BT23 7GQ, UK' },
  { slug: 'elite-personal-training-studio', name: 'Elite Personal Training Studio', category: 'personal trainer', phone: '07921 908303', address: 'Unit 22, 308 Albertbridge Rd, Belfast BT5 4GX, UK' },
  { slug: 'massage-therapy-gosia', name: 'Massage Therapy-Gosia', category: 'mobile massage therapist', phone: '07463 439944', address: '11 Glenbryn Park, Belfast BT14 7JG, UK' },
  { slug: 'shine-mobile-valeting', name: 'Shine Mobile Valeting', category: 'mobile car wash', phone: '07983 226227', address: '3 Ballywillin Cres, Portrush BT56 8GJ, UK' },
  { slug: 'hidden-beauty', name: 'Hidden Beauty', category: 'mobile beauty therapist', phone: '07714 536918', address: 'Unit 224 Enterprise Cres, Lisburn BT28 2BP, UK' },
  { slug: 'stonebridge-painting-and-decorating', name: 'Stonebridge Painting and Decorating', category: 'painter decorator', phone: '07967 087534', address: '3 Stonebridge Ct, Stonyford, Lisburn BT28 3EL, UK' },
  { slug: 'bonnie-b-s-cattery', name: 'Bonnie B\'s Cattery', category: 'pet sitting', phone: '07834 556254', address: '16 Cranley Dr, Bangor BT19 7BZ, UK' },
  { slug: 'jacobs-house-dog-home-boarding-kennels-ards-peninsula-northern-ireland', name: 'Jacobs House Dog Home Boarding Kennels Ards Peninsula Northern Ireland', category: 'pet sitting', phone: '07557 580777', address: '10 Hillside, Portavogie, Newtownards BT22 1EZ, UK' },
  { slug: 'precision-details', name: 'Precision Details', category: 'mobile car wash', phone: '07403 766743', address: '8 Ensbury Dr, Bangor BT19 6UF, UK' },
  { slug: 'the-beauty-studio', name: 'The Beauty Studio', category: 'mobile beauty therapist', phone: '07361 253721', address: '29 Church Rd, Holywood BT18 9BU, UK' },
  { slug: 'lauren-pinkney-health-fitness-ltd', name: 'lauren pinkney health & fitness ltd', category: 'personal trainer', phone: '07402 953082', address: 'Unit C6, Park, Strangford House, Jubilee Rd, Newtownards BT23 4YH, UK' },
  { slug: 'learn-to-drive-with-craig', name: 'Learn to drive with Craig', category: 'driving instructor', phone: '07740 192927', address: 'Lisbane Dr, Newtownards BT23 4PY, UK' },
  { slug: 'gibsons-grooms-mobile-dog-groomer', name: 'Gibsons Grooms (Mobile Dog Groomer)', category: 'mobile dog grooming', phone: '07858 304615', address: '202 Moira Rd, Lisburn BT28 2SN, UK' },
  { slug: 'kitty-sitter-ni', name: 'Kitty Sitter NI', category: 'pet sitting', phone: '07808 522431', address: 'Crumlin Rd, Belfast BT14 7EE, UK' },
  { slug: 'antrim-pet-services', name: 'Antrim Pet Services', category: 'pet sitting', phone: '07525 182003', address: '40 Kilgavanagh Rd, Antrim BT41 2LJ, UK' },
  { slug: 'keencut-gardens', name: 'KeenCut Gardens', category: 'gardening service', phone: '07365 958989', address: 'Glendarragh, Belfast BT4 2WB, UK' },
  { slug: 'acorn-wood-services', name: 'Acorn wood services', category: 'tree surgeon', phone: '07849 965593', address: 'Millreagh Grv, Belfast BT16 1AH, UK' },
  { slug: 'belfast-car-mechanic-breakdown-recovery', name: 'Belfast Car Mechanic & Breakdown Recovery', category: 'mobile mechanic', phone: '07955 977616', address: 'Unit 2, 10 Hydepark Rd, Newtownabbey BT36 4PY, UK' },
  { slug: 'auto-electric-services', name: 'Auto Electric Services', category: 'mobile mechanic', phone: '07964 018331', address: '8 My Ladys Rd, Belfast BT6 8FB, UK' },
  { slug: 'poppy-s-pawsome-pups-dog-groomers-lisburn', name: 'Poppy\'s Pawsome Pups Dog Groomers Lisburn', category: 'dog groomer', phone: '07900 353002', address: '12 Bridge St, Lisburn BT28 1XZ, UK' },
  { slug: 'premier-detailing-ni', name: 'Premier detailing ni', category: 'mobile car wash', phone: '07734 791302', address: '25 Hillhall Rd, Lisburn BT27 5BX, UK' },
  { slug: 'helen-s-bay-dog-grooming', name: 'Helen\'s Bay Dog Grooming', category: 'dog groomer', phone: '07729 038420', address: '10 Coastguard Ave, Helen\'s Bay, Bangor BT19 1JY, UK' },
  { slug: 'bayview-mobile-caravan-cleaning', name: 'Bayview Mobile Caravan Cleaning', category: 'mobile car wash', phone: '07454 908365', address: '1 Cove Ln, Groomsport, Bangor BT19 6HU, UK' },
  { slug: 'vivid-external-cleaning-services', name: 'Vivid External Cleaning Services', category: 'cleaning service', phone: '07584 949582', address: '71 Green Rd, Bangor BT19 7QA, UK' },
  { slug: 'little-mama-health-beauty', name: 'Little Mama Health & Beauty', category: 'mobile beauty therapist', phone: '07539 722035', address: 'Suite 5, Regent House, 35 Regent St, Newtownards BT23 4AD, UK' },
  { slug: 'limitless-fitness', name: 'Limitless Fitness', category: 'personal trainer', phone: '07340 797233', address: 'Unit 5, The Precinct, South St, Newtownards BT23 4JT, UK' },
  { slug: 'momentum-health-fitness', name: 'Momentum Health & Fitness', category: 'personal trainer', phone: '07902 933656', address: '35 Hawthorn Hill, Newtownards BT23 8ET, UK' },
  { slug: 'c-m-d-ground-tree-services', name: 'C M D Ground & Tree Services', category: 'tree surgeon', phone: '07715 116010', address: '42 Cloughey Rd, Portaferry, Newtownards BT22 1NQ, UK' },
  { slug: 'dolores-mccormick-registered-childminder', name: 'Dolores McCormick Registered Childminder', category: 'chilminder', phone: '07933 603285', address: '49 Strangford Rd, Downpatrick BT30 6SL, UK' },
  { slug: 'lambeg-dog-walkers', name: 'lambeg dog walkers', category: 'pet sitting', phone: '07748 247675', address: 'Seymour St, Lisburn BT27 4XF, UK' },
  { slug: 'mrs-b-s-precious-paws-pet-sitting-and-cattery', name: 'Mrs B’s Precious Paws Pet Sitting and Cattery', category: 'pet sitting', phone: '07796 786731', address: '15 Aghnacarra Rd, Lisbellaw, Enniskillen BT94 5HX, UK' },
  { slug: 'emerald-autocare', name: 'Emerald Autocare', category: 'mobile car wash', phone: '07507 712017', address: 'Blaris Rd, Lisburn BT27 5RA, UK' },
  { slug: 'lisburn-cabs-company', name: 'Lisburn Cabs Company', category: 'taxi service', phone: '07779 559595', address: 'Lisburn BT28 2RH, UK' },
  { slug: 'puppylove-dog-grooming-ni', name: 'PuppyLove dog grooming NI', category: 'dog groomer', phone: '07522 931674', address: '28 Central Ave, Bangor BT20 3AF, UK' },
  { slug: 'elite-pet-styling', name: 'Elite pet styling', category: 'dog groomer', phone: '07565 480438', address: '24 Brook Ln, Bangor BT19 1ST, UK' },
  { slug: 'relight-mind-body', name: 'Relight - Mind & Body', category: 'personal trainer', phone: '07725 356675', address: 'Main St, Bangor BT20 4HD, UK' },
  { slug: 'jb-photography-online', name: 'JB Photography Online', category: 'event photographer', phone: '07925 294815', address: '8 Rock Hill, Donaghadee, Bangor BT21 0FB, UK' },
  { slug: 'groundsmen-garden-fencing-services', name: 'GroundsMen Garden & Fencing Services', category: 'gardening service', phone: '07851 047614', address: '33 Ballyhalbert Gardens, Bangor BT19 1SE, UK' },
  { slug: 'c-p-tree-services', name: 'C.P. Tree Services', category: 'tree surgeon', phone: '07889 359754', address: 'Victoria Rd, Bangor BT20 5EX, UK' },
  { slug: 'ine-mcmenamin-piano-and-cello-tuition', name: 'Áine McMenamin Piano and Cello Tuition', category: 'music teacher', phone: '07845 836846', address: '7 Stonebridge Square, Conlig, Bangor, Newtownards BT23 7QU, UK' },
  { slug: 'rgs-drive-safe', name: 'RGS Drive Safe', category: 'driving instructor', phone: '07850 552626', address: 'Sinclair Dell, Bangor BT19 1ED, UK' },
  { slug: 'abfab-painters-and-decorators', name: 'ABFAB Painters And Decorators', category: 'painter decorator', phone: '07808 540732', address: '12 Devon Dr, Sydenham, Belfast BT4 1LF, UK' },
  { slug: 'pawz-4-fun', name: 'Pawz 4 Fun', category: 'pet sitting', phone: '07885 499863', address: '25 Springmount Rd, Ballygowan, Newtownards BT23 6NF, UK' },
  { slug: 'your-style-spraying-solutions', name: 'Your Style Spraying Solutions', category: 'painter decorator', phone: '07904 976189', address: '9 Movilla Mews, Newtownards BT23 8WN, UK' },
  { slug: 'jet-n-vac-cleaning-services', name: 'Jet n Vac cleaning services', category: 'cleaning service', phone: '07817 284844', address: 'Cairndore Way, Newtownards BT23 8PB, UK' },
  { slug: 'nina-s-notes', name: 'Nina’s Notes', category: 'music teacher', phone: '07783 127025', address: '1 Whiterock Rd, Killinchy, Newtownards BT23 6PR, UK' },
  { slug: 'power-pups-grooming', name: 'Power Pups Grooming', category: 'mobile dog grooming', phone: '07948 091017', address: '174G Lenadoon Ave, Belfast BT11 9HF, UK' },
  { slug: 'greenfingers-gardening-services', name: 'Greenfingers Gardening Services', category: 'gardening service', phone: '07878 761896', address: '42 Mount Eagles Square, Dunmurry, Belfast BT17 0GZ, UK' },
  { slug: 'nanny-b-s-childminding', name: 'Nanny B\'s Childminding', category: 'chilminder', phone: '07739 404549', address: '155 Horn Dr, Belfast BT11 9NF, UK' },
  { slug: 'tim-the-mobile-barber', name: 'Tim The Mobile Barber', category: 'mobile hairdresser', phone: '07921 354588', address: '04 Ardvanagh Park, Bangor, Newtownards BT23 7XG, UK' },
  { slug: 'the-bakery', name: 'The Bakery', category: 'baker', phone: '07352 961228', address: '105 Alliance Ave, Belfast BT14 7NT, UK' },
  { slug: 'soanna-beauty', name: 'Soanna Beauty', category: 'mobile beauty therapist', phone: '07766 074157', address: '511 Upper Newtownards Rd, Belfast BT4 3LL, UK' },
  { slug: 'suds-snips', name: 'Suds & Snips', category: 'dog groomer', phone: '07741 572050', address: '91 Park Ave, Belfast BT4 1JJ, UK' },
  { slug: 'magee-landscapes-garden-maintenance', name: 'Magee Landscapes & Garden Maintenance', category: 'gardening service', phone: '07557 298592', address: '9B Ballyvannon Rd, Upper Ballinderry, Lisburn BT28 2LD, UK' },
  { slug: 'crumbs', name: 'Crumbs', category: 'mobile catering', phone: '07784 412886', address: 'Lisburn BT28 1RT, UK' },
  { slug: 'blankets-bones', name: 'Blankets & Bones', category: 'pet sitting', phone: '07747 842221', address: '46 Cleland Park N, Bangor BT20 3EN, UK' },
  { slug: 'garden-worx', name: 'Garden worx', category: 'gardening service', phone: '07719 767129', address: '20 Woodford Grange, Bangor BT19 6ZA, UK' },
  { slug: 'easy-lay-tiling', name: 'Easy Lay Tiling', category: 'tiling contractor', phone: '07974 692490', address: '39 Whitethorn Dr, Newtownards BT23 8WS, UK' },
  { slug: '54-degrees-north-landscape-photography', name: '54 Degrees North Landscape Photography', category: 'freelance photographer', phone: '07892 899961', address: '73 St George\'s Market, 69 Oxford St, Belfast BT1 3LA, UK' },
  { slug: 'the-beauty-rooms', name: 'The Beauty Rooms', category: 'mobile beauty therapist', phone: '07813 984835', address: '300 Bangor Rd, Newtownards BT23 7PH, UK' },
  { slug: 'debut-drive', name: 'Debut Drive', category: 'driving instructor', phone: '07834 468641', address: '7 Benford Dr, Newtownards BT23 8TH, UK' },
  { slug: 'drakes-landscaping-handyman-services', name: 'Drakes Landscaping & Handyman Services', category: 'handyman', phone: '07707 321794', address: 'Moyle Walk, Belfast BT8 7ER, UK' },
  { slug: 'ivanhoe-painters-decorators', name: 'Ivanhoe Painters & Decorators', category: 'painter decorator', phone: '07719 324897', address: '560 Saintfield Rd, Belfast BT8 8BL, UK' },
  { slug: 'lk-tiling', name: 'LK Tiling', category: 'tiling contractor', phone: '07779 091376', address: '73 Carlane Rd, Randalstown, Antrim BT41 3LY, UK' },
  { slug: 'midnight-cakes', name: 'Midnight Cakes', category: 'wedding cake maker', phone: '07872 427237', address: '50 Ravenhill Ave, Belfast BT6 8LG, UK' },
  { slug: 'aot-autocare', name: 'AOT Autocare', category: 'car detailing', phone: '07909 962267', address: '24 Annadale Ter, Belfast BT7 3DH, UK' },
  { slug: 'ards-handyman-services', name: 'Ards Handyman Services', category: 'handyman', phone: '07766 004100', address: 'A20, Comber, Newtownards BT23 5AZ, UK' },
  { slug: 'allfit', name: 'allFIT', category: 'personal trainer', phone: '07545 004196', address: 'Unit 37, Enterprise Organisation, Lisburn BT28 2BP, UK' },
  { slug: 'paddywhacks-groom-room', name: 'Paddywhacks Groom Room', category: 'dog groomer', phone: '07843 806373', address: 'Pod 4, 19 Enterprise Rd, Bangor BT19 7TA, UK' },
  { slug: 'eat-fit-ni', name: 'Eat Fit NI', category: 'personal trainer', phone: '07598 725818', address: '95a Victoria Rd, Bangor BT20 5ER, UK' },
  { slug: 'mmb-catering', name: 'MMB Catering', category: 'mobile catering', phone: '07746 419272', address: '21 Carnony Rd, Omagh BT79 7TF, UK' },
  { slug: 'c-a-m-cleaning-solutions', name: 'C.A.M Cleaning Solutions', category: 'cleaning service', phone: '07485 416197', address: '210 High St, Bangor LL57 1NY, UK' },
  { slug: 'prestige-car-valeting-detailing', name: 'Prestige Car Valeting & Detailing', category: 'mobile car wash', phone: '07734 231374', address: '8 Redburn Square, Holywood BT18 9JF, UK' },
  { slug: 'dogface-grooming', name: 'DogFace Grooming', category: 'dog groomer', phone: '07542 927085', address: '9 Bridge St, Comber, Newtownards BT23 5AT, UK' },
  { slug: 'great-tails', name: 'Great Tails', category: 'pet sitting', phone: '07707 355087', address: 'Manse Rd, Glastry, Newtownards BT22 1DR, UK' },
  { slug: 'philippa-whitham-complementary-therapist-speaclist-in-integrative-holistic-therapy-for-cancer-and-palliative-care-patients', name: 'Philippa Whitham Complementary Therapist (Speaclist in integrative holistic therapy for cancer and palliative care patients)', category: 'mobile massage therapist', phone: '07379 289242', address: '4 Abbey Mews, Newtownards BT23 8FA, UK' },
  { slug: 'cb-detailing-valet', name: 'CB Detailing & Valet', category: 'car detailing', phone: '07568 536486', address: '4 Strangford Heights, Newtownards BT23 8ND, UK' },
  { slug: 'care-cabs', name: 'Care Cabs', category: 'taxi service', phone: '07496 363657', address: '5 Gibsons Ln, Newtownards BT23 4LJ, UK' },
  { slug: 'fareways-taxis', name: 'FAREWAYS TAXIS', category: 'taxi service', phone: '07766 708280', address: '14 Quinton Park, Newtownards BT23 4PR, UK' },
  { slug: 'purple-taxi', name: 'purple taxi', category: 'taxi service', phone: '07922 582419', address: '1A Blackabbey Rd, Greyabbey, Newtownards BT22 2RH, UK' },
  { slug: 'alastair-smyth-driving-instructor', name: 'Alastair Smyth Driving Instructor', category: 'driving instructor', phone: '07711 145110', address: '52 Lawnbrook Dr, Newtownards BT23 8XD, UK' },
  { slug: 'kerry-s-mobile-dog-grooming', name: 'Kerry\'s Mobile Dog Grooming', category: 'mobile dog grooming', phone: '07989 793462', address: '10 Avonmere, Craigavon BT64 1AN, UK' },
  { slug: 'mojo-s-mobile-dog-grooming', name: 'Mojo\'s Mobile Dog Grooming', category: 'mobile dog grooming', phone: '07748 464850', address: 'Ballyphilip Rd, Portaferry, Newtownards BT22 1RD, UK' },
  { slug: 'four-seasons-landscaping-n-i', name: 'Four seasons landscaping N.I', category: 'landscaping', phone: '07732 341215', address: '21 Springfield Meadows, Belfast BT13 3QS, UK' },
  { slug: 'gh-tiling', name: 'GH Tiling', category: 'tiling contractor', phone: '07837 893981', address: '54 Roddens Cres, Belfast BT5 7JP, UK' },
  { slug: 'maple-tree-childminding', name: 'Maple Tree Childminding', category: 'chilminder', phone: '07879 265501', address: '26 Ashley Park, Armagh BT60 1EU, UK' },
  { slug: 'ideal-decorators', name: 'Ideal decorators', category: 'painter decorator', phone: '07706 917665', address: '312 Springfield Rd, Belfast BT12 7DS, UK' },
  { slug: 'the-car-cleaning-centre', name: 'The car cleaning centre', category: 'mobile car wash', phone: '07841 508348', address: '219A Moira Rd, Lisburn BT28 2ST, UK' },
  { slug: 'rjh-painting-decorating', name: 'RJH Painting & Decorating', category: 'painter decorator', phone: '07738 830315', address: '31 Lagmore Grove, Dunmurry, Belfast BT17 0TD, UK' },
  { slug: 'cdg-oven-cleaning', name: 'CDG Oven Cleaning', category: 'cleaning service', phone: '07512 136803', address: '81 Mornington Ave, Lisburn BT28 2WP, UK' },
  { slug: 'bump-to-birth-ni', name: 'Bump to birth NI', category: 'babysitting service', phone: '07809 313559', address: '11 Ayrshire Park, Lisburn BT28 2LT, UK' },
  { slug: 'paul-beattie-guitar-lessons-aghalee', name: 'Paul Beattie Guitar Lessons Aghalee', category: 'music teacher', phone: '07962 056409', address: '28 Beechfield Lodge, Aghalee, Lisburn BT67 0GA, UK' },
  { slug: 'mossgarden', name: 'Mossgarden', category: 'gardening service', phone: '07803 772763', address: '2 Pinehill Ave, Bangor BT19 6NY, UK' },
  { slug: 'k-ashton-landscaping-and-tree-services', name: 'K Ashton Landscaping and Tree Services', category: 'landscaping', phone: '07917 850304', address: '101 Penrhyn Ave, Bangor LL57 1LT, UK' },
  { slug: 'jaime-marshall-hair', name: 'Jaime Marshall Hair', category: 'mobile hairdresser', phone: '07933 114766', address: 'Solo hair, 129 High St, Holywood BT18 9LG, UK' },
  { slug: 'hairy-pawters', name: 'Hairy Pawters', category: 'dog groomer', phone: '07761 610017', address: '102 Ballyregan Rd, Dundonald, Northern Ireland BT18, UK' },
  { slug: 'whitehouse-decor', name: 'Whitehouse Decor', category: 'painter decorator', phone: '07903 197365', address: '19 Graymount Rd, Newtownabbey BT36 7DR, UK' },
  { slug: 'hillside-garden-services', name: 'Hillside Garden Services', category: 'gardening service', phone: '07359 790114', address: 'Main Rd, Portavogie, Newtownards BT22 1EL, UK' },
  { slug: 'peter-dempster-tiling-services', name: 'Peter Dempster Tiling Services', category: 'tiling contractor', phone: '07835 508444', address: 'Longlands Dr, Comber, Newtownards BT23 5AL, UK' },
  { slug: 'ac-cleaning-services', name: 'AC Cleaning Services', category: 'cleaning service', phone: '07790 443417', address: '8A Loughdoo Rd, Ardkeen, Newtownards BT22 1HJ, UK' },
  { slug: 'your-image-nail-beauty', name: 'Your Image Nail & Beauty', category: 'mobile beauty therapist', phone: '07849 454163', address: '36 Knockbreda Rd, Belfast BT6 0JB, UK' },
  { slug: 'bb-easyway-flat-pack-assembly-removals-hadyman', name: 'BB EasyWay Flat pack assembly removals hadyman', category: 'handyman', phone: '07816 585707', address: '15 Leggagh Ct, Belfast BT14 8AY, UK' },
  { slug: 'brush-strokes', name: 'Brush Strokes', category: 'painter decorator', phone: '07974 355675', address: 'Apartment 5.2, 62 Donegall Quay, Holywood, Belfast BT1 3NG, UK' },
  { slug: 'shm-tiling-services', name: 'SHM Tiling Services', category: 'tiling contractor', phone: '07835 603346', address: '76 Glenview Park, Newtownabbey BT37 0TG, UK' },
  { slug: 'auto-check', name: 'Auto Check', category: 'MOT testing', phone: '07522 264111', address: '35 Juniper Rise, Dunmurry, Belfast BT17 0BG, UK' },
  { slug: 'claire-wilson-childminding', name: 'Claire Wilson Childminding', category: 'chilminder', phone: '07538 786531', address: 'Weavers Ln, Craigavon BT66 7UE, UK' },
  { slug: 'the-handyman-service', name: 'The Handyman Service', category: 'handyman', phone: '07935 410491', address: '42 Main St, Maghera BT46 5AE, UK' },
  { slug: 'nw-mobile-mechanic', name: 'Nw mobile mechanic', category: 'mobile mechanic', phone: '07365 353921', address: '72 Dunderg Rd, Coleraine BT51 4NE, UK' },
  { slug: 'jb-autoshine-ni', name: 'JB AUTOSHINE NI', category: 'mobile car wash', phone: '07504 661803', address: 'Lisburn BT27 4PA, UK' },
  { slug: 'dm-painting-decorating', name: 'DM Painting & Decorating', category: 'painter decorator', phone: '07803 824328', address: '14 Castlevue Gardens, Moira, Craigavon BT67 0DU, UK' },
  { slug: 'pawsome-grooms', name: 'Pawsome Grooms', category: 'dog groomer', phone: '07902 048933', address: '69 High Bangor Rd, Donaghadee BT21 0PW, UK' },
  { slug: 'the-pet-nannies', name: 'The Pet Nannies', category: 'pet sitting', phone: '07880 678850', address: 'Bangor BT20 4NW, UK' },
  { slug: 'scallywaggs-dog-walking-pet-sitting', name: 'ScallyWaggs Dog Walking & Pet Sitting', category: 'pet sitting', phone: '07515 653226', address: '9 Quarry Ct, Helen\'s Bay, Bangor BT19 1TY, UK' },
  { slug: 'walk-n-wagz-north-down', name: 'Walk \'N\' Wagz North Down', category: 'pet sitting', phone: '07516 453441', address: 'Co.down, 11 Sunningdale Park, Bangor BT20 4UU, UK' },
  { slug: 'county-down-small-pet-holiday-boarding', name: 'County Down Small Pet Holiday Boarding', category: 'pet sitting', phone: '07895 044835', address: 'Meadowvale Park, Newcastle BT33 0TH, UK' },
  { slug: 'ards-painting-decorating', name: 'Ards Painting & Decorating', category: 'painter decorator', phone: '07746 171543', address: '22 Ardmillan Cres, Newtownards BT23 4PW, UK' },
  { slug: 'contract-autos', name: 'Contract Autos', category: 'mobile mechanic', phone: '07929 279357', address: '73a Green Rd, Bangor BT19 7QA, UK' },
  { slug: 'beatbox-music-studio', name: 'Beatbox Music Studio', category: 'music teacher', phone: '07927 236316', address: '42, Dunlop Industrial Units, 8 Balloo Dr, Bangor BT19 7QY, UK' },
  { slug: 'scott-fulton-driving-instruction', name: 'Scott Fulton Driving Instruction', category: 'driving instructor', phone: '07740 933403', address: '42 Ardvanagh Dr, Bangor, Newtownards BT23 7XQ, UK' },
  { slug: 'hair-by-gillian', name: 'Hair by Gillian', category: 'mobile hairdresser', phone: '07743 524794', address: '39 Brownlow St, Comber, Newtownards BT23 5EP, UK' },
  { slug: 'hairy-styles', name: 'Hairy Styles', category: 'dog groomer', phone: '07845 467861', address: 'B7, Park, Strangford House, Jubilee Rd, Newtownards BT23 4YH, UK' },
  { slug: 'meraki-in-focus', name: 'Meraki in Focus', category: 'event photographer', phone: '07738 493613', address: '10 Cambourne Mews, Newtownards BT23 4WB, UK' },
  { slug: 'photo-restoration-er', name: 'Photo Restoration ER', category: 'freelance photographer', phone: '07500 787972', address: '48 Beverley Walk, Newtownards BT23 7UQ, UK' },
  { slug: 'rb-gardening-services', name: 'RB Gardening Services', category: 'gardening service', phone: '07761 468659', address: '5 Tower Park, Conlig, Newtownards BT23 7PL, UK' },
  { slug: 'wrightscuts', name: 'WrightsCuts', category: 'landscaping', phone: '07710 444594', address: 'Dermott Ave, Comber, Newtownards BT23 5JF, UK' },
  { slug: 'dani-s-home-hair', name: 'Dani\'s Home Hair', category: 'mobile hairdresser', phone: '07740 046652', address: '4 Garranard Park, Belfast BT4 2GL, UK' },
  { slug: 'handyman-ni', name: 'Handyman NI', category: 'handyman', phone: '07842 723238', address: '33 Ainsworth Dr, Belfast BT13 3EJ, UK' },
  { slug: 'handyman-services-ni', name: 'Handyman Services Ni', category: 'handyman', phone: '07817 608122', address: '13 Chichester Rd, Belfast BT15 5EJ, UK' },
  { slug: 'id-painting-decorating', name: 'ID Painting & Decorating', category: 'painter decorator', phone: '07857 974046', address: '51 Mountcollyer Ave, Belfast BT15 3DR, UK' },
  { slug: 'bowen-tile', name: 'Bowen Tile', category: 'tiling contractor', phone: '07519 512730', address: '15 Rochester Dr, Castlereagh, Belfast BT6 9JX, UK' },
  { slug: 'jasmine-s-kitchen', name: 'Jasmine\'s Kitchen', category: 'mobile catering', phone: '07402 975851', address: '23 Castlereagh Pl, Belfast BT5 4NN, UK' },
  { slug: 'happy-home-child-care', name: 'Happy Home Child Care', category: 'chilminder', phone: '07872 121565', address: '19 Hightown Dr, Newtownabbey BT36 7TG, UK' },
  { slug: 'happy-tailz-bed-biscuits', name: 'HAPPY TAILZ BED & BISCUITS', category: 'pet sitting', phone: '07775 786417', address: '64 Mullaghsandall Road, Larne BT40 2LY, UK' },
  { slug: 'painter-and-decorator-belfast', name: 'Painter and Decorator Belfast', category: 'painter decorator', phone: '07418 342355', address: '2/321 Albertbridge Rd, Belfast BT5 4PY, UK' },
  { slug: 'the-nurtured-baby-hub', name: 'The Nurtured Baby Hub', category: 'babysitting service', phone: '07732 894168', address: 'The Mount, Belfast BT5 4NA, UK' },
  { slug: 'josie-s-bed-biscuit', name: 'Josie’s Bed & Biscuit', category: 'pet sitting', phone: '07787 087618', address: 'Gortnessy Meadows, Lettershendony, Londonderry BT47 3FW, UK' },
  { slug: 'accent-music-belfast', name: 'Accent Music Belfast', category: 'music teacher', phone: '07841 163179', address: '34 Woodview Dr, Belfast BT5 7PY, UK' },
  { slug: 'd-p-autos-mobile-mechanic', name: 'D&P Autos mobile mechanic', category: 'mobile mechanic', phone: '07367 695903', address: 'Donemana, Stoneybrook BT82 0FE, UK' },
  { slug: 'the-barking-lounge', name: 'The Barking Lounge', category: 'dog groomer', phone: '07546 317598', address: 'Woodbrook Ave, Lisburn BT28 2ZG, UK' },
  { slug: 'belsize-landscapes', name: 'Belsize Landscapes', category: 'landscaping', phone: '07753 357172', address: '55 Belsize Rd, Lisburn BT27 4BS, UK' },
  { slug: 'dc-tree-care-specialist', name: 'DC TREE CARE SPECIALIST', category: 'tree surgeon', phone: '07490 674603', address: 'Lusk Transport Ltd, 48 Knockany Rd, Lisburn BT27 6YB, UK' },
  { slug: 'rb-tiling-services', name: 'RB Tiling Services', category: 'tiling contractor', phone: '07840 155680', address: '25 Coronation Gardens, County, Antrim, Lisburn BT27 5RG, UK' },
  { slug: 'ducklings-daycare', name: 'Ducklings Daycare', category: 'babysitting service', phone: '07795 600860', address: '19 Mount Eagles Ave, Belfast, Dunmurry, Lisburn BT17 0GT, UK' },
  { slug: 'rock-solid-guitar-studio', name: 'Rock Solid Guitar Studio', category: 'music teacher', phone: '07533 551741', address: '26 Llewellyn Ave, Lisburn BT27 4AG, UK' },
  { slug: 'ross-s-pet-collective', name: 'Ross\'s Pet Collective', category: 'pet sitting', phone: '07864 861761', address: '11 Oakwood Park, Bangor BT20 3TR, UK' },
  { slug: '3f-personal-training', name: '3F Personal Training', category: 'personal trainer', phone: '07711 249346', address: '24 Fifth Ave, Baylands Ct, Bangor BT20 5JP, UK' },
  { slug: 'l-e-valets', name: 'L.E valets', category: 'mobile car wash', phone: '07596 108664', address: '20 Perry Dr, Bangor, BT196UD BT19 6UD, UK' },
  { slug: 'clearcut-details-valeting', name: 'ClearCut Details & Valeting', category: 'mobile car wash', phone: '07714 214328', address: 'The Pitstop 39 Balloo Road Bangor County Down, Bangor BT19 7PG, UK' },
  { slug: 'ld-detailing', name: 'Ld detailing', category: 'car detailing', phone: '07805 737610', address: '7 Dixon Rd, Bangor BT19 6AU, UK' },
  { slug: 'brush-strokes-painting-and-decorating', name: 'Brush Strokes Painting and Decorating', category: 'painter decorator', phone: '07436 266515', address: '12 Mason St, Bangor LL57 1DE, UK' },
  { slug: 'bridget-benson-l-t-c-l-flute-teacher', name: 'Bridget Benson L.T.C.L . Flute Teacher', category: 'music teacher', phone: '07712 627888', address: '22 Bellevue, Bangor BT20 5QW, UK' },
  { slug: 'starskynclutch', name: 'StarskyNClutch', category: 'driving instructor', phone: '07494 282256', address: 'Ballyholme Rd, Bangor BT20, UK' },
  { slug: 'icing-on-the-cake', name: 'Icing on the Cake', category: 'wedding cake maker', phone: '07725 516112', address: '79 Groomsport Rd, Bangor BT20 5ND, UK' },
  { slug: 'the-lash-studio', name: 'THE LASH STUDIO', category: 'mobile beauty therapist', phone: '07934 994453', address: 'Unit 3, 114 High St, Holywood BT18 9HW, UK' },
  { slug: 'holywoof-grooming', name: 'Holywoof Grooming', category: 'dog groomer', phone: '07712 580853', address: '23 Firmount Cres, Holywood BT18 9QN, UK' },
  { slug: 'eclipse', name: 'Eclipse', category: 'event photographer', phone: '07850 045995', address: '28 Croft Rd, Holywood BT18 0PB, UK' },
  { slug: 'craigavad-garden-services', name: 'Craigavad Garden Services', category: 'gardening service', phone: '07719 553750', address: '72a Ballymoney Rd, Holywood BT18 0JJ, UK' },
  { slug: 'jl-gardening-services', name: 'Jl Gardening Services', category: 'gardening service', phone: '07872 390975', address: '83 Abbey Ring, Holywood BT18 9NU, UK' },
  { slug: 'mark-morrison-tiling', name: 'Mark Morrison Tiling', category: 'tiling contractor', phone: '07803 897789', address: '2 Whiteways, Mountain Rd, Newtownards BT23 4UW, UK' },
  { slug: 'shane-hamill-piano', name: 'Shane Hamill Piano', category: 'music teacher', phone: '07476 970196', address: '26 Bangor Rd, Holywood BT18 0LQ, UK' },
  { slug: 'paws-woofs-hoofs', name: 'Paws Woofs Hoofs', category: 'pet sitting', phone: '07840 829897', address: '5 Fir Dr, Newtownards BT23 4HH, UK' },
  { slug: 'sp-gardening-and-landscaping-services-newtownards-bangor-north-down-belfast', name: 'SP Gardening and landscaping Services -Newtownards/Bangor/North Down / Belfast', category: 'gardening service', phone: '07739 897991', address: '171 Scrabo Rd, Newtownards BT23 4SJ, UK' },
  { slug: 'mcgrogan-tiler', name: 'McGrogan Tiler', category: 'tiling contractor', phone: '07815 061771', address: '26 Cornmill Avenue, Millisle, Newtownards BT22 2GN, UK' },
  { slug: 'tullycross-tiling', name: 'Tullycross Tiling', category: 'tiling contractor', phone: '07719 939164', address: '3 Tullycross Rd, Ardkeen, Newtownards BT22 1JJ, UK' },
  { slug: 'dream-clean-ni', name: 'Dream Clean NI', category: 'cleaning service', phone: '07518 524250', address: '32 Mill St Ct, Newtownards BT23 4JE, UK' },
  { slug: 'little-rainbows-playgroup', name: 'Little Rainbows Playgroup', category: 'babysitting service', phone: '07854 268145', address: '87 Movilla Rd, Newtownards BT23 8RQ, UK' },
  { slug: 'esther-moore-piano-lessons', name: 'Esther Moore Piano Lessons', category: 'music teacher', phone: '07724 033859', address: '25 Lisbarnet Rd, Lisbane, Comber, Newtownards BT23 6AW, UK' },
  { slug: 'c-l-f-school-of-motoring', name: 'C L F School of Motoring', category: 'driving instructor', phone: '07912 363581', address: '15 Tara Cres, Newtownards BT23 7DF, UK' },
  { slug: 'chris-the-barber', name: 'Chris The Barber', category: 'mobile barber', phone: '07517 320068', address: '29 Kilmore Cl, Belfast BT13 2TE, UK' },
  { slug: 'car-wash-mobile', name: 'CAR WASH (Mobile)', category: 'mobile car wash', phone: '07708 580460', address: '36 Killynure Grn, Carryduff, Belfast BT8 8FA, UK' },
  { slug: 'pm-tiling', name: 'PM Tiling', category: 'tiling contractor', phone: '07985 108484', address: '83 Bracken Prk, Londonderry BT48 8AZ, UK' },
  { slug: 'registered-childminder', name: 'Registered childminder', category: 'chilminder', phone: '07518 366095', address: '58 Severn St, Belfast BT4 1FB, UK' },
  { slug: 'angela-s-angels', name: 'Angela’s Angels', category: 'chilminder', phone: '07592 199887', address: '9 Greenane Cres, Belfast BT10 0NY, UK' },
  { slug: 'twinkle-star-daycare', name: 'twinkle star daycare', category: 'chilminder', phone: '07710 258861', address: 'Mayfield Square, Belfast BT10 0QR, UK' },
  { slug: 'newborn-night-nanny', name: 'Newborn Night Nanny', category: 'babysitting service', phone: '07769 584897', address: '176 Ballyclare Rd, County, Glengormley, Antrim BT36 5JR, UK' },
  { slug: 'mobile-man-cuts', name: 'Mobile Man Cuts', category: 'mobile barber', phone: '07514 729887', address: '11 Beaufort Dr, Londonderry BT47 6FG, UK' },
  { slug: 'relax-recharge-holistic-massage-therapy-belfast', name: 'Relax & Recharge Holistic Massage Therapy Belfast', category: 'mobile massage therapist', phone: '07743 304158', address: '330 Beersbridge Rd, Belfast BT5 5DY, UK' },
  { slug: 'total-floor-care-ni-tile-grout-cleaning-belfast', name: 'Total Floor Care NI - Tile & Grout Cleaning Belfast', category: 'tiling contractor', phone: '07933 650590', address: '39 Lansdowne Rd, Belfast BT15 4AA, UK' },
  { slug: 'ss-tiling', name: 'SS Tiling', category: 'tiling contractor', phone: '07513 828485', address: '36 Crimea St, Belfast BT13 1LT, UK' },
  { slug: 'emma-s-childminding', name: 'Emma’s Childminding', category: 'chilminder', phone: '07510 074323', address: '44 Church Rd, Rasharkin, Ballymena BT44 8QY, UK' },
  { slug: 'wild-ones-childminding-castlecaulfield', name: 'Wild Ones Childminding- Castlecaulfield', category: 'chilminder', phone: '07415 370627', address: '49 Foygh Rd, Dungannon BT70 3DH, UK' },
  { slug: 'jd-garden-services-ni', name: 'JD Garden Services NI', category: 'gardening service', phone: '07591 124249', address: '33 Dhu Varren Parade, Belfast BT13 3FJ, UK' },
  { slug: 'best-paws-forward', name: 'Best Paws Forward', category: 'pet sitting', phone: '07511 472720', address: 'Avonmore Park, Lisburn BT28 1NE, UK' },
  { slug: 'ryan-quinn-fitness', name: 'Ryan Quinn Fitness', category: 'personal trainer', phone: '07956 871482', address: '17 Altona Rd, Lisburn BT27 5QB, UK' },
  { slug: 'pmg-detailing', name: 'PMG detailing', category: 'car detailing', phone: '07724 277676', address: '10 Barbour Ct, Lisburn BT27 5DR, UK' },
  { slug: 'cedarwood-garden-services', name: 'Cedarwood Garden Services', category: 'gardening service', phone: '07801 990865', address: '29a Pond Park Rd, Lisburn BT28 3LA, UK' },
  { slug: 'hilden-lawn-garden', name: 'Hilden Lawn & Garden', category: 'gardening service', phone: '07518 464061', address: '58 Delacherois Ave, Lisburn BT27 4UA, UK' },
  { slug: 'cjs-cleaning-service-ltd', name: 'CJS CLEANING SERVICE LTD', category: 'cleaning service', phone: '07934 710119', address: '21 Molyneaux Dr, Lisburn BT28 2LY, UK' },
  { slug: 'singing-lessons-with-pauline-carville', name: 'SINGING LESSONS with Pauline Carville', category: 'music teacher', phone: '07881 803662', address: '28 Lisburn Square, Lisburn BT28 1TS, UK' },
  { slug: 'grooveworks-drum-school', name: 'GrooveWorks Drum School', category: 'music teacher', phone: '07515 469273', address: 'Enterprise Cres, Lisburn BT28 2BP, UK' },
  { slug: 'ali-s-mobile-hairdressing', name: 'Ali\'s mobile Hairdressing', category: 'mobile hairdresser', phone: '07894 252716', address: '4 Main Street, Desertmartin, Magherafelt BT45 5LN, UK' },
  { slug: 'milesian-fat-loss-coaching', name: 'Milesian Fat Loss Coaching', category: 'personal trainer', phone: '07799 287951', address: 'Pure Gym, Toscana Retail Park, Bangor BT19 1FH, UK' },
  { slug: 'c-m-valenting-detailing', name: 'C.M valenting & Detailing', category: 'mobile valeting', phone: '07716 909169', address: '19 Killaire Wood Ln, Bangor BT19 1ZY, UK' },
  { slug: 'stephen-reid-quality-painting-decorating', name: 'Stephen Reid Quality Painting & Decorating', category: 'painter decorator', phone: '07790 993773', address: '14 Lord Warden\'s Hollow, Bangor BT19 1GP, UK' },
  { slug: 'dynamic-decorators-ni', name: 'Dynamic Decorators NI', category: 'painter decorator', phone: '07706 719164', address: '8 Ambleside Rd, Bangor BT20 4QA, UK' },
  { slug: 'sparkle-cleaning-services', name: 'Sparkle cleaning services', category: 'domestic cleaning', phone: '07580 638705', address: '8 Fern Grove, Rathgael Rd, Bangor BT19 1FG, UK' },
  { slug: 'grooms-by-meg', name: 'grooms by meg', category: 'dog groomer', phone: '07940 067661', address: '102 Ballyregan Rd, Holywood BT18 9RP, UK' },
  { slug: 'dog-walking-pet-sitting-holywood', name: 'Dog Walking & Pet Sitting Holywood', category: 'pet sitting', phone: '07456 312375', address: '18 Wood End, Holywood BT18 9PN, UK' },
  { slug: 'bayburn-fitness', name: 'Bayburn Fitness', category: 'personal trainer', phone: '07793 470324', address: '114 High St, Holywood BT18 9HW, UK' },
  { slug: 'apex-mobile-valets', name: 'APEX MOBILE VALETS', category: 'mobile car wash', phone: '07799 022957', address: 'Ferndale Rd, Glengormley, Newtownabbey BT36 5AD, UK' },
  { slug: 'rice-autos', name: 'Rice autos', category: 'mobile mechanic', phone: '07860 643974', address: '13 Cooke St, Belfast BT7 2EP, UK' },
  { slug: 'kelly-s-kidz', name: 'kelly\'s Kidz', category: 'chilminder', phone: '07703 624879', address: '61 Cronstown Cottage Park, Newtownards BT23 8QP, UK' },
  { slug: 'holywood-play-company', name: 'Holywood Play Company', category: 'babysitting service', phone: '07837 598691', address: '22-30 Ean Hill, Holywood BT18 9LQ, UK' },
  { slug: 'mad-pups-dog-grooming', name: 'Mad Pups Dog Grooming', category: 'dog groomer', phone: '07365 658385', address: 'Glenford Rd, Newtownards BT23 4AX, UK' },
  { slug: 'tracey-ayre-dog-grooming', name: 'Tracey Ayre Dog Grooming', category: 'dog groomer', phone: '07874 012515', address: 'Tern Park, Newtownards BT23 8FP, UK' },
  { slug: 'fluffology-dog-grooming', name: 'Fluffology Dog Grooming', category: 'dog groomer', phone: '07872 328501', address: '3 Jubilee Rd, Newtownards BT23 4YH, UK' },
  { slug: 'paws-to-go', name: 'Paws...To Go...', category: 'pet sitting', phone: '07713 804136', address: 'Old Shore Rd, Newtownards BT23 8NE, UK' },
  { slug: 'limitless-fitness-ni', name: 'Limitless fitness ni', category: 'personal trainer', phone: '07494 862439', address: 'Benford Dr, Newtownards BT23 8TH, UK' },
  { slug: 'peak-detailing', name: 'Peak Detailing', category: 'car detailing', phone: '07515 967375', address: '76, Newtownards BT23 4UL, UK' },
  { slug: 'refleq-detailing', name: 'Refleq Detailing', category: 'car detailing', phone: '07401 999757', address: '43 Bridgelea Ave, Bangor, Newtownards BT23 7HX, UK' },
  { slug: 'a1-elite-mobile-detailing', name: 'A1 Elite Mobile Detailing', category: 'mobile valeting', phone: '07519 777499', address: 'Bridgelea Ct, Bangor, Newtownards BT22 7HW, UK' },
  { slug: 'stephen-mcburney-painting-and-decorating', name: 'Stephen McBurney Painting and Decorating', category: 'painter decorator', phone: '07545 349490', address: '3 Dermott Rd, Comber, Newtownards BT23 5LG, UK' },
  { slug: 'ng-shaw-paint-spraying-services', name: 'NG Shaw Paint Spraying Services', category: 'painter decorator', phone: '07789 755888', address: '19 Court St, Newtownards BT23 7NX, UK' },
  { slug: 'newtownards-bangor-child-contact-centres', name: 'Newtownards & Bangor Child Contact Centres', category: 'babysitting service', phone: '07540 143700', address: 'Strean Presbyterian Church, Newtownards BT23 4EN, UK' },
];
