export interface Business {
  slug: string;
  name: string;
  category: string;
  phone: string;
  address: string;
}

export const businesses: Business[] = [
  { slug: 'p-lynch-plumbing-heating', name: 'P lynch Plumbing & heating', category: 'plumber', phone: '07790 864092', address: '193 Hatmore Park, Londonderry BT48 0AF, UK' },
  { slug: 'dm-gas-plumbing-heating', name: 'DM Gas - plumbing - heating', category: 'plumber', phone: '07514 734229', address: '367 Carnhill, Londonderry BT48 8BS, UK' },
  { slug: 'the-shower-doctor', name: 'The Shower Doctor', category: 'plumber', phone: '07845 587908', address: '21 Ardlough Rd, Londonderry BT47 5SW, UK' },
  { slug: 'gmc-plumbing-and-heating-ltd', name: 'GMC plumbing and heating ltd', category: 'plumber', phone: '07989 350136', address: '8 Lyndhurst Rd, Londonderry BT47 5HS, UK' },
  { slug: 'all-emergency-plumbing', name: 'all emergency plumbing', category: 'plumber', phone: '07955 050100', address: '28 Prehen Park, Londonderry BT47 2NY, UK' },
  { slug: 'p-t-s-plumbing-trade-supplies', name: 'P T S Plumbing Trade Supplies', category: 'plumber', phone: '028 7130 6000', address: '40 Springtown Rd, Londonderry BT48 0LY, UK' },
  { slug: 'clearflow', name: 'Clearflow', category: 'plumber', phone: '07845 877493', address: '80 Strabane Old Rd, Londonderry BT47 2EG, UK' },
  { slug: 'tj-mcconnell-and-sons', name: 'TJ McConnell and Sons', category: 'plumber', phone: '028 7136 3539', address: '32 Balliniska Rd, Londonderry BT48 0NA, UK' },
  { slug: 'mcquaid-electrical', name: 'Mcquaid Electrical', category: 'electrician', phone: '07388 877368', address: '269 Carnhill, Londonderry BT48 8BL, UK' },
  { slug: 'derry-auto-electrics', name: 'Derry Auto Electrics', category: 'electrician', phone: '028 7126 1100', address: '102 Duncreggan Rd, Londonderry BT48 0AA, UK' },
  { slug: 'horton-electrical-services-ltd', name: 'Horton Electrical Services Ltd', category: 'electrician', phone: '028 7130 8858', address: '1 Bay Road Business Park, Londonderry BT48 7SH, UK' },
  { slug: 'curran-hepburn', name: 'Curran & Hepburn', category: 'electrician', phone: '07712 110048', address: '87 Spencer Rd, Londonderry BT47 6AE, UK' },
  { slug: 'ks-electrical-services-ltd', name: 'KS Electrical Services Ltd', category: 'electrician', phone: '028 7128 6777', address: 'Business Park, Unit 7 Bay Rd, Londonderry BT48 7SE, UK' },
  { slug: 'harrison-electrical', name: 'Harrison Electrical', category: 'electrician', phone: '028 7134 2539', address: '78 Duke St, Londonderry BT47 6DQ, UK' },
  { slug: 'nor-den-electrical', name: 'Nor-Den Electrical', category: 'electrician', phone: '028 7137 7210', address: '3 Springtown Rd, Londonderry BT48 0LY, UK' },
  { slug: 'brett-electrical', name: 'Brett Electrical', category: 'electrician', phone: '07706 820839', address: '65 Ivy Mead, Altnagelvin, Londonderry BT47 3WW, UK' },
  { slug: 'derry-electrics', name: 'Derry Electrics', category: 'electrician', phone: '07923 806636', address: '50 Elaghmore Prk, Londonderry BT48 8DX, UK' },
  { slug: 'dl-electrical-services', name: 'DL Electrical Services', category: 'electrician', phone: '07368 409085', address: 'Beechwood Ave, Londonderry BT48 9LR, UK' },
  { slug: 'crumley-patrick', name: 'Crumley Patrick', category: 'electrician', phone: '028 7131 2939', address: '18b Riverview Terrace, Londonderry BT47 2BL, UK' },
  { slug: 'strand-electrics', name: 'Strand Electrics', category: 'electrician', phone: '028 7126 5012', address: 'Unit 19F Pennyburn Industrial Estate, Londonderry BT48 0LU, UK' },
  { slug: 'pjm-power-electrical-contractor', name: 'PJM Power Electrical Contractor', category: 'electrician', phone: '07521 052569', address: 'Ard Grange, Londonderry BT48 0SF, UK' },
  { slug: 'mccauley-auto-electrics', name: 'McCauley Auto Electrics', category: 'electrician', phone: '028 7135 1972', address: '64 Coney Rd, Londonderry BT48 8JP, UK' },
  { slug: 'city-electrics-ireland-ltd', name: 'City Electrics Ireland Ltd', category: 'electrician', phone: '028 7135 3147', address: '19 Sandbank Cottages, Londonderry BT48 8LL, UK' },
  { slug: 'city-roofing-ltd', name: 'City Roofing Ltd', category: 'roofer', phone: '028 7126 9648', address: '3 Pennyburn Industrial Estate, Londonderry BT48 0LU, UK' },
  { slug: 'dgs-roofing-services', name: 'Dgs roofing services', category: 'roofer', phone: '07928 033186', address: '67 Coney Rd, Londonderry BT48 8JN, UK' },
  { slug: 'h-carlin-decorators', name: 'H Carlin Decorators', category: 'painter', phone: '028 7135 4489', address: '1 Griffith Park, Londonderry BT48 8PE, UK' },
  { slug: 'prime-decor', name: 'Prime Decor', category: 'painter', phone: '', address: '7 Abbots Walk, Londonderry BT48 9HA, UK' },
  { slug: 'seamusmcclafferty', name: 'Seamusmcclafferty', category: 'painter', phone: '07706 033987', address: '7 Ballymore Park, Londonderry BT48 9BP, UK' },
  { slug: 'city-paints-wallpapers', name: 'City Paints & Wallpapers', category: 'painter', phone: '028 7128 0088', address: '5/6 Springtown Business Park, Londonderry BT48 0GY, UK' },
  { slug: 'bell-p-j', name: 'Bell P J', category: 'painter', phone: '028 7135 1639', address: '2 Clonliffe Park, Londonderry BT48 8NT, UK' },
  { slug: 'mccann-decor-ltd', name: 'McCann Decor Ltd', category: 'painter', phone: '028 7135 2243', address: '59 Templeard, Ballynagard, Londonderry BT48 8FE, UK' },
  { slug: 'ruairi-o-hara-painting-decorating', name: 'Ruairi O\'Hara Painting & Decorating', category: 'painter', phone: '07821 770842', address: '30 Columbia Park, Londonderry BT47 4PD, UK' },
  { slug: 'ray-mallett-painting-decorating', name: 'Ray Mallett Painting & Decorating', category: 'painter', phone: '07925 771154', address: '437 Carnhill, Londonderry BT48 8BT, UK' },
  { slug: 'bmr-decorators', name: 'BMR DECORATORS', category: 'painter', phone: '07873 445963', address: '157 Gortin Manor, Newbuildings, Londonderry BT47 2TT, UK' },
  { slug: 'ec-painters-decorators', name: 'Ec painters & decorators', category: 'painter', phone: '07873 673801', address: '30E McLean Rd, Campsie, Londonderry BT47 3XX, UK' },
  { slug: 'derry-tiler', name: 'Derry Tiler', category: 'tiler', phone: '028 7137 3386', address: '24 Four Seasons, Foyle Road, Londonderry, Derry BT48 6AX, UK' },
  { slug: 'dmc-premier-tiling', name: 'DMC Premier Tiling', category: 'tiler', phone: '07738 003899', address: '55 Lincoln Ct, Waterside, Londonderry BT47 5NT, UK' },
  { slug: 'rjb-joinery', name: 'RJB JOINERY', category: 'joiner', phone: '07591 887868', address: 'Unit A1, Ballinska Business Park, Springtown Industrial Estate, Londonderry BT48 0LY, UK' },
  { slug: 'concept-carpentry-joinery', name: 'Concept Carpentry &Joinery', category: 'joiner', phone: '07903 152202', address: '563 Carnhill, Londonderry BT48 8BZ, UK' },
  { slug: 'aok-joinery', name: 'AOK Joinery', category: 'joiner', phone: '07825 517616', address: '51 Foxhill, The Bolies, Londonderry BT47 2TN, UK' },
  { slug: 'aj-joinery', name: 'Aj joinery', category: 'joiner', phone: '', address: '82 Duncreggan Rd, Londonderry BT48 0AA, UK' },
  { slug: 'ad-joinery', name: 'Ad Joinery', category: 'joiner', phone: '', address: '14 Ardanlee, Ballynagard, Londonderry BT48 8RR, UK' },
  { slug: 'joinery-workshop-services-ltd', name: 'Joinery Workshop Services Ltd', category: 'joiner', phone: '07951 068053', address: 'Site 30, Springtown Industrial Estate, Unit F Springrowth Rd, Londonderry BT48 0LY, UK' },
  { slug: 'darek-furniture', name: 'Darek furniture', category: 'joiner', phone: '07873 529748', address: '34 Ervey Ct, Londonderry BT47 3WN, UK' },
  { slug: 'a-l-c-joinery', name: 'A L C Joinery', category: 'joiner', phone: '028 7134 1386', address: '59 Sevenoaks, Londonderry BT47 6BD, UK' },
  { slug: 'maybrooke-renovations-and-extensions', name: 'maybrooke renovations and extensions', category: 'joiner', phone: '07387 882775', address: '28 Petrie Way, Londonderry BT47 3XX, UK' },
  { slug: 'pavier-joinery', name: 'Pavier Joinery', category: 'joiner', phone: '07818 866690', address: 'Belvoir Park, Londonderry BT48 8PQ, UK' },
  { slug: 'kara-construction', name: 'KARA CONSTRUCTION', category: 'joiner', phone: '07597 752723', address: '85 Monnaboy Rd, Londonderry BT47 3HP, UK' },
  { slug: 'north-west-joinery-ltd', name: 'North West Joinery Ltd', category: 'joiner', phone: '028 7135 5555', address: '5 Steelstown Rd, Londonderry BT48 8EU, UK' },
  { slug: 'derry-garden-services', name: 'Derry Garden Services', category: 'landscaper', phone: '07523 612005', address: 'Londonderry BT47 6BB, UK' },
  { slug: 'plant-a-seed-landscapes', name: 'Plant A Seed Landscapes', category: 'landscaper', phone: '07746 229281', address: '51a Cromore Gardens, Londonderry BT48 9TG, UK' },
  { slug: 'falcon-landscape-building-services', name: 'Falcon landscape building services', category: 'landscaper', phone: '', address: 'Castle View Park, Londonderry BT48 8DL, UK' },
  { slug: 'north-wesrt-garden-experts', name: 'North Wesrt Garden Experts', category: 'landscaper', phone: '028 7135 8828', address: '47 Papworth Ave, Londonderry BT48 8PT, UK' },
  { slug: 'donohoe-t', name: 'Donohoe T', category: 'builder', phone: '028 7126 7244', address: '19-21 Chamberlain St, Londonderry BT48 6LR, UK' },
  { slug: 'doherty-e-sons', name: 'Doherty E & Sons', category: 'builder', phone: '028 7135 1655', address: '6 Fir Rd, Londonderry BT48 8NB, UK' },
  { slug: 'nicor-construction', name: 'Nicor Construction', category: 'builder', phone: '028 7188 0888', address: 'Unit 11, Bay Road Industrial Park, Bay Rd, Londonderry BT48 7SE, UK' },
  { slug: 'lynch-builders', name: 'Lynch Builders', category: 'builder', phone: '028 7181 1385', address: '38 Coolagh Rd, Londonderry BT47 3EQ, UK' },
  { slug: 'jfc-construction-ltd', name: 'JFC Construction Ltd', category: 'builder', phone: '028 7181 1477', address: '8e Courtauld Way, Campsie, Londonderry BT47 3XX, UK' },
  { slug: 'meraki-hairdressing', name: 'Meraki Hairdressing', category: 'hairdresser', phone: '028 7128 2386', address: '28 Carlisle Rd, Londonderry BT48 6JW, UK' },
  { slug: 'marie-gillespie-hair-beauty-studio', name: 'Marie Gillespie Hair & Beauty Studio', category: 'hairdresser', phone: '028 7134 4284', address: 'Unit 1 Woodburn Shopping Centre, 1, Waterside, Londonderry BT47 5PS, UK' },
  { slug: 'salon-sixteen', name: 'Salon Sixteen', category: 'hairdresser', phone: '028 7131 2504', address: '16 Clooney Terrace, Londonderry BT47 6AR, UK' },
  { slug: 'salon-one-hairdressing', name: 'Salon One hairdressing', category: 'hairdresser', phone: '028 7126 2781', address: '17 The, Craft Village, Shipquay St, Londonderry BT48 6AR, UK' },
  { slug: 'whispers-hairdressing-salon', name: 'Whispers Hairdressing Salon', category: 'hairdresser', phone: '028 7126 0595', address: '16 The Diamond, Londonderry BT48 6HW, UK' },
  { slug: 'streaks-ahead', name: 'Streaks Ahead', category: 'hairdresser', phone: '028 7128 8222', address: '21 William St, Londonderry BT48 6EP, UK' },
  { slug: 'sage-hair-beauty', name: 'Sage Hair & Beauty', category: 'hairdresser', phone: '07596 590617', address: '98 Spencer Rd, Londonderry BT47 6AG, UK' },
  { slug: 'headz-co', name: 'Headz & Co', category: 'hairdresser', phone: '028 7134 8665', address: '15 Glendermott Rd, Londonderry BT47 6BB, UK' },
  { slug: 'michael-deery-hair', name: 'Michael Deery Hair', category: 'hairdresser', phone: '07498 688989', address: '6 Castle St, Londonderry BT48 6HQ, UK' },
  { slug: 'mavericks-hair-extensions-beauty', name: 'Mavericks Hair Extensions & Beauty', category: 'hairdresser', phone: '028 7116 3266', address: 'Room 1, Unit 18, Northside Village Centre, Glengalliagh Rd, Londonderry BT48 8NN, UK' },
  { slug: 'essential-hair-company', name: 'Essential Hair Company', category: 'hairdresser', phone: '028 7126 2427', address: '8-10 Great James St, Londonderry BT48 7DB, UK' },
  { slug: 'brooke-hairdressing', name: 'Brooke Hairdressing', category: 'hairdresser', phone: '028 7126 0003', address: '8 Castle St, Londonderry BT48 6HQ, UK' },
  { slug: 'gemini-hair-studio', name: 'Gemini Hair Studio', category: 'hairdresser', phone: '028 7127 1122', address: '53 Carlisle Rd, Londonderry BT48 6JL, UK' },
  { slug: 'michael-tomasz-hairdressing', name: 'Michael Tomasz Hairdressing', category: 'hairdresser', phone: '028 7126 8172', address: 'Unit 3, Rock Mills, 126 Strand Rd, Londonderry BT48 7AD, UK' },
  { slug: 'lux-hair-beauty-studio', name: 'LUX Hair & Beauty Studio', category: 'hairdresser', phone: '07710 797261', address: '143 Bishop St, Londonderry BT48 6UJ, UK' },
  { slug: 'crumlish-house-of-luxury-hair-extensions-makeup-artistry', name: 'Crumlish House Of Luxury Hair Extensions & Makeup Artistry', category: 'hairdresser', phone: '', address: 'Pump St, Londonderry BT48 6JG, UK' },
  { slug: 'sammy-s-barbershop', name: 'Sammy\'s Barbershop', category: 'barber', phone: '07577 053073', address: '45 Great James St, Londonderry BT48 7DF, UK' },
  { slug: 'traditional-turkish-barber', name: 'Traditional Turkish Barber', category: 'barber', phone: '07857 997747', address: '152 Spencer Rd, Londonderry BT47 6AH, UK' },
  { slug: 'city-turkish-barbers-derry', name: 'City Turkish Barbers Derry', category: 'barber', phone: '', address: '25 The Diamond, Londonderry BT48 6HP, UK' },
  { slug: 'district-47-barbering-company', name: 'District 47 Barbering Company', category: 'barber', phone: '07845 009876', address: '47 Carlisle Rd, Co, Londonderry BT48 6JJ, UK' },
  { slug: 'the-barber-shop', name: 'The Barber Shop', category: 'barber', phone: '07544 194746', address: '82 Spencer Rd, Londonderry BT47 6AA, UK' },
  { slug: 'bareknuckle-barbershop', name: 'Bareknuckle Barbershop', category: 'barber', phone: '07803 842600', address: '173 Spencer Rd, Londonderry BT47 6AH, UK' },
  { slug: 'bt48-barbering-for-men', name: 'Bt48 barbering for men', category: 'barber', phone: '07517 698045', address: '16 Carlisle Rd, Londonderry BT48 6JN, UK' },
  { slug: 'summerland-stores', name: 'SUMMERLAND STORES', category: 'barber', phone: '07447 821727', address: '13-15 Foyle St, Londonderry BT48 6AL, UK' },
  { slug: 'the-waterloo-barber', name: 'The Waterloo Barber', category: 'barber', phone: '028 7126 4749', address: '44 Waterloo St, Londonderry BT48 6HF, UK' },
  { slug: 'roisin-s-barbers', name: 'Roisin\'s Barbers', category: 'barber', phone: '', address: '96 Bishop St, Londonderry BT48 6PP, UK' },
  { slug: 'busters-barber-shop', name: 'Busters Barber Shop', category: 'barber', phone: '07594 749796', address: '21A Waterloo St, Londonderry BT48 6HA, UK' },
  { slug: 'man-cave-barber-shop', name: 'Man Cave Barber Shop', category: 'barber', phone: '028 7136 7770', address: 'Whitehouse Retail, 65 Buncrana Rd, Londonderry BT48 8LB, UK' },
  { slug: 'city-barbers', name: 'City barbers', category: 'barber', phone: '07500 357463', address: '9 Great James St, Londonderry BT48 7BZ, UK' },
  { slug: 'jake-co', name: 'Jake&Co', category: 'barber', phone: '028 7116 3694', address: '4 Messines Terrace, The Collon, Londonderry BT48 7QZ, UK' },
  { slug: 'breidges-barbers', name: 'Breidges Barbers', category: 'barber', phone: '028 7137 2030', address: '47 Strand Rd, Londonderry BT48 7BN, UK' },
  { slug: 'choppers-barbers', name: 'Choppers Barbers', category: 'barber', phone: '028 7130 9400', address: '74 Bishop St, Londonderry BT48 6QE, UK' },
  { slug: 'diamond-brow-bar', name: 'Diamond Brow Bar', category: 'beauty salon', phone: '07751 099410', address: '4 Shipquay St, Londonderry BT48 6DN, UK' },
  { slug: 'code', name: 'CODE', category: 'beauty salon', phone: '', address: '10/11, Craft Village, Londonderry BT48 6AR, UK' },
  { slug: 'professionail-beauty-salon', name: 'ProfessioNail Beauty Salon', category: 'beauty salon', phone: '07856 000020', address: '88 Spencer Rd, Waterside, Londonderry BT47 6AG, UK' },
  { slug: 'zolero', name: 'Zolero', category: 'beauty salon', phone: '028 7137 0279', address: '145 Bishop St, Londonderry BT48 6UJ, UK' },
  { slug: 'beauty-unlimited', name: 'Beauty Unlimited', category: 'beauty salon', phone: '028 7137 2117', address: '22a Great James St, Londonderry BT48 7DA, UK' },
  { slug: 'michelle-s-beauty-clinic-and-training-academy', name: 'Michelle’s Beauty Clinic and Training Academy', category: 'beauty salon', phone: '07598 567984', address: '26 Spencer Rd, Londonderry BT47 6AA, UK' },
  { slug: 'miabella-beauty-bar', name: 'Miabella beauty bar', category: 'beauty salon', phone: '07895 490560', address: '88 Racecourse Rd, Londonderry BT48 8DS, UK' },
  { slug: 'la-bella-salon', name: 'La Bella Salon', category: 'beauty salon', phone: '028 7131 1522', address: '51 Spencer Rd, Londonderry BT47 6AA, UK' },
  { slug: 'notorious-street-food', name: 'Notorious Street Food', category: 'takeaway', phone: '', address: 'Northside Village Centre, Glengalliagh Rd, Londonderry BT48 8NN, UK' },
  { slug: 'kebab-house', name: 'Kebab House', category: 'takeaway', phone: '028 7137 4500', address: '42 Shipquay St, Londonderry BT48 6DW, UK' },
  { slug: 'chicken-plaza', name: 'Chicken Plaza', category: 'takeaway', phone: '028 7141 3326', address: '27 Foyle St, Londonderry BT48 6AL, UK' },
  { slug: 'bc-auto-repair', name: 'BC Auto Repair', category: 'mechanic', phone: '07783 849000', address: 'Unit 4 Springtown Dr, Londonderry BT48 0LY, UK' },
  { slug: 'dc-auto-repair-derry', name: 'DC Auto Repair Derry', category: 'mechanic', phone: '07544 061038', address: '19, Rathmore Business Park, Londonderry BT48 0LZ, UK' },
  { slug: 'cusack-s-garage', name: 'Cusack\'s Garage', category: 'mechanic', phone: '028 7126 9209', address: '4A Claremont St, Londonderry BT48 7NB, UK' },
  { slug: 'a1-mobile-mechanic-derry', name: 'A1 Mobile mechanic derry', category: 'mechanic', phone: '07487 664507', address: '36 Westland St, Londonderry BT48 9ET, UK' },
  { slug: 'g-mak-auto-service', name: 'G Mak Auto Service', category: 'mechanic', phone: '028 7126 5151', address: 'Iona Business Pk, Southway, Londonderry BT48 9AH, UK' },
  { slug: 'stewart-motors', name: 'Stewart Motors', category: 'mechanic', phone: '028 7126 7579', address: '43 Barry St, Londonderry BT48 7PJ, UK' },
  { slug: 'foyleside-garage', name: 'Foyleside Garage', category: 'mechanic', phone: '028 7134 9203', address: '2a York St, Londonderry BT47 6DX, UK' },
  { slug: 'northland-motors', name: 'Northland Motors', category: 'mechanic', phone: '028 7136 4141', address: 'Unit 2, Northland Road Industrial Estate, Londonderry BT48 0LD, UK' },
  { slug: 'wallace-auto-repairs', name: 'Wallace Auto-repairs', category: 'mechanic', phone: '028 7141 7382', address: '4 Ferguson St, Londonderry BT48 6TA, UK' },
  { slug: 'od-s-garage', name: 'Od-S Garage', category: 'mechanic', phone: '', address: 'Unit 12, B, Springtown Rd, Londonderry BT48 0LY, UK' },
  { slug: 'collon-cars', name: 'Collon Cars', category: 'mechanic', phone: '028 7126 2952', address: 'Unit 12,13,14, Northland Road Industrial Estate, Northland Rd, Londonderry BT48 0LD, UK' },
  { slug: 'wilson-s-autorepair', name: 'Wilson\'s Autorepair', category: 'mechanic', phone: '07488 260222', address: '2 Temple Park, Londonderry BT48 8PN, UK' },
  { slug: 'emc-autos-mobile-mechanic', name: 'Emc Autos Mobile Mechanic', category: 'mechanic', phone: '07871 717678', address: '80A Culmore Rd, Londonderry BT48 8JB, UK' },
  { slug: 'f-s-motors', name: 'F & S Motors', category: 'mechanic', phone: '028 7135 0565', address: '26 Lenamore Rd, Londonderry BT48 8NA, UK' },
  { slug: 'hasson-motors', name: 'Hasson Motors', category: 'mechanic', phone: '07751 322671', address: '27a Sheriffs Rd, Londonderry BT48 0JS, UK' },
  { slug: '20-laburnum-terrace', name: '20 laburnum terrace', category: 'mechanic', phone: '', address: '4 College Terrace, Londonderry BT48 7JG, UK' },
  { slug: 'the-garage', name: 'The Garage', category: 'mechanic', phone: '', address: '24 Queens Quay, Londonderry BT48 7AS, UK' },
  { slug: 'sho-vij-fitness-female-body-tone-coach-derry', name: 'Sho Vij Fitness Female Body Tone Coach Derry', category: 'personal trainer', phone: '07935 487075', address: 'Raw Fitness Derry Ltd, Pennyburn Industrial Estate, Londonderry BT47 0LU, UK' },
  { slug: 'raw-fitness-derry-ltd', name: 'Raw Fitness Derry Ltd', category: 'personal trainer', phone: '07703 326018', address: '5, Londonderry BT48 0LU, UK' },
  { slug: 'raise-the-bar-fitness-female-personal-training-derry', name: 'Raise The Bar Fitness Female Personal Training Derry', category: 'personal trainer', phone: '07856 890786', address: 'Raise The Bar Fitness Derry, Unit 5 Balliniska Rd, Springtown Dr, Londonderry BT48 0LY, UK' },
  { slug: 'xtreme-gym', name: 'Xtreme Gym', category: 'personal trainer', phone: '028 7134 5044', address: '2 Distillery Brae, Londonderry BT47 6AN, UK' },
  { slug: 'paul-kelly-personal-trainer-coach', name: 'Paul Kelly Personal Trainer/Coach', category: 'personal trainer', phone: '07716 093501', address: 'Unit 43, North West Business Complex Skeoge Industrial park, Londonderry BT48 8SE, UK' },
  { slug: 'transition-derry', name: 'Transition Derry', category: 'personal trainer', phone: '07843 956960', address: '5, Swilly House, Springtown Industrial Estate, Londonderry BT48 0LY, UK' },
  { slug: 'paul-mc-gowan-fitness-derry', name: 'Paul Mc Gowan Fitness Derry', category: 'personal trainer', phone: '085 775 9877', address: 'Unit 1 & 2, Springtown Industrial Estate, Springrowth Rd, Londonderry BT48 0LY, UK' },
  { slug: 'strive-performance-center-limited', name: 'Strive Performance Center limited', category: 'personal trainer', phone: '07564 477858', address: 'Unit 8 Elagh Business Pk, Coshquin, Londonderry BT48 8QP, UK' },
  { slug: 'elite-cleaning-services', name: 'Elite Cleaning Services', category: 'cleaner', phone: '07756 059298', address: '45 Ashburn Ave, Londonderry BT47 5QE, UK' },
  { slug: 'cleanlyy', name: 'Cleanlyy', category: 'cleaner', phone: '028 7178 2153', address: 'Rhodemore Ltd, The Innovation Centre, Bay Rd, Londonderry BT48 7TG, UK' },
  { slug: 'oven-cleaning-muckers', name: 'Oven Cleaning Muckers', category: 'cleaner', phone: '028 7100 0028', address: '103 Westlake Enagh, 103 Westlake, Strathfoyle, Londonderry BT47 6WE, UK' },
  { slug: 'xtreme-cleaning-services-ni', name: 'Xtreme Cleaning Services ni', category: 'cleaner', phone: '07517 003144', address: 'Creggan St, Londonderry BT48 0EU, UK' },
  { slug: 'speedy-clean', name: 'Speedy Clean', category: 'cleaner', phone: '028 7134 7822', address: '5 Blackburn Cres, Londonderry BT47 5QG, UK' },
  { slug: 'bark-n-baths', name: 'Bark N Baths', category: 'dog groomer', phone: '07719 579277', address: 'Unit 6, Swilly House, Springtown Rd, Londonderry BT48 0GH, UK' },
  { slug: 'igroom-dog-grooming-by-lisa-curran-springtown', name: 'IGROOM DOG GROOMING BY LISA CURRAN SPRINGTOWN', category: 'dog groomer', phone: '07749 457323', address: 'Balliniska Rd, Springtown Rd, Londonderry BT48 0NA, UK' },
  { slug: 'canine-barber-company', name: 'CANINE BARBER COMPANY', category: 'dog groomer', phone: '', address: '66 Strand Rd, Londonderry BT48 7PX, UK' },
  { slug: 'the-dog-parlour', name: 'The Dog Parlour', category: 'dog groomer', phone: '07724 330117', address: 'Ráth mór centre Bligh\'s lane, Londonderry BT48 0LZ, UK' },
  { slug: 'blissful-brush-dog-grooming', name: 'Blissful Brush Dog Grooming', category: 'dog groomer', phone: '07749 317864', address: '22 Rossdowney Dr, Londonderry BT47 5PR, UK' },
  { slug: 'trendy-paws-by-craig-jan', name: 'Trendy Paws By Craig Jan', category: 'dog groomer', phone: '07522 782066', address: '27 Grangewood Ct, Londonderry BT47 5WT, UK' },
  { slug: 'd-m-groomers', name: 'D&M GROOMERS', category: 'dog groomer', phone: '07927 443098', address: '53 Rosemount Ave, Londonderry BT48 0HL, UK' },
  { slug: 'catwalk-dogs-grooming-salon-doggie-daycare', name: 'Catwalk Dogs Grooming Salon & Doggie Daycare', category: 'dog groomer', phone: '', address: 'Racecourse Rd, Londonderry BT48 7UD, UK' },
  { slug: 'dapper-dogs-mobile-grooming', name: 'Dapper Dogs Mobile Grooming', category: 'dog groomer', phone: '07368 243039', address: 'Prehen Park, Derry BT47 2NY, UK' },
  { slug: 'groomin-marvelous', name: 'Groomin Marvelous', category: 'dog groomer', phone: '07855 808932', address: '4 North Meadows, Londonderry BT48 0QB, UK' },
  { slug: 'platinum-puppies', name: 'Platinum Puppies', category: 'dog groomer', phone: '07488 238101', address: '20 Rathlin Gardens, Londonderry BT48 9UE, UK' },
  { slug: 'best-buddies-groomers', name: 'Best Buddies Groomers', category: 'dog groomer', phone: '07821 072599', address: '8 Glasgow Terrace, Londonderry BT48 0DP, UK' },
  { slug: 'adorable-dogs', name: 'Adorable Dogs', category: 'dog groomer', phone: '07753 117195', address: '20 Maydown Rd, Strathfoyle, Londonderry BT47 6UJ, UK' },
  { slug: 'pampered-paws-k9', name: 'Pampered Paws K9', category: 'dog groomer', phone: '028 7131 3864', address: 'Unit 1, Ballyore Business Park, Victoria Rd, Newbuildings, Londonderry BT47 2TH, UK' },
  { slug: 'all-furr-dogs', name: 'ALL FURR DOGS', category: 'dog groomer', phone: '07779 028028', address: '1 Sheraton Park, Londonderry BT48 0AQ, UK' },
  { slug: 'the-handyman', name: 'The Handyman', category: 'handyman', phone: '028 7181 0941', address: '42 Woodvale Mews, Eglinton, Londonderry BT47 3FE, UK' },
  { slug: 'instant-property-maintenance-ltd', name: 'Instant Property Maintenance Ltd', category: 'handyman', phone: '028 7131 3325', address: '5 Columba Ter, Londonderry BT47 6JT, UK' },
  { slug: 'promastix-sealants', name: 'ProMastix Sealants', category: 'handyman', phone: '', address: '20c Balliniska Rd, Londonderry BT48 0NA, UK' },
  { slug: 'm-c-plastering', name: 'M C Plastering', category: 'plasterer', phone: '07709 614094', address: '4 Copperfield Dr, Londonderry BT47 5DG, UK' },
  { slug: 'kc-locksmiths', name: 'KC Locksmiths', category: 'locksmith', phone: '07528 758157', address: '11 Maybrook Park, Londonderry BT48 7TP, UK' },
];
