developer_token: "GkByzoE5295UNH5bMVfiow"
client_id: "815883685833-tpjtme1mpjlgeq9os4vt1hbqhtoqucmf.apps.googleusercontent.com"
client_secret: "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"
refresh_token: "1//038hb8qUl_HryCgYIARAAGAMSNwF-L9IrSRmvogjWhfZddt2WW4AXN3CC2HE-KAEFp7rhaxsD1gmwnSw2FpNHqcuMAMKjjUt-xUc"
login_customer_id: "3963786948"
use_proto_plus: True