export interface Company {
  slug: string;
  name: string;
  website: string;
}

export const companies: Company[] = [
  { slug: 'ae-global', name: 'AE Global', website: 'https://aeglobal.uk' },
  { slug: 'accelercomm-ltd', name: 'AccelerComm Ltd', website: 'https://accelercomm.com' },
  { slug: 'access-elemental-social-prescribing', name: 'Access Elemental Social Prescribing', website: 'https://elementalsoftware.co' },
  { slug: 'action-sustainability', name: 'Action Sustainability', website: 'https://actionsustainability.com' },
  { slug: 'aeronadental-software', name: 'AeronaDental Software', website: 'https://aerona.com' },
  { slug: 'albida', name: 'Albida', website: 'https://albida.com' },
  { slug: 'alpnet-solutions-limited', name: 'AlpNet Solutions Limited', website: 'https://taskvision.co.uk' },
  { slug: 'amire-strategic-digital-marketing', name: 'Amire Strategic Digital Marketing', website: 'https://amire.com.au' },
  { slug: 'arch', name: 'Arch', website: 'https://wearearch.com' },
  { slug: 'ard-contracts-ltd', name: 'Ard Contracts Ltd', website: 'https://ardcontracts.com' },
  { slug: 'austcorp', name: 'Austcorp', website: 'https://austcorpexecutive.com.au' },
  { slug: 'auto-mate-consultants', name: 'Auto-mate Consultants', website: 'https://auto-mateconsultants.co.uk' },
  { slug: 'b4b-group', name: 'B4B Group', website: 'https://b4bgroup.ie' },
  { slug: 'braidwater-limited', name: 'BRAIDWATER LIMITED', website: 'https://braidwater.com' },
  { slug: 'brm-utility-services-ltd', name: 'BRM UTILITY SERVICES LTD', website: 'https://brmusl.co.uk' },
  { slug: 'bsg', name: 'BSG', website: 'https://bsg-ltd.com' },
  { slug: 'bwdi-ltd', name: 'BWDI Ltd', website: 'https://bwdiltd.com' },
  { slug: 'bloom-procurement-services', name: 'Bloom Procurement Services', website: 'https://bloom.services' },
  { slug: 'blue-zinc-it', name: 'Blue Zinc IT', website: 'https://blue-zinc.com' },
  { slug: 'budibase', name: 'Budibase', website: 'https://budibase.com' },
  { slug: 'carnanbane-building-contractors-limited', name: 'CARNANBANE BUILDING CONTRACTORS LIMITED', website: 'https://cbcni.co.uk' },
  { slug: 'callaghan-group', name: 'Callaghan Group', website: 'https://callaghangroup.ie' },
  { slug: 'challengecurve', name: 'ChallengeCurve', website: 'https://challengecurve.com' },
  { slug: 'claremount-accountants', name: 'Claremount Accountants', website: 'https://claremount.net' },
  { slug: 'combined-facilities-management-cfm-ltd', name: 'Combined Facilities Management (CFM) Ltd', website: 'https://cfm-ni.com' },
  { slug: 'compass-informatics', name: 'Compass Informatics', website: 'https://compass.ie' },
  { slug: 'compass-windows-and-doors', name: 'Compass Windows and Doors', website: 'https://compasswd.com' },
  { slug: 'confrere-building-control-ltd', name: 'Confrere Building Control Ltd', website: 'https://confrere.co.uk' },
  { slug: 'conscia', name: 'Conscia', website: 'https://conscia.com.au' },
  { slug: 'creevagh-consulting-engineers-limited', name: 'Creevagh Consulting Engineers Limited', website: 'https://creevagh.com' },
  { slug: 'd4-solutions', name: 'D4 Solutions', website: 'https://d4solutions.co.uk' },
  { slug: 'deci-ltd', name: 'DECI Ltd', website: 'https://deci-ltd.com' },
  { slug: 'disten-property-maintenance-ltd', name: 'DISTEN PROPERTY MAINTENANCE LTD', website: 'https://disten.net' },
  { slug: 'dml-interior-systems-ltd', name: 'DML Interior Systems Ltd', website: 'https://dmlcontracts.com' },
  { slug: 'dataops-live', name: 'DataOps.live', website: 'https://dataops.live' },
  { slug: 'derry-chamber-of-commerce', name: 'Derry Chamber of Commerce', website: 'https://londonderrychamber.co.uk' },
  { slug: 'donaldson-and-thompson-ltd', name: 'Donaldson & Thompson Ltd', website: 'https://dt-accountants.com' },
  { slug: 'dynamic-sales-force', name: 'Dynamic Sales Force', website: 'https://dynamicsalesforce.co.uk' },
  { slug: 'dysnix', name: 'Dysnix', website: 'https://dysnix.com' },
  { slug: 'eha-group', name: 'EHA Group', website: 'https://ehagroup.co.uk' },
  { slug: 'eoc-estate-agents', name: 'EOC Estate Agents', website: 'https://eocestateagents.com' },
  { slug: 'ewl-living', name: 'EWL Living', website: 'https://ecoworldlondon.com' },
  { slug: 'edgewater-contracts-and-specialist-joinery-ltd', name: 'Edgewater Contracts & Specialist Joinery Ltd', website: 'https://edgewatercontracts.co.uk' },
  { slug: 'elevate-labs', name: 'Elevate Labs', website: 'https://elevate-labs.io' },
  { slug: 'ellipsys', name: 'Ellipsys', website: 'https://ellipsys.ai' },
  { slug: 'engineering-maintenance-and-fitting-ltd', name: 'Engineering Maintenance and Fitting ltd', website: 'https://emf-ltd.net' },
  { slug: 'enterprise-north-west-limited', name: 'Enterprise North West Limited', website: 'https://enterprisenw.com' },
  { slug: 'evide', name: 'Evide', website: 'https://evide.org' },
  { slug: 'evouchers', name: 'Evouchers', website: 'https://evouchers.com' },
  { slug: 'fermac-properties-limited', name: 'FERMAC PROPERTIES LIMITED', website: 'https://fermacproperties.com' },
  { slug: 'fnw-group', name: 'FNW Group', website: 'https://fnw-group.com' },
  { slug: 'fasthouse', name: 'FastHouse', website: 'https://fast-house.co.uk' },
  { slug: 'foylesoft-ltd', name: 'Foylesoft Ltd', website: 'https://foylesoft.co.uk' },
  { slug: 'franklins-estate-agents', name: 'Franklins Estate Agents', website: 'https://franklins.ie' },
  { slug: 'g2-speech', name: 'G2 Speech', website: 'https://g2speech.com' },
  { slug: 'glendermott-enterprises-limited', name: 'GLENDERMOTT ENTERPRISES LIMITED', website: 'https://glendermott.com' },
  { slug: 'gavan-mcgill-and-company', name: 'Gavan McGill & Company', website: 'https://gmcgillaccountants.com' },
  { slug: 'glenform-building-ltd', name: 'Glenform Building Ltd', website: 'https://glenform.com' },
  { slug: 'glenturas-construction', name: 'Glenturas Construction', website: 'https://glenturas.com' },
  { slug: 'globalize', name: 'Globalize', website: 'https://globalize.co.uk' },
  { slug: 'grammarguru', name: 'GrammarGuru', website: 'https://grammarguru.app' },
  { slug: 'gray-s-marketing-and-comms-specialists', name: 'Gray\'s Marketing & Comms Specialists', website: 'https://grayscommunications.com' },
  { slug: 'greenview', name: 'Greenview', website: 'https://greenviewgroup.com' },
  { slug: 'h-and-a-group', name: 'H&A GROUP', website: 'https://thehagroup.com' },
  { slug: 'humain', name: 'HUMAIN', website: 'https://humain-studios.com' },
  { slug: 'handicaddie', name: 'Handicaddie', website: 'https://handicaddie.com' },
  { slug: 'hard-yards-scale-up-support', name: 'Hard Yards - Scale Up Support', website: 'https://hardyards.uk' },
  { slug: 'healex-systems-limited', name: 'Healex Systems Limited', website: 'https://healex.com' },
  { slug: 'henderson-technology-edgepos', name: 'Henderson Technology - EDGEPoS', website: 'https://henderson.technology' },
  { slug: 'hive-group', name: 'Hive Group', website: 'https://hive-group.com' },
  { slug: 'hub44', name: 'Hub44', website: 'https://hub44.co.uk' },
  { slug: 'inspired', name: 'INSPIRED', website: 'https://inspiredca.com' },
  { slug: 'image-promotional-branding-llc', name: 'Image Promotional Branding, LLC', website: 'https://imagepb.com' },
  { slug: 'innovate-ni', name: 'Innovate-NI', website: 'https://innovate-ni.com' },
  { slug: 'intsys-solutions', name: 'IntSys Solutions', website: 'https://intsys-solutions.com' },
  { slug: 'international-synergies-ni-ltd', name: 'International Synergies NI Ltd', website: 'https://international-synergies.com' },
  { slug: 'intouch-network-solutions', name: 'Intouch Network Solutions', website: 'https://intouchns.com' },
  { slug: 'jpm-contracts-ltd', name: 'JPM Contracts Ltd', website: 'https://jpm-contracts.com' },
  { slug: 'jsc-consulting-structural-engineers', name: 'JSC Consulting Structural Engineers', website: 'https://jscconsulting.co.uk' },
  { slug: 'kevin-watson-group', name: 'Kevin Watson Group', website: 'https://kevinwatsongroup.com' },
  { slug: 'kilcreen-consulting-limited', name: 'Kilcreen Consulting Limited', website: 'https://kilcreenconsulting.com' },
  { slug: 'kilwaughter-minerals-ltd', name: 'Kilwaughter Minerals Ltd', website: 'https://kilwaughter.com' },
  { slug: 'knowio-by-inniovate', name: 'Knowio by Inniovate', website: 'https://inniovate.com' },
  { slug: 'konstruct-group', name: 'Konstruct Group', website: 'https://konstruct.group' },
  { slug: 'lmc-drylining-ltd', name: 'LMC Drylining Ltd', website: 'https://lmcdrylining.co.uk' },
  { slug: 'landlord-vision-ltd', name: 'Landlord Vision Ltd', website: 'https://landlordvision.co.uk' },
  { slug: 'm-a-mccloskey-ltd-consulting-engineers', name: 'M.A McCloskey Ltd Consulting Engineers', website: 'https://mamccloskeyltd.com' },
  { slug: 'mci-chartered-accountants', name: 'MCI Chartered Accountants', website: 'https://mciaccountants.com' },
  { slug: 'midd-electrical-ltd', name: 'MIDD ELECTRICAL LTD', website: 'https://middelectrical.com' },
  { slug: 'mulderg-interior-linings-limited', name: 'MULDERG INTERIOR LININGS LIMITED', website: 'https://mulderginteriorlinings.co.uk' },
  { slug: 'martin-property-group', name: 'Martin Property Group', website: 'https://martin-group.co.uk' },
  { slug: 'mccallion-group', name: 'McCallion Group', website: 'https://mccalliongroup.ie' },
  { slug: 'mckelvey-construction', name: 'McKelvey Construction', website: 'https://mckelveyconstruction.co.uk' },
  { slug: 'mccambridge-duffy-llp', name: 'Mccambridge Duffy Llp', website: 'https://mccambridgeduffy.co.uk' },
  { slug: 'metadeck', name: 'Metadeck', website: 'https://metadeck.io' },
  { slug: 'metomic', name: 'Metomic', website: 'https://metomic.io' },
  { slug: 'mind³-ltd-mind-cubed', name: 'Mind³ Ltd (Mind Cubed)', website: 'https://mind-3.com' },
  { slug: 'modern-agility-ltd', name: 'Modern Agility Ltd', website: 'https://modernagilityltd.com' },
  { slug: 'modern-democracy', name: 'Modern Democracy', website: 'https://moderndemocracy.com' },
  { slug: 'montgomery-and-mccleery-estate-agents', name: 'Montgomery & McCleery Estate Agents', website: 'https://montgomerymccleery.com' },
  { slug: 'moore-ni', name: 'Moore NI', website: 'https://mooreni.co.uk' },
  { slug: 'my-accountant-friend', name: 'My Accountant Friend', website: 'https://myaccountantfriend.com' },
  { slug: 'n-and-r-devine-ltd', name: 'N & R DEVINE LTD', website: 'https://n-rgroup.com' },
  { slug: 'npf-group', name: 'NPF Group', website: 'https://northernpowerforce.com' },
  { slug: 'newtownstewart-construction-uk-ltd', name: 'Newtownstewart Construction UK Ltd', website: 'https://nsc-uk.com' },
  { slug: 'newtownstewart-ltd', name: 'Newtownstewart Ltd', website: 'https://newtownstewart.co.uk' },
  { slug: 'nics', name: 'Nics', website: 'https://nics.com.tr' },
  { slug: 'nimbus', name: 'Nimbus', website: 'https://nimbuscs.com' },
  { slug: 'nvolve', name: 'Nvolve', website: 'https://nvolvegroup.com' },
  { slug: 'o-neill-bros-master-joiners-ltd', name: 'O\'Neill Bros Master Joiners Ltd', website: 'https://oneillbros.com' },
  { slug: 'obconstruction', name: 'OBConstruction', website: 'https://obconstruction.co.uk' },
  { slug: 'outsource', name: 'OUTSOURCE', website: 'https://osgroup.co.uk' },
  { slug: 'obbi-club', name: 'Obbi Club', website: 'https://obbi.club' },
  { slug: 'ondox', name: 'Ondox', website: 'https://litheit.com' },
  { slug: 'optik', name: 'Optik', website: 'https://optikai.io' },
  { slug: 'pdsvision-uk', name: 'PDSVISION UK', website: 'https://root-solutions.co.uk' },
  { slug: 'pgr-chartered-accountants', name: 'PGR Chartered Accountants', website: 'https://pgraccountants.com' },
  { slug: 'payescape-ltd', name: 'PayEscape Ltd', website: 'https://payescape.com' },
  { slug: 'pentagon-solutions-ltd', name: 'Pentagon Solutions Ltd.', website: 'https://pentagonsolutions.com' },
  { slug: 'pixl8-group', name: 'Pixl8 Group', website: 'https://pixl8.com' },
  { slug: 'quantum-group-ni', name: 'Quantum Group NI', website: 'https://quantumgroupni.com' },
  { slug: 'rst-epos-hospitality-and-retail-solutions', name: 'RST EPoS - Hospitality and Retail Solutions', website: 'https://rstepos.com' },
  { slug: 'radius-ireland', name: 'Radius - Ireland', website: 'https://dcicard.co.uk' },
  { slug: 'resdiary', name: 'ResDiary', website: 'https://resdiary.com' },
  { slug: 'roll-innovation', name: 'Roll Innovation', website: 'https://rollinnovation.co.uk' },
  { slug: 'simply-zesty-uk-limited', name: 'SIMPLY ZESTY UK LIMITED', website: 'https://simplyzesty.com' },
  { slug: 'sm-devine', name: 'SM Devine', website: 'https://smdevine.co.uk' },
  { slug: 'smg-contracts', name: 'SMG Contracts', website: 'https://smgcontracts.com' },
  { slug: 'swamp-by-system-initiative', name: 'SWAMP by System Initiative', website: 'https://systeminit.com' },
  { slug: 'salutem-insights-ltd', name: 'Salutem Insights Ltd.', website: 'https://saluteminsights.com' },
  { slug: 'sammon', name: 'Sammon', website: 'https://sammon.eu' },
  { slug: 'satori-accounting', name: 'Satori Accounting', website: 'https://satoriaccounting.com' },
  { slug: 'sinann-people', name: 'Sinann People', website: 'https://sinannpeople.com' },
  { slug: 'sourcedogg', name: 'SourceDogg', website: 'https://sourcedogg.com' },
  { slug: 'spotx-now-part-of-magnite', name: 'SpotX (now part of Magnite)', website: 'https://spotxchange.com' },
  { slug: 'sustainiq', name: 'SustainIQ', website: 'https://sustainiq.co.uk' },
  { slug: 'tmcl-and-sons-contracts-ltd', name: 'TMcL & Sons Contracts Ltd', website: 'https://tmclandsons.com' },
  { slug: 'tabulator', name: 'Tabulator', website: 'https://tabulator.info' },
  { slug: 'talon-ireland', name: 'Talon Ireland', website: 'https://theoval.ie' },
  { slug: 'techethics', name: 'TechEthics', website: 'https://techethics.co.uk' },
  { slug: 'terramar-networks', name: 'TerraMar Networks', website: 'https://terramarnetworks.com' },
  { slug: 'the-bionic-group', name: 'The Bionic Group', website: 'https://thebionicgroup.com' },
  { slug: 'the-hughes-consultancy', name: 'The Hughes Consultancy', website: 'https://thehughesconsultancy.co.uk' },
  { slug: 'the-mcginnis-group', name: 'The McGinnis Group', website: 'https://themcginnisgroup.com' },
  { slug: 'the-web-crew', name: 'The Web Crew', website: 'https://thewebcrew.co.uk' },
  { slug: 'thinkcare', name: 'Thinkcare', website: 'https://thinkcare.org.uk' },
  { slug: 'three-plus-consulting', name: 'Three Plus Consulting', website: 'https://3plusconsulting.co.uk' },
  { slug: 'toast-accountants', name: 'Toast Accountants', website: 'https://toast.tax' },
  { slug: 'turnkey-ips', name: 'Turnkey IPS', website: 'https://turnkey-ips.com' },
  { slug: 'used-cars-ni', name: 'Used Cars NI', website: 'https://usedcarsni.com' },
  { slug: 'visfo', name: 'VISFO', website: 'https://visfo.health' },
  { slug: 'valley-roofing-ltd', name: 'Valley Roofing Ltd', website: 'https://valleyroofing.co.uk' },
  { slug: 'verallo', name: 'Verallo', website: 'https://verallo.com' },
  { slug: 'w-and-j-chambers-ltd', name: 'W. & J. CHAMBERS LTD', website: 'https://wjchambers.com' },
  { slug: 'wh-stephens', name: 'WH Stephens', website: 'https://whstephens.com' },
  { slug: 'water-solutions-ireland-ltd', name: 'Water Solutions Ireland Ltd', website: 'https://watersolutions-ireland.com' },
  { slug: 'web-control', name: 'Web Control', website: 'https://webcontrol.co.uk' },
  { slug: 'webuild', name: 'Webuild', website: 'https://webuild.team' },
  { slug: 'whitehat-dynamic-by-synopsys', name: 'WhiteHat Dynamic by Synopsys', website: 'https://whitehatsec.com' },
  { slug: 'https://yourworkpal.com', name: 'WorkPal ', website: ' Smarter Job Management' },
  { slug: 'wurkhouse', name: 'Wurkhouse', website: 'https://wurkhouse.com' },
  { slug: 'xcn', name: 'XCN', website: 'https://xcn-eng.com' },
  { slug: 'yavia', name: 'YAVIA', website: 'https://yavia.co.uk' },
  { slug: 'ypp-lettings', name: 'YPP Lettings', website: 'https://ypp.co.uk' },
  { slug: 'yourtradebase', name: 'YourTradebase', website: 'https://yourtradebase.com' },
  { slug: 'zerographic-systems', name: 'Zerographic Systems', website: 'https://zerographic.com' },
  { slug: 'zymplify', name: 'Zymplify', website: 'https://zymplify.com' },
  { slug: 'edesk', name: 'eDesk', website: 'https://edesk.com' },
  { slug: 'trufflepig', name: 'trufflepig', website: 'https://trufflepig.ai' },
];

export function getCompanyBySlug(slug: string): Company | undefined {
  return companies.find(c => c.slug === slug);
}
