export type Showcase = {
  slug: string;
  address: string;
  shortAddress: string;
  location: string;
  sourceUrl: string;
  currentAgent: string;
  priceText: string;
  originalPriceText?: string;
  priceSignal?: string;
  daysLive: number;
  listedDate: string;
  updatedDate: string;
  beds: number;
  baths: number;
  receptions: number;
  style: string;
  brief: string;
  hero: string;
  images: string[];
  viewsAllTime?: string;
  views30?: string;
  views7?: string;
  story: string;
  opportunity: string;
  buyerAngles: string[];
  relaunchPlan: string[];
  socialHooks: string[];
  accessPostcodes: string[];
};

export const contact = {
  phone: '07786 910 768',
  email: 'james@jamesgormanproperty.com',
  website: 'jamesgormanproperty.com',
};

export const showcases: Showcase[] = [
  {
    slug: '270-culmore-road',
    address: '270 Culmore Road, Culmore, Derry, BT48 8JL',
    shortAddress: '270 Culmore Road',
    location: 'Culmore, BT48',
    sourceUrl: 'https://www.propertypal.com/1018806',
    currentAgent: 'Oakland Estate Agents',
    priceText: 'Offers Over £750,000',
    originalPriceText: '£825,000',
    priceSignal: 'Price reduced by £75,000 in March 2026',
    daysLive: 350,
    listedDate: '29 May 2025',
    updatedDate: '17 March 2026',
    beds: 5,
    baths: 3,
    receptions: 5,
    style: 'Detached landmark home',
    brief: '5 Bed Detached House',
    hero: 'https://media.propertypal.com/large/p/1017606/38329830.jpg',
    images: [
      'https://media.propertypal.com/large/p/1017606/38329830.jpg',
      'https://media.propertypal.com/large/p/1017606/38329831.jpg',
      'https://media.propertypal.com/large/p/1017606/38329832.jpg',
      'https://media.propertypal.com/large/p/1017606/38329833.jpg',
      'https://media.propertypal.com/large/p/1017606/38329835.jpg',
      'https://media.propertypal.com/large/p/1017606/38329955.jpg',
      'https://media.propertypal.com/large/p/1017606/38329957.jpg',
      'https://media.propertypal.com/large/p/1017606/38329971.jpg',
    ],
    viewsAllTime: '44,303',
    views30: '924',
    views7: '269',
    story: 'Old Hollybush School House is a rare landmark home with local history, scale, privacy and around two acres of gardens close to Derry, Donegal and the airport.',
    opportunity: 'This should feel less like a standard listing and more like the sale of a landmark estate: heritage, privacy, lifestyle, space, work-from-home and cross-border convenience.',
    buyerAngles: ['Historic landmark home', 'Approx. 4,000 sq ft of upgraded accommodation', 'Two-acre private garden setting', 'Garage / workshop with media or home office space'],
    relaunchPlan: ['Lead with the Hollybush School House story, not just room counts.', 'Create a cinematic garden, lifestyle and heritage reel for social.', 'Target executive movers, returning Derry families and Donegal-border buyers.', 'Retarget engaged viewers with a private viewing invitation.'],
    socialHooks: ['A former school transformed into a private Culmore landmark', 'Two acres, five receptions and a home-office above the garage', 'The kind of home buyers remember after one scroll'],
    accessPostcodes: ['BT488JL', 'BT48 8JL'],
  },
  {
    slug: 'cregg-lodge-claudy',
    address: 'Cregg Lodge, 346 Glenshane Road, Claudy, BT47 4HP',
    shortAddress: 'Cregg Lodge',
    location: 'Claudy, BT47',
    sourceUrl: 'https://www.propertypal.com/1019432',
    currentAgent: 'Daniel Henry',
    priceText: 'Offers Over £695,000',
    daysLive: 346,
    listedDate: '2 June 2025',
    updatedDate: '1 July 2025',
    beds: 5,
    baths: 4,
    receptions: 5,
    style: 'Large detached family home',
    brief: '5 Bed Detached House',
    hero: 'https://media.propertypal.com/large/p/1018232/38345165.jpg',
    images: [
      'https://media.propertypal.com/large/p/1018232/38345165.jpg',
      'https://media.propertypal.com/large/p/1018232/38345162.jpg',
      'https://media.propertypal.com/large/p/1018232/38345168.jpg',
      'https://media.propertypal.com/large/p/1018232/38345161.jpg',
      'https://media.propertypal.com/large/p/1018232/38345166.jpg',
      'https://media.propertypal.com/large/p/1018232/38345163.jpg',
      'https://media.propertypal.com/large/p/1018232/38345167.jpg',
      'https://media.propertypal.com/large/p/1018232/38345164.jpg',
    ],
    viewsAllTime: '17,911',
    views30: '781',
    views7: '188',
    story: 'A substantial red-brick home of approximately 4,500 sq ft, set on a large private plot with mature lawns, five receptions, five bedrooms, games room, study and garage.',
    opportunity: 'The listing has real ingredients for a premium family-home campaign, but it needs a stronger emotional route: arrival, scale, garden, entertaining and easy A6 access.',
    buyerAngles: ['Approx. 4,500 sq ft', 'Five reception rooms plus games room', 'Large mature plot and sweeping driveway', 'Convenient A6 commuter position'],
    relaunchPlan: ['Reframe around scale, privacy and family lifestyle.', 'Build a “grand arrival” video using the driveway, hallway and gardens.', 'Target Derry professionals, growing families and relocation buyers.', 'Use a premium viewing campaign instead of relying on passive portal traffic.'],
    socialHooks: ['The family home with room for every stage of life', 'A private Claudy plot with serious presence', 'Five receptions, five bedrooms and a games room'],
    accessPostcodes: ['BT474HP', 'BT47 4HP'],
  },
  {
    slug: '52-tirbracken-road',
    address: '52 Tirbracken Road, Drumahoe, Londonderry, BT47 3LS',
    shortAddress: '52 Tirbracken Road',
    location: 'Drumahoe, BT47',
    sourceUrl: 'https://www.propertypal.com/1019847',
    currentAgent: 'Robert Ferris Estate Agents',
    priceText: 'Price from £399,950',
    originalPriceText: '£485,000',
    priceSignal: 'Fresh reduction from £485,000 to £399,950',
    daysLive: 332,
    listedDate: '16 June 2025',
    updatedDate: '15 May 2026',
    beds: 3,
    baths: 1,
    receptions: 1,
    style: 'Home + business / investment opportunity',
    brief: 'Detached house with adjoining business premises',
    hero: 'https://media.propertypal.com/large/p/1018647/40064228.jpg',
    images: [
      'https://media.propertypal.com/large/p/1018647/40064228.jpg',
      'https://media.propertypal.com/large/p/1018647/40064226.jpg',
      'https://media.propertypal.com/large/p/1018647/40064301.jpg',
      'https://media.propertypal.com/large/p/1018647/38357394.jpg',
      'https://media.propertypal.com/large/p/1018647/38357396.jpg',
      'https://media.propertypal.com/large/p/1018647/39999563.jpg',
      'https://media.propertypal.com/large/p/1018647/38356546.jpg',
      'https://media.propertypal.com/large/p/1018647/38356550.jpg',
    ],
    viewsAllTime: '16,706',
    views30: '876',
    views7: '137',
    story: 'A rare home plus business / investment opportunity close to the A6, combining a modern detached bungalow with established Class 1 retail premises formerly associated with a long-running car parts business.',
    opportunity: 'This needs investor-style positioning: income potential, owner-occupier use, road connectivity, secure yard space and the story of an established trading site.',
    buyerAngles: ['Residential plus Class 1 retail premises', 'Close to A6 Belfast–Derry route', 'Former long-established car parts site', 'Potential rental and owner-occupier angles'],
    relaunchPlan: ['Split the campaign into investor, trade buyer and live-work buyer stories.', 'Create a simple income-potential explainer instead of a standard house listing.', 'Target local business owners, trades and commercial investors.', 'Use the fresh price reduction as a relaunch moment.'],
    socialHooks: ['A live-work opportunity beside the A6', 'Home, yard and business premises in one package', 'Freshly repositioned below £400k'],
    accessPostcodes: ['BT473LS', 'BT47 3LS'],
  },
  {
    slug: '6-oak-country-green',
    address: '6 Oak Country Green, Waterside, Derry, BT47 6FU',
    shortAddress: '6 Oak Country Green',
    location: 'Waterside, BT47',
    sourceUrl: 'https://www.propertypal.com/6-oak-country-green-waterside-derry/1032131',
    currentAgent: 'Pauline Elliott Estate Agents',
    priceText: 'Offers Over £385,000',
    originalPriceText: '£399,500',
    priceSignal: 'Originally marketed at £399,500, reduced to £375,000, sale agreed, then relaunched at £385,000 in February 2026',
    daysLive: 290,
    listedDate: '11 August 2025',
    updatedDate: '4 February 2026',
    beds: 4,
    baths: 2,
    receptions: 1,
    style: 'Detached chalet bungalow',
    brief: '4 Bed Detached Chalet Bungalow',
    hero: 'https://media.propertypal.com/large/p/1030931/38731503.jpg',
    images: [
      'https://media.propertypal.com/large/p/1030931/38731503.jpg',
      'https://media.propertypal.com/large/p/1030931/38731504.jpg',
      'https://media.propertypal.com/large/p/1030931/38731502.jpg',
      'https://media.propertypal.com/large/p/1030931/38731367.jpg',
      'https://media.propertypal.com/large/p/1030931/38731374.jpg',
      'https://media.propertypal.com/large/p/1030931/38731377.jpg',
      'https://media.propertypal.com/large/p/1030931/38731378.jpg',
      'https://media.propertypal.com/large/p/1030931/38731379.jpg',
    ],
    viewsAllTime: '29,048',
    views30: '1,754',
    views7: '430',
    story: 'A polished four-bedroom detached chalet bungalow tucked into a Waterside cul-de-sac, with a strong kitchen-dining space, private gardens, garage and early occupation available.',
    opportunity: 'Oak Country Green has had plenty of portal attention and a previous sale-agreed moment, but after a long run it needs a reset: position it around move-in readiness, cul-de-sac calm, energy efficiency and family convenience rather than another standard bungalow listing.',
    buyerAngles: ['Quiet cul-de-sac setting in Waterside', 'Four-bedroom chalet bungalow layout', 'Gas heating, double glazing and strong EPC rating', 'Early occupation available after a long campaign'],
    relaunchPlan: ['Reframe as a ready-to-move Waterside family home, not just a room-by-room spec sheet.', 'Create a warm “cul-de-sac living” reel using the kitchen, lounge, garden and frontage.', 'Target upsizers, returning Derry families and buyers who missed out when it previously went sale agreed.', 'Use the relaunch history as a reason for fresh calls, private viewings and buyer follow-up.'],
    socialHooks: ['The Waterside cul-de-sac home that deserves a fresh audience', 'Four bedrooms, garage and early occupation available', 'A sale-agreed story that needs a stronger second launch'],
    accessPostcodes: ['BT476FU', 'BT47 6FU'],
  },
  {
    slug: '12-church-road-altnagelvin',
    address: '12 Church Road, Altnagelvin, Derry, BT47 3QB',
    shortAddress: '12 Church Road',
    location: 'Altnagelvin, BT47',
    sourceUrl: 'https://www.propertypal.com/12-church-road-altnagelvin-derry-londonderry/1030647',
    currentAgent: 'Robert Quigley Estate Agents',
    priceText: 'Price £350,000',
    originalPriceText: '£375,000',
    priceSignal: 'Reduced from £375,000 to £360,000, sale agreed, then relaunched at £350,000 in May 2026',
    daysLive: 300,
    listedDate: '1 August 2025',
    updatedDate: '20 May 2026',
    beds: 4,
    baths: 2,
    receptions: 4,
    style: 'Detached bungalow on a generous plot',
    brief: '4 Bed Detached Bungalow',
    hero: 'https://media.propertypal.com/large/p/1029447/38689599.jpg',
    images: [
      'https://media.propertypal.com/large/p/1029447/38689599.jpg',
      'https://media.propertypal.com/large/p/1029447/38689596.jpg',
      'https://media.propertypal.com/large/p/1029447/38689595.jpg',
      'https://media.propertypal.com/large/p/1029447/38689603.jpg',
      'https://media.propertypal.com/large/p/1029447/38689618.jpg',
      'https://media.propertypal.com/large/p/1029447/38689613.jpg',
      'https://media.propertypal.com/large/p/1029447/38689615.jpg',
      'https://media.propertypal.com/large/p/1029447/38689620.jpg',
    ],
    viewsAllTime: '22,061',
    views30: '1,309',
    views7: '687',
    story: 'A bright, spacious Altnagelvin detached bungalow with around 2,475 sq ft, multiple living areas, flexible fourth-bedroom potential and generous front and rear gardens.',
    opportunity: 'This is not a small bungalow — it is a flexible family-scale home in a practical Altnagelvin position. The campaign should lean into space, layout options, garden life and the recent price reset.',
    buyerAngles: ['Approx. 2,475 sq ft of flexible accommodation', 'Four receptions / multiple living zones', 'Generous gardens front and rear', 'Fresh £350,000 relaunch after previous sale-agreed status'],
    relaunchPlan: ['Lead with the size and flexibility: bungalow convenience with family-house scale.', 'Build a walkthrough campaign around “four ways to live in this home” using the multiple reception rooms.', 'Target downsizers who still need space, families wanting single-level living and Altnagelvin/Waterside movers.', 'Use the recent £350,000 reset as a direct reason to re-engage interested buyers quickly.'],
    socialHooks: ['The Altnagelvin bungalow with family-home scale', 'Four living spaces, generous gardens and a fresh price reset', 'A flexible home that should be shown, not just listed'],
    accessPostcodes: ['BT473QB', 'BT47 3QB'],
  },
  {
    slug: '17-rossdowney-park',
    address: "17 Rossdowney Park, Waterside, Derry, BT47 5NR",
    shortAddress: '17 Rossdowney Park',
    location: 'Waterside, BT47',
    sourceUrl: 'https://www.propertypal.com/17-rossdowney-park-waterisde-lderry/1027754',
    currentAgent: 'Pauline Elliott Estate Agents',
    priceText: 'Asking Price £259,950',
    originalPriceText: '£275,000',
    priceSignal: 'Reduced from £275,000 to £265,000, then to £259,950 in April 2026; now 348 days live with 24,603 all-time views',
    daysLive: 348,
    listedDate: '16 July 2025',
    updatedDate: '15 April 2026',
    beds: 3,
    baths: 1,
    receptions: 1,
    style: 'Detached bungalow with garage',
    brief: '3 Bed Detached Bungalow with Garage',
    hero: 'https://media.propertypal.com/large/p/1026554/38601539.jpg',
    images: [
      'https://media.propertypal.com/large/p/1026554/38601539.jpg',
      'https://media.propertypal.com/large/p/1026554/38601540.jpg',
      'https://media.propertypal.com/large/p/1026554/38601541.jpg',
      'https://media.propertypal.com/large/p/1026554/38601480.jpg',
      'https://media.propertypal.com/large/p/1026554/38601481.jpg',
      'https://media.propertypal.com/large/p/1026554/38601482.jpg',
      'https://media.propertypal.com/large/p/1026554/38601483.jpg',
      'https://media.propertypal.com/large/p/1026554/38601484.jpg',
    ],
    viewsAllTime: '24,603',
    views30: '4,295',
    views7: '349',
    story: 'A detached Waterside bungalow with garage, three bedrooms, early occupation available and a practical Rossdowney Park setting close to local amenities.',
    opportunity: 'The listing has ongoing attention but needs a cleaner emotional route: low-maintenance bungalow living, early occupation, garage, mature Waterside location and a clear price-reduction relaunch.',
    buyerAngles: ['Detached bungalow with garage', 'Early occupation available', 'Reduced from £275,000 to £259,950', 'Waterside location with strong downsizer appeal'],
    relaunchPlan: ['Position it around ease: bungalow living, garage, early occupation and a manageable move.', 'Create a simple “ready for its next chapter” content set aimed at downsizers and local movers.', 'Retarget older portal viewers and buyers searching for bungalows under £300k in Waterside.', 'Use the two-stage price reduction as a fresh campaign trigger rather than letting it sit passively.'],
    socialHooks: ['A Waterside bungalow ready for its next chapter', 'Detached, reduced and available for early occupation', 'The kind of bungalow local buyers ask for — but it needs a sharper push'],
    accessPostcodes: ['BT475NR', 'BT47 5NR'],
  },
  {
    slug: '29-mallory-park',
    address: '29 Mallory Park, Eglinton, Derry, BT47 3XJ',
    shortAddress: '29 Mallory Park',
    location: 'Eglinton, BT47',
    sourceUrl: 'https://www.propertypal.com/29-mallory-park-eglinton-derry/1052760',
    currentAgent: 'Pauline Elliott Estate Agents',
    priceText: 'Offers Over £249,950',
    originalPriceText: '£269,950',
    priceSignal: 'Reduced from £269,950 during the campaign and still live after 173 days',
    daysLive: 173,
    listedDate: '7 January 2026',
    updatedDate: '28 April 2026',
    beds: 3,
    baths: 1,
    receptions: 1,
    style: 'Detached bungalow in Eglinton',
    brief: '3 Bed Detached Bungalow',
    hero: 'https://media.propertypal.com/large/p/1051560/39892923.jpg',
    images: [
      'https://media.propertypal.com/large/p/1051560/39892923.jpg',
      'https://media.propertypal.com/large/p/1051560/39892924.jpg',
      'https://media.propertypal.com/large/p/1051560/39892926.jpg',
      'https://media.propertypal.com/large/p/1051560/39892927.jpg',
      'https://media.propertypal.com/large/p/1051560/39892928.jpg',
      'https://media.propertypal.com/large/p/1051560/39892929.jpg',
      'https://media.propertypal.com/large/p/1051560/39892930.jpg',
      'https://media.propertypal.com/large/p/1051560/39892931.jpg',
    ],
    viewsAllTime: '13,299',
    views30: '2,679',
    story: 'A three-bedroom detached bungalow in an Eglinton cul-de-sac, with oil heating, uPVC glazing, driveway parking, patio space and early occupation available.',
    opportunity: 'Mallory Park is close to the £250k mark and has already been repriced, but the listing still reads like a features list. A relaunch should lead with the Eglinton lifestyle, cul-de-sac ease and bungalow convenience.',
    buyerAngles: ['Eglinton cul-de-sac setting', 'Detached bungalow close to £250k', 'Early occupation available', 'Recent price reset from £269,950'],
    relaunchPlan: ['Position around easy single-level living in Eglinton rather than another standard bungalow spec.', 'Build a compact “ready to move” reel using the frontage, kitchen, lounge and patio.', 'Target downsizers, local Eglinton movers and Derry/Limavady commuters.', 'Use the price reduction and 152-day run as a reason for a proper campaign reset.'],
    socialHooks: ['The Eglinton bungalow that needs a sharper second push', 'Reduced, detached and ready for early occupation', 'A cul-de-sac home local downsizers should be seeing'],
    accessPostcodes: ['BT473XJ', 'BT47 3XJ'],
  },
  {
    slug: '14-clarendon-street',
    address: '14 Clarendon Street, Derry, BT48 7ET',
    shortAddress: '14 Clarendon Street',
    location: 'Cityside, BT48',
    sourceUrl: 'https://www.propertypal.com/14-clarendon-street-derry/986071',
    currentAgent: 'Oakland Estate Agents',
    priceText: 'Offers Over £250,000',
    priceSignal: 'Still live after 72 days, with investment and mixed-use potential needing clearer positioning',
    daysLive: 72,
    listedDate: '18 April 2026',
    updatedDate: '23 April 2026',
    beds: 0,
    baths: 1,
    receptions: 11,
    style: 'Three-storey townhouse / investment property',
    brief: 'Terrace House with 11 rooms/offices',
    hero: 'https://media.propertypal.com/large/p/984871/41421358.jpg',
    images: [
      'https://media.propertypal.com/large/p/984871/41421358.jpg',
      'https://media.propertypal.com/large/p/984871/41421354.jpg',
      'https://media.propertypal.com/large/p/984871/41421361.jpg',
      'https://media.propertypal.com/large/p/984871/41421371.jpg',
      'https://media.propertypal.com/large/p/984871/41421374.jpg',
      'https://media.propertypal.com/large/p/984871/41421395.jpg',
      'https://media.propertypal.com/large/p/984871/41421419.jpg',
      'https://media.propertypal.com/large/p/984871/41421417.jpg',
    ],
    viewsAllTime: '5,104',
    views30: '1,958',
    story: 'A substantial three-storey Clarendon Street property with 11 reception rooms/offices, vacant possession and potential for commercial, residential or HMO-style use subject to planning.',
    opportunity: 'This is not a normal terrace. The campaign should separate investor, professional-office, HMO and conversion angles so the right buyer understands the value quickly.',
    buyerAngles: ['11 rooms/offices across three storeys', 'Clarendon Street professional corridor', 'Vacant possession', 'Commercial, residential or investment potential'],
    relaunchPlan: ['Reframe the listing as an investment and conversion opportunity, not a standard townhouse.', 'Create a simple “four possible uses” explainer for social and email follow-up.', 'Target landlords, local professionals, developers and cityside investors.', 'Use the postcode-gated showcase to show how James would package the opportunity clearly.'],
    socialHooks: ['A Clarendon Street investment with more than one route to value', '11 rooms, vacant possession and cityside potential', 'Not a normal terrace — a property that needs a buyer-specific pitch'],
    accessPostcodes: ['BT487ET', 'BT48 7ET'],
  },
  {
    slug: '31-briar-hill',
    address: '31 Briar Hill, Greysteel, Derry, BT47 3DE',
    shortAddress: '31 Briar Hill',
    location: 'Greysteel, BT47',
    sourceUrl: 'https://www.propertypal.com/31-briar-hill-greysteel-derry/1070050',
    currentAgent: "EO'C Estate Agents",
    priceText: 'Asking Price £250,000',
    priceSignal: 'Live for 48 days at the exact £250k mark',
    daysLive: 48,
    listedDate: '21 April 2026',
    updatedDate: '21 April 2026',
    beds: 3,
    baths: 2,
    receptions: 1,
    style: 'Refurbished detached bungalow',
    brief: '3 Bed Detached Bungalow',
    hero: 'https://media.propertypal.com/large/p/1068850/41328963.jpg',
    images: [
      'https://media.propertypal.com/large/p/1068850/41328963.jpg',
      'https://media.propertypal.com/large/p/1068850/41328957.jpg',
      'https://media.propertypal.com/large/p/1068850/41328958.jpg',
      'https://media.propertypal.com/large/p/1068850/41328961.jpg',
      'https://media.propertypal.com/large/p/1068850/41328960.jpg',
      'https://media.propertypal.com/large/p/1068850/41328962.jpg',
      'https://media.propertypal.com/large/p/1068850/41328956.jpg',
      'https://media.propertypal.com/large/p/1068850/41328959.jpg',
    ],
    viewsAllTime: '4,756',
    views30: '2,137',
    story: 'A refurbished three-bedroom detached Greysteel bungalow with three double bedrooms, two bathrooms, new kitchen, upgraded bathroom and driveway parking for four cars.',
    opportunity: 'Briar Hill has move-in condition and village appeal, but needs a more emotional “finished bungalow between Derry and Limavady” pitch to convert browsers into viewings.',
    buyerAngles: ['Refurbished detached bungalow', 'Three double bedrooms and two bathrooms', 'Driveway parking for four cars', 'Minutes from Derry or Limavady'],
    relaunchPlan: ['Lead with move-in readiness and Greysteel convenience.', 'Create a before/after style reel around the refurb, kitchen, bathrooms and garden.', 'Target downsizers, young families and commuters priced around £250k.', 'Follow up recent viewers with a private viewing message built around no-work-needed living.'],
    socialHooks: ['A Greysteel bungalow that is ready without the project work', 'Three doubles, two bathrooms and parking for four', 'The £250k bungalow buyers should be comparing'],
    accessPostcodes: ['BT473DE', 'BT47 3DE'],
  },
  {
    slug: '123-abbeydale',
    address: "123 Abbeydale, Waterside, L'Derry, BT47 6FY",
    shortAddress: '123 Abbeydale',
    location: 'Waterside, BT47',
    sourceUrl: 'https://www.propertypal.com/123-abbeydale-waterside-lderry/1043543',
    currentAgent: "Paul O'Keefe Estate Agents",
    priceText: 'Offers Over £239,950',
    priceSignal: 'Live for 235 days with more than 18,500 all-time PropertyPal views',
    daysLive: 235,
    listedDate: '16 October 2025',
    updatedDate: '5 May 2026',
    beds: 3,
    baths: 1,
    receptions: 1,
    style: 'Detached bungalow on a corner plot',
    brief: '3 Bed Detached Bungalow',
    hero: 'https://media.propertypal.com/large/p/1042343/39191590.jpg',
    images: [
      'https://media.propertypal.com/large/p/1042343/39191590.jpg',
      'https://media.propertypal.com/large/p/1042343/39191591.jpg',
      'https://media.propertypal.com/large/p/1042343/39191592.jpg',
      'https://media.propertypal.com/large/p/1042343/39191593.jpg',
      'https://media.propertypal.com/large/p/1042343/39191594.jpg',
      'https://media.propertypal.com/large/p/1042343/39191595.jpg',
      'https://media.propertypal.com/large/p/1042343/39191596.jpg',
      'https://media.propertypal.com/large/p/1042343/39191603.jpg',
    ],
    viewsAllTime: '18,502',
    views30: '3,106',
    story: 'A detached Waterside bungalow with three double bedrooms, spacious living room, kitchen-dining area, utility room, detached garage and a large corner plot.',
    opportunity: 'Abbeydale is getting attention but has become familiar after a long portal run. The relaunch should focus on corner-plot space, bungalow scarcity and detached-garage practicality.',
    buyerAngles: ['Large corner plot', 'Detached garage', 'Three double bedrooms', 'Strong Waterside bungalow demand'],
    relaunchPlan: ['Reposition around space and scarcity: detached bungalow, garage and corner plot.', 'Create a “why bungalows move fast when marketed properly” campaign angle.', 'Retarget Waterside bungalow searchers and older portal viewers.', 'Use the 235-day run as a clear reason for a fresh James Gorman presentation.'],
    socialHooks: ['A Waterside bungalow with the corner plot buyers ask for', 'Detached, practical and still waiting for the right push', '18,500 views means attention — now it needs action'],
    accessPostcodes: ['BT476FY', 'BT47 6FY'],
  },
  {
    slug: '25-lenamore-park',
    address: '25 Lenamore Park, Derry, BT48 8GL',
    shortAddress: '25 Lenamore Park',
    location: 'Cityside, BT48',
    sourceUrl: 'https://www.propertypal.com/25-lenamore-park-derry/1071040',
    currentAgent: 'Daniel Henry',
    priceText: 'Offers Around £242,500',
    originalPriceText: '£250,000',
    priceSignal: 'Reduced from £250,000 and now live for 67 days',
    daysLive: 67,
    listedDate: '23 April 2026',
    updatedDate: '18 June 2026',
    beds: 3,
    baths: 2,
    receptions: 1,
    style: 'Detached family home',
    brief: '3 Bed Detached House',
    hero: 'https://media.propertypal.com/large/p/1069840/42521842.jpg',
    images: [
      'https://media.propertypal.com/large/p/1069840/42521842.jpg',
      'https://media.propertypal.com/large/p/1069840/42521596.jpg',
      'https://media.propertypal.com/large/p/1069840/42521595.jpg',
      'https://media.propertypal.com/large/p/1069840/42521597.jpg',
      'https://media.propertypal.com/large/p/1069840/42521600.jpg',
      'https://media.propertypal.com/large/p/1069840/42521599.jpg',
      'https://media.propertypal.com/large/p/1069840/42521598.jpg',
      'https://media.propertypal.com/large/p/1069840/42521602.jpg',
    ],
    viewsAllTime: '9,101',
    views30: '2,012',
    story: 'A well-presented three-bedroom detached Lenamore Park home with oil heating, uPVC glazing, side driveway, rear lawn and patio, blinds included and chain-free availability.',
    opportunity: 'Lenamore Park is fresh enough to still have momentum but old enough to need a sharper push. The campaign should lean into chain-free family living and the recent price adjustment.',
    buyerAngles: ['Detached three-bedroom home', 'Chain-free sale', 'Driveway plus rear lawn and patio', 'Reduced from £250,000'],
    relaunchPlan: ['Lead with chain-free detached living near the £240k mark.', 'Create family-focused content around the lounge, kitchen, garden and parking.', 'Target Cityside movers and buyers comparing detached homes under £250k.', 'Use the price reduction as a reason to re-open conversations with warm buyers.'],
    socialHooks: ['A chain-free detached home with a fresh price angle', 'Lenamore Park buyers should see this differently', 'Detached, practical and now under the original £250k guide'],
    accessPostcodes: ['BT488GL', 'BT48 8GL'],
  },
  {
    slug: '98-duncastle-park',
    address: "98 Duncastle Park, Newbuildings, L'Derry, BT47 2QL",
    shortAddress: '98 Duncastle Park',
    location: 'Newbuildings, BT47',
    sourceUrl: 'https://www.propertypal.com/98-duncastle-park-newbuildings-lderry/1072692',
    currentAgent: 'Daniel Henry',
    priceText: 'Offers Over £255,000',
    priceSignal: 'Live for 61 days at £255,000, with 5,856 all-time views and 2,197 views in the last 30 days',
    daysLive: 61,
    listedDate: '29 April 2026',
    updatedDate: '12 May 2026',
    beds: 4,
    baths: 2,
    receptions: 1,
    style: 'Detached bungalow with garage',
    brief: '4 Bed Detached Bungalow',
    hero: 'https://media.propertypal.com/large/p/1071492/41556422.jpg',
    images: [
      'https://media.propertypal.com/large/p/1071492/41556422.jpg',
      'https://media.propertypal.com/large/p/1071492/41556432.jpg',
      'https://media.propertypal.com/large/p/1071492/41556434.jpg',
      'https://media.propertypal.com/large/p/1071492/41556436.jpg',
      'https://media.propertypal.com/large/p/1071492/41556433.jpg',
      'https://media.propertypal.com/large/p/1071492/41556421.jpg',
      'https://media.propertypal.com/large/p/1071492/41556435.jpg',
      'https://media.propertypal.com/large/p/1071492/41556437.jpg',
    ],
    viewsAllTime: '5,856',
    views30: '2,197',
    story: 'A four-bedroom detached Newbuildings bungalow in a cul-de-sac, with oil heating, PVC double glazing, driveway, garage, front lawn and paved patio to the rear.',
    opportunity: 'Duncastle Park has the right ingredients for a sharper relaunch: detached bungalow demand, four bedrooms, garage, a family cul-de-sac setting and enough recent views to prove buyers are still engaging.',
    buyerAngles: ['Four-bedroom detached bungalow', 'Garage plus driveway parking', 'Cul-de-sac Newbuildings setting', 'Over 2,000 views in the last 30 days'],
    relaunchPlan: ['Lead with the scarce four-bedroom bungalow angle rather than a generic Newbuildings listing.', 'Create a practical family-living reel around the frontage, lounge, bedrooms, garage and rear patio.', 'Target Waterside and Newbuildings families comparing homes around £250k.', 'Use the 60+ day mark as a clean reason to relaunch the campaign before attention cools further.'],
    socialHooks: ['A Newbuildings bungalow with four-bedroom family appeal', '61 days live and still pulling fresh buyer attention', 'Detached, garage, cul-de-sac — the story needs shown clearly'],
    accessPostcodes: ['BT472QL', 'BT47 2QL'],
  },
  {
    slug: '3-sycamore-gardens',
    address: '3 Sycamore Gardens, Drumahoe, Londonderry, BT47 3BZ',
    shortAddress: '3 Sycamore Gardens',
    location: 'Drumahoe, BT47',
    sourceUrl: 'https://www.propertypal.com/3-sycamore-gardens-drumahoe-londonderry/1077836',
    currentAgent: 'Pauline Elliott Estate Agents',
    priceText: 'Asking Price £269,950',
    priceSignal: 'Live for 40 days at £269,950, with 5,127 all-time views and 2,755 views in the last 30 days',
    daysLive: 40,
    listedDate: '20 May 2026',
    updatedDate: '20 May 2026',
    beds: 3,
    baths: 1,
    receptions: 2,
    style: 'Detached bungalow in Drumahoe',
    brief: '3 Bed Detached Bungalow',
    hero: 'https://media.propertypal.com/large/p/1076636/41907207.jpg',
    images: [
      'https://media.propertypal.com/large/p/1076636/41907207.jpg',
      'https://media.propertypal.com/large/p/1076636/41907200.jpg',
      'https://media.propertypal.com/large/p/1076636/41907208.jpg',
      'https://media.propertypal.com/large/p/1076636/41907233.jpg',
      'https://media.propertypal.com/large/p/1076636/41907235.jpg',
      'https://media.propertypal.com/large/p/1076636/41907237.jpg',
      'https://media.propertypal.com/large/p/1076636/41907239.jpg',
      'https://media.propertypal.com/large/p/1076636/41907240.jpg',
    ],
    viewsAllTime: '5,127',
    views30: '2,755',
    story: 'A detached Drumahoe bungalow with three bedrooms, two reception zones, an open-plan kitchen/dining/family room, oil and solid-fuel heating, and a practical BT47 village position.',
    opportunity: 'Sycamore Gardens sits right in the widened target band and has enough recent attention to prove demand, but it needs a clearer bungalow story around Drumahoe convenience, flexible living and easy single-level appeal.',
    buyerAngles: ['Detached Drumahoe bungalow', 'Open-plan kitchen / dining / family room', 'Two reception zones', 'Over 2,700 views in the last 30 days'],
    relaunchPlan: ['Lead with detached bungalow demand in Drumahoe rather than room-by-room detail.', 'Create a compact lifestyle reel around the family room, lounge, frontage and garden access.', 'Target Waterside and Drumahoe buyers comparing bungalows below £300k.', 'Use the 40-day mark as an early relaunch trigger before the listing becomes stale.'],
    socialHooks: ['A Drumahoe bungalow that needs a sharper second push', 'Detached, practical and already getting buyer attention', '40 days live is the moment to refresh the story'],
    accessPostcodes: ['BT473BZ', 'BT47 3BZ'],
  },
  {
    slug: '14-carmoney-court',
    address: "14 Carmoney Court, Eglinton, L'Derry, BT47 3FX",
    shortAddress: '14 Carmoney Court',
    location: 'Eglinton, BT47',
    sourceUrl: 'https://www.propertypal.com/14-carmoney-court-eglinton-lderry/1077130',
    currentAgent: 'Pauline Elliott Estate Agents',
    priceText: 'Asking Price £225,000',
    priceSignal: 'Live for 45 days at £225,000, with 5,120 all-time views and 2,716 views in the last 30 days',
    daysLive: 45,
    listedDate: '15 May 2026',
    updatedDate: '22 June 2026',
    beds: 3,
    baths: 3,
    receptions: 1,
    style: 'Freshly prepared semi-detached home',
    brief: '3 Bed Semi-detached House',
    hero: 'https://media.propertypal.com/large/p/1075930/41838527.jpg',
    images: [
      'https://media.propertypal.com/large/p/1075930/41838527.jpg',
      'https://media.propertypal.com/large/p/1075930/41838518.jpg',
      'https://media.propertypal.com/large/p/1075930/41838517.jpg',
      'https://media.propertypal.com/large/p/1075930/41838412.jpg',
      'https://media.propertypal.com/large/p/1075930/41838430.jpg',
      'https://media.propertypal.com/large/p/1075930/41838431.jpg',
      'https://media.propertypal.com/large/p/1075930/41838441.jpg',
      'https://media.propertypal.com/large/p/1075930/41838442.jpg',
    ],
    viewsAllTime: '5,120',
    views30: '2,716',
    story: 'A three-bedroom Carmoney Court semi in Eglinton, freshly painted with new carpets, new kitchen appliances, three bathrooms, utility room, cul-de-sac position and early occupation available.',
    opportunity: 'Carmoney Court has a strong ready-to-move story at the lower end of the widened band. The campaign should make the Eglinton location, fresh finish and early occupation feel obvious in the first few seconds.',
    buyerAngles: ['Eglinton cul-de-sac location', 'Fresh paint, new carpets and new appliances', 'Three bedrooms and three bathrooms', 'Early occupation available'],
    relaunchPlan: ['Position it as a clean, ready-to-move Eglinton home at £225k.', 'Build short-form content around the fresh finish, open-plan living, utility and cul-de-sac setting.', 'Target Eglinton first-time movers, young families and buyers comparing newer-feel homes under £250k.', 'Use the recent 2,700-view signal to drive a private viewing push.'],
    socialHooks: ['An Eglinton home that is ready now, not after a project', 'Fresh carpets, new appliances and early occupation', '45 days live means it needs a sharper conversion push'],
    accessPostcodes: ['BT473FX', 'BT47 3FX'],
  },
  {
    slug: '4-daisyhill-park',
    address: '4 Daisyhill Park, Derry, BT48 8EZ',
    shortAddress: '4 Daisyhill Park',
    location: 'Cityside, BT48',
    sourceUrl: 'https://www.propertypal.com/4-daisyhill-park-derry/1075025',
    currentAgent: 'Pauline Elliott Estate Agents',
    priceText: 'Asking Price £279,950',
    priceSignal: 'Live for 54 days at £279,950, with 7,869 all-time views and 3,030 views in the last 30 days',
    daysLive: 54,
    listedDate: '6 May 2026',
    updatedDate: '20 May 2026',
    beds: 3,
    baths: 1,
    receptions: 1,
    style: 'Semi-detached bungalow with early occupation',
    brief: '3 Bed Semi-detached Bungalow',
    hero: 'https://media.propertypal.com/large/p/1073825/41672227.jpg',
    images: [
      'https://media.propertypal.com/large/p/1073825/41672227.jpg',
      'https://media.propertypal.com/large/p/1073825/41672155.jpg',
      'https://media.propertypal.com/large/p/1073825/41672225.jpg',
      'https://media.propertypal.com/large/p/1073825/41672178.jpg',
      'https://media.propertypal.com/large/p/1073825/41672191.jpg',
      'https://media.propertypal.com/large/p/1073825/41672200.jpg',
      'https://media.propertypal.com/large/p/1073825/41672233.jpg',
      'https://media.propertypal.com/large/p/1073825/41672300.jpg',
    ],
    viewsAllTime: '7,869',
    views30: '3,030',
    story: 'A three-bedroom Daisyhill Park semi-detached bungalow with open-plan lounge/dining/kitchen space, utility room, gas heating, early occupation and a practical Cityside BT48 position.',
    opportunity: 'Daisyhill Park has high recent attention and bungalow scarcity on its side. The relaunch needs to make the single-level convenience, Cityside setting and early-occupation route more immediate.',
    buyerAngles: ['Cityside bungalow-style living', 'Open-plan lounge / dining / kitchen', 'Utility room and gas heating', 'Over 3,000 views in the last 30 days'],
    relaunchPlan: ['Lead with Cityside bungalow demand and early occupation.', 'Create a buyer-friendly reel around open-plan living, bedrooms, shower room and low-maintenance convenience.', 'Target downsizers, local BT48 movers and families looking just above £250k.', 'Use the strong monthly views as a reason to refresh the campaign before it drifts.'],
    socialHooks: ['A Cityside bungalow-style home with real buyer demand', 'Nearly 8,000 views needs better follow-up', 'Daisyhill Park deserves a clearer relaunch angle'],
    accessPostcodes: ['BT488EZ', 'BT48 8EZ'],
  },
  {
    slug: '14-oakfield-road',
    address: '14 Oakfield Road, Derry, BT48 9BB',
    shortAddress: '14 Oakfield Road',
    location: 'Cityside, BT48',
    sourceUrl: 'https://www.propertypal.com/14-oakfield-road-derry/1017897',
    currentAgent: 'Oakland Estate Agents',
    priceText: 'Guide Price £299,950',
    priceSignal: 'Live for 152 days at £299,950, with 24,368 all-time views and 2,498 views in the last 30 days',
    daysLive: 152,
    listedDate: '29 January 2026',
    updatedDate: '23 April 2026',
    beds: 3,
    baths: 2,
    receptions: 2,
    style: 'Detached cityside family home',
    brief: '3 Bed Detached House',
    hero: 'https://media.propertypal.com/large/p/1016697/41302796.jpg',
    images: [
      'https://media.propertypal.com/large/p/1016697/41302796.jpg',
      'https://media.propertypal.com/large/p/1016697/41307751.jpg',
      'https://media.propertypal.com/large/p/1016697/41311148.jpg',
      'https://media.propertypal.com/large/p/1016697/41314618.jpg',
      'https://media.propertypal.com/large/p/1016697/41317492.jpg',
      'https://media.propertypal.com/large/p/1016697/41320304.jpg',
      'https://media.propertypal.com/large/p/1016697/41328325.jpg',
      'https://media.propertypal.com/large/p/1016697/41352874.jpg',
    ],
    viewsAllTime: '24,368',
    views30: '2,498',
    story: 'A detached Oakfield Road home with three bedrooms, two reception rooms, two bathrooms, private side and rear gardens, concrete parking, CCTV and a walkable position close to the city centre, Brooke Park, schools and the university.',
    opportunity: 'Oakfield Road has had a long run and huge attention, but the story needs to move beyond “detached house”. The campaign should sell the rare cityside mix: quiet residential street, garden privacy, walkability and detached family space.',
    buyerAngles: ['Detached home within walking distance of the city centre', 'Two receptions and two bathrooms', 'Private side and rear gardens', 'Over 24,000 all-time views'],
    relaunchPlan: ['Reframe the home around city walkability plus private detached living.', 'Create a location-led reel connecting Oakfield Road to Brooke Park, schools, university and the city centre.', 'Target cityside families, university-linked buyers and movers wanting convenience without losing garden space.', 'Use the 152-day run and 24,000 views as the reason for a proper presentation reset.'],
    socialHooks: ['A detached Cityside home with the views but not the conversion', 'Oakfield Road has the location story buyers remember', '152 days live means it needs more than another portal refresh'],
    accessPostcodes: ['BT489BB', 'BT48 9BB'],
  },
  {
    slug: '62-cranlee-park',
    address: '62 Cranlee Park, Culmore, Derry, BT48 8AJ',
    shortAddress: '62 Cranlee Park',
    location: 'Culmore, BT48',
    sourceUrl: 'https://www.propertypal.com/62-cranlee-park-culmore-derry/1058031',
    currentAgent: 'Midas Estate Agents',
    priceText: 'Price £234,950',
    priceSignal: 'Repriced during a 120-day campaign and still generating strong monthly views',
    daysLive: 120,
    listedDate: '9 February 2026',
    updatedDate: '17 April 2026',
    beds: 3,
    baths: 1,
    receptions: 1,
    style: 'Detached bungalow in Culmore',
    brief: '3 Bed Detached Bungalow',
    hero: 'https://media.propertypal.com/large/p/1056831/41275505.jpg',
    images: [
      'https://media.propertypal.com/large/p/1056831/41275505.jpg',
      'https://media.propertypal.com/large/p/1056831/40273466.jpg',
      'https://media.propertypal.com/large/p/1056831/40273467.jpg',
      'https://media.propertypal.com/large/p/1056831/40273468.jpg',
      'https://media.propertypal.com/large/p/1056831/40273469.jpg',
      'https://media.propertypal.com/large/p/1056831/40273470.jpg',
      'https://media.propertypal.com/large/p/1056831/40273471.jpg',
      'https://media.propertypal.com/large/p/1056831/40273472.jpg',
    ],
    viewsAllTime: '11,699',
    views30: '4,185',
    story: 'A detached three-bedroom Culmore bungalow in Cranlee Park with ample parking, oil heating, uPVC glazing, open fire option and an enclosed rear yard.',
    opportunity: 'Cranlee Park has a strong location and high recent views, but needs a cleaner campaign around Culmore bungalow demand, parking and manageable living.',
    buyerAngles: ['Popular Culmore setting', 'Detached bungalow below £235k', 'Ample parking', 'Over 4,000 views in the last 30 days'],
    relaunchPlan: ['Position as a practical Culmore bungalow with strong buyer demand already visible.', 'Build a short social campaign around parking, bungalow ease and location.', 'Target Culmore downsizers and local buyers searching for detached stock below £250k.', 'Turn recent portal views into direct private viewing follow-up.'],
    socialHooks: ['A Culmore bungalow with buyer attention already there', '4,000 recent views needs better follow-up', 'Detached, practical and priced below £235k'],
    accessPostcodes: ['BT488AJ', 'BT48 8AJ'],
  },
  {
    slug: '6-baronet-street',
    address: '6 Baronet Street, Cityside, Derry/Londonderry, BT48 7NT',
    shortAddress: '6 Baronet Street',
    location: 'Cityside, BT48',
    sourceUrl: 'https://www.propertypal.com/6-baronet-street-cityside-derrylondonderry/1066833',
    currentAgent: 'Montgomery & McCleery',
    priceText: 'Price £239,950',
    priceSignal: 'Live for 68 days with more than 14,600 all-time views',
    daysLive: 68,
    listedDate: '1 April 2026',
    updatedDate: '22 May 2026',
    beds: 5,
    baths: 1,
    receptions: 2,
    style: 'Mid-terrace near the waterfront',
    brief: 'A rare mid terrace property near the waterfront',
    hero: 'https://media.propertypal.com/large/p/1065633/41048204.jpg',
    images: [
      'https://media.propertypal.com/large/p/1065633/41048204.jpg',
      'https://media.propertypal.com/large/p/1065633/41048219.jpg',
      'https://media.propertypal.com/large/p/1065633/41048218.jpg',
      'https://media.propertypal.com/large/p/1065633/41048209.jpg',
      'https://media.propertypal.com/large/p/1065633/41048208.jpg',
      'https://media.propertypal.com/large/p/1065633/41048205.jpg',
      'https://media.propertypal.com/large/p/1065633/41048206.jpg',
      'https://media.propertypal.com/large/p/1065633/41048210.jpg',
    ],
    viewsAllTime: '14,665',
    views30: '4,683',
    story: 'A rare Baronet Street property close to the city centre, Magee University and the waterfront, offering five bedrooms, two receptions and investment-style appeal.',
    opportunity: 'Baronet Street should be sold on location, university demand and city-centre flexibility, not just room counts. The recent view count suggests interest that needs better conversion.',
    buyerAngles: ['Near Magee University and the waterfront', 'Five bedrooms and two receptions', 'Cityside investment appeal', '4,683 views in the last 30 days'],
    relaunchPlan: ['Reframe around city living, student/professional demand and waterfront proximity.', 'Create a location-first reel tying the house to Magee, the quay and city centre.', 'Target investors, parents of students and cityside movers.', 'Use high recent views as the hook for a direct follow-up push.'],
    socialHooks: ['A Cityside property buyers should see as an opportunity', 'Magee, the quay and five-bedroom flexibility', 'High views, strong location — now it needs a sharper pitch'],
    accessPostcodes: ['BT487NT', 'BT48 7NT'],
  },
  {
    slug: '21-strangford-park',
    address: '21 Strangford Park, Foyle Springs, Derry, BT48 0JW',
    shortAddress: '21 Strangford Park',
    location: 'Foyle Springs, BT48',
    sourceUrl: 'https://www.propertypal.com/21-strangford-park-foyle-springs-derry/1067405',
    currentAgent: 'Oakland Estate Agents',
    priceText: 'Guide Price £255,000',
    originalPriceText: '£265,000',
    priceSignal: 'Reduced from £265,000 and still live after 66 days',
    daysLive: 66,
    listedDate: '3 April 2026',
    updatedDate: '5 June 2026',
    beds: 4,
    baths: 1,
    receptions: 1,
    style: 'Detached chalet bungalow',
    brief: '4 Bed Detached House',
    hero: 'https://media.propertypal.com/large/p/1066205/41080241.jpg',
    images: [
      'https://media.propertypal.com/large/p/1066205/41080241.jpg',
      'https://media.propertypal.com/large/p/1066205/41080242.jpg',
      'https://media.propertypal.com/large/p/1066205/41080244.jpg',
      'https://media.propertypal.com/large/p/1066205/41080237.jpg',
      'https://media.propertypal.com/large/p/1066205/41080238.jpg',
      'https://media.propertypal.com/large/p/1066205/41080240.jpg',
      'https://media.propertypal.com/large/p/1066205/41080239.jpg',
      'https://media.propertypal.com/large/p/1066205/41080243.jpg',
    ],
    viewsAllTime: '12,868',
    views30: '4,676',
    story: 'A four-bedroom detached chalet bungalow in a private Foyle Springs park, close to the city centre and local amenities, with driveway parking and a private rear garden.',
    opportunity: 'At £255k this sits just above the target band but has the right stale-market profile. A relaunch should push Foyle Springs, detached space and the fresh reduction.',
    buyerAngles: ['Private Foyle Springs park', 'Four-bedroom detached layout', 'Reduced from £265,000', 'High recent portal activity'],
    relaunchPlan: ['Lead with detached family space in Foyle Springs, not just the bungalow label.', 'Create a “private park near the city” social angle using the frontage and garden.', 'Target families comparing £250k-£260k detached homes.', 'Use the £10k reduction as a reason to restart buyer conversations.'],
    socialHooks: ['A Foyle Springs detached home that needs a reset', 'Reduced, private and close to the city', 'Four-bedroom space just above the £250k mark'],
    accessPostcodes: ['BT480JW', 'BT48 0JW'],
  },
  {
    slug: '71a-ivy-mead',
    address: '71a Ivy Mead, Waterside, Derry / Londonderry, BT47 3WW',
    shortAddress: '71a Ivy Mead',
    location: 'Waterside, BT47',
    sourceUrl: 'https://www.propertypal.com/71a-ivy-mead-waterside-derry-londonderry/1067386',
    currentAgent: 'Robert Quigley Estate Agents',
    priceText: 'Price £230,000',
    priceSignal: 'Live for 67 days with more than 10,000 all-time views',
    daysLive: 67,
    listedDate: '3 April 2026',
    updatedDate: '27 April 2026',
    beds: 4,
    baths: 3,
    receptions: 3,
    style: 'Large semi-detached family home',
    brief: '4 Bed Semi-detached House',
    hero: 'https://media.propertypal.com/large/p/1066186/41489343.jpg',
    images: [
      'https://media.propertypal.com/large/p/1066186/41489343.jpg',
      'https://media.propertypal.com/large/p/1066186/41489342.jpg',
      'https://media.propertypal.com/large/p/1066186/41489344.jpg',
      'https://media.propertypal.com/large/p/1066186/41489347.jpg',
      'https://media.propertypal.com/large/p/1066186/41489346.jpg',
      'https://media.propertypal.com/large/p/1066186/41489351.jpg',
      'https://media.propertypal.com/large/p/1066186/41489352.jpg',
      'https://media.propertypal.com/large/p/1066186/41489354.jpg',
    ],
    viewsAllTime: '10,487',
    views30: '3,168',
    story: 'A beautifully presented four-bedroom Ivy Mead semi-detached home with three receptions, three bathrooms, oil heating, uPVC glazing and a popular Waterside setting.',
    opportunity: 'Ivy Mead has more space than many buyers expect at £230k. A relaunch should make the family-scale layout obvious immediately and stop it being treated like a standard semi.',
    buyerAngles: ['Four bedrooms, three bathrooms and three receptions', 'Popular Waterside residential area', 'Strong space-for-money story', 'More than 10,000 all-time views'],
    relaunchPlan: ['Position around “family-scale space under £235k” rather than a standard semi-detached listing.', 'Create a room-count and lifestyle walkthrough that shows the extra receptions clearly.', 'Target growing families and Waterside movers priced out of detached options.', 'Follow up recent viewers with a space/value message and private viewing prompt.'],
    socialHooks: ['A Waterside semi with serious family space', 'Four beds, three receptions and three bathrooms under £235k', 'The layout needs shown, not buried in listing text'],
    accessPostcodes: ['BT473WW', 'BT47 3WW'],
  },
  {
    slug: '18-ashthorpe',
    address: '18 Ashthorpe, Waterside, Derry, BT47 2DH',
    shortAddress: '18 Ashthorpe',
    location: 'Waterside, BT47',
    sourceUrl: 'https://www.propertypal.com/18-ashthorpe-waterside-derry/1081632',
    currentAgent: 'Locate Estate Agents',
    priceText: 'Asking Price £245,000',
    priceSignal: 'Added on 7 June 2026 and already ranked 1st for Waterside homes between £200k and £250k',
    daysLive: 8,
    listedDate: '7 June 2026',
    updatedDate: '7 June 2026',
    beds: 3,
    baths: 3,
    receptions: 1,
    style: 'Semi-detached corner-plot home',
    brief: '3 Bed Semi-detached House',
    hero: 'https://media.propertypal.com/large/p/1080432/42296470.jpg',
    images: [
      'https://media.propertypal.com/large/p/1080432/42296470.jpg',
      'https://media.propertypal.com/large/p/1080432/42296471.jpg',
      'https://media.propertypal.com/large/p/1080432/42296472.jpg',
      'https://media.propertypal.com/large/p/1080432/42296473.jpg',
      'https://media.propertypal.com/large/p/1080432/42296474.jpg',
      'https://media.propertypal.com/large/p/1080432/42296475.jpg',
      'https://media.propertypal.com/large/p/1080432/42296476.jpg',
      'https://media.propertypal.com/large/p/1080432/42296477.jpg',
    ],
    viewsAllTime: '3,498',
    views30: '3,498',
    views7: '2,985',
    story: 'A three-bedroom Ashthorpe semi on a corner plot with three bathrooms, driveway parking, front and rear gardens, a decked area and early occupation available.',
    opportunity: 'Ashthorpe is already getting strong fresh attention, but the campaign should make the practical buyer story clearer: corner plot, parking, three bathrooms, early occupation and a ready-to-move Waterside position.',
    buyerAngles: ['Corner plot in Waterside', 'Three bedrooms and three bathrooms', 'Driveway parking plus front and rear gardens', 'Early occupation available'],
    relaunchPlan: ['Lead with the corner-plot and early-occupation story, not just the room list.', 'Create a quick family-move reel using the frontage, kitchen, lounge and garden deck.', 'Target Waterside buyers comparing homes under £250k and families who need practical space now.', 'Use the early view spike to push private viewing follow-up before the listing cools.'],
    socialHooks: ['A Waterside corner-plot home with momentum already there', 'Three bathrooms, driveway parking and early occupation', 'Fresh attention needs fast follow-up before buyers drift'],
    accessPostcodes: ['BT472DH', 'BT47 2DH'],
  },
  {
    slug: '101-templegrove',
    address: '101 Templegrove, Derry, BT48 0RF',
    shortAddress: '101 Templegrove',
    location: 'Cityside, BT48',
    sourceUrl: 'https://www.propertypal.com/101-templegrove-derry/1079899',
    currentAgent: 'Pauline Elliott Estate Agents',
    priceText: 'Asking Price £285,000',
    priceSignal: 'Added on 9 June 2026 and already ranked 1st for Cityside homes between £200k and £300k',
    daysLive: 6,
    listedDate: '9 June 2026',
    updatedDate: '9 June 2026',
    beds: 4,
    baths: 3,
    receptions: 3,
    style: 'Chalet bungalow in a cul-de-sac',
    brief: '4 Bed Chalet Bungalow',
    hero: 'https://media.propertypal.com/large/p/1078699/42337458.jpg',
    images: [
      'https://media.propertypal.com/large/p/1078699/42337458.jpg',
      'https://media.propertypal.com/large/p/1078699/42337443.jpg',
      'https://media.propertypal.com/large/p/1078699/42337468.jpg',
      'https://media.propertypal.com/large/p/1078699/42337478.jpg',
      'https://media.propertypal.com/large/p/1078699/42337477.jpg',
      'https://media.propertypal.com/large/p/1078699/42337487.jpg',
      'https://media.propertypal.com/large/p/1078699/42337498.jpg',
      'https://media.propertypal.com/large/p/1078699/42337499.jpg',
    ],
    viewsAllTime: '3,015',
    views30: '3,015',
    views7: '2,831',
    story: 'A four-bedroom Templegrove chalet bungalow in a cul-de-sac, with three receptions, three bathrooms, a sunroom, driveway, enclosed rear garden and early occupation available.',
    opportunity: 'Templegrove has family-scale space but could easily be skimmed as another chalet bungalow. The campaign should make the three-reception layout, cul-de-sac setting and move-ready Cityside convenience obvious in the first few seconds.',
    buyerAngles: ['Four bedrooms, three bathrooms and three receptions', 'Cul-de-sac Cityside setting', 'Sunroom plus kitchen-dining space', 'Early occupation available'],
    relaunchPlan: ['Position it as flexible family-scale living in a quiet Cityside cul-de-sac.', 'Build a walkthrough around “three living zones” using the lounge, dining room and sunroom.', 'Target Cityside upsizers, downsizers who still need space and families comparing under £300k.', 'Follow up early portal viewers with a layout-led private viewing message.'],
    socialHooks: ['A Cityside chalet bungalow with more space than buyers expect', 'Four beds, three receptions and a cul-de-sac setting', '3,000 fresh views means the audience is already there'],
    accessPostcodes: ['BT480RF', 'BT48 0RF'],
  },
  {
    slug: '13-florence-street',
    address: '13 Florence Street, Derry, BT48 0HA',
    shortAddress: '13 Florence Street',
    location: 'Rosemount, BT48',
    sourceUrl: 'https://www.propertypal.com/13-florence-street-derry/1082093',
    currentAgent: 'Oakland Estate Agents',
    priceText: 'Guide Price £130,000',
    priceSignal: 'Added on 9 June 2026 and already ranked 2nd for Cityside homes between £125k and £150k',
    daysLive: 6,
    listedDate: '9 June 2026',
    updatedDate: '10 June 2026',
    beds: 2,
    baths: 1,
    receptions: 2,
    style: 'Cityside terrace with starter-home appeal',
    brief: '2 Bed Terrace House',
    hero: 'https://media.propertypal.com/large/p/1080893/42341093.jpg',
    images: [
      'https://media.propertypal.com/large/p/1080893/42341093.jpg',
      'https://media.propertypal.com/large/p/1080893/42341089.jpg',
      'https://media.propertypal.com/large/p/1080893/42341090.jpg',
      'https://media.propertypal.com/large/p/1080893/42341091.jpg',
      'https://media.propertypal.com/large/p/1080893/42341087.jpg',
      'https://media.propertypal.com/large/p/1080893/42341088.jpg',
      'https://media.propertypal.com/large/p/1080893/42341094.jpg',
      'https://media.propertypal.com/large/p/1080893/42341092.jpg',
    ],
    viewsAllTime: '3,228',
    views30: '3,228',
    views7: '3,043',
    story: 'A two-bedroom Florence Street terrace within walking distance of Magee University and the city centre, with two receptions, possible ground-floor third bedroom and immediate occupation available.',
    opportunity: 'Florence Street needs a sharper split between first-time buyer and investor messaging. The value is not only the price; it is the University, city-centre access, flexible third-room option and ready-now condition.',
    buyerAngles: ['Walking distance to Magee and the city centre', 'Two receptions with possible third-bedroom use', 'Affordable guide price at £130,000', 'Ready for immediate occupation'],
    relaunchPlan: ['Lead with affordability, location and immediate occupation rather than generic terrace wording.', 'Create two campaign angles: first home near the city and investor-ready Rosemount terrace.', 'Target first-time buyers, Co-Ownership prospects, parents of students and cityside investors.', 'Use the fresh view surge to separate serious buyers from passive browsers quickly.'],
    socialHooks: ['A Rosemount starter home with investor logic too', 'Magee, city centre and immediate occupation at £130k', 'High fresh views need a buyer-specific follow-up plan'],
    accessPostcodes: ['BT480HA', 'BT48 0HA'],
  },

];

export function getShowcase(slug: string) {
  return showcases.find((showcase) => showcase.slug === slug);
}
