export const programmes = [
  {
    id: 'primary-ni',
    region: 'NI',
    schoolType: 'Primary',
    title: 'NI Primary Support Programme',
    description: 'P1-P7 wellbeing, resilience, anxiety, friendships, transitions and cultural diversity support.',
    workshops: [
      { id: 'tricky-times', title: "HIP 'N' HAPPY — Tricky Times", stage: 'P1-P3', delivery: 'Face-to-face', term: 'Flexible', price: null },
      { id: 'feelings', title: "HIP 'N' HAPPY — My Feelings and I", stage: 'P1-P3', delivery: 'Face-to-face', term: 'Flexible', price: null },
      { id: 'friendships', title: "HIP 'N' HAPPY — Building Friendships", stage: 'P1-P3', delivery: 'Face-to-face', term: 'Flexible', price: null },
      { id: 'p7-worries', title: 'Conquering P7 Worries', stage: 'P7', delivery: 'Online', term: 'October', price: null },
      { id: 'anti-bullying', title: 'Anti-Bullying Megathon', stage: 'P4-P7', delivery: 'Online', term: 'November', price: null },
      { id: 'mental-health-week', title: "Children's Mental Health Week", stage: 'P4-P7', delivery: 'Online', term: 'February', price: null },
      { id: 'tackling-anxiety-primary', title: 'Tackling Anxiety', stage: 'P4-P7', delivery: 'Online', term: 'March', price: null },
      { id: 'resilience-primary', title: 'Enhancing Resilience', stage: 'P4-P7', delivery: 'Online', term: 'April', price: null },
      { id: 'next-step-primary', title: 'Taking The Next Step', stage: 'P7', delivery: 'Online / F2F on request', term: 'May-June', price: null },
      { id: 'cultural-diversity', title: 'Cultural Diversity', stage: 'P4-P7', delivery: 'Online', term: 'May', price: 120 },
    ],
  },
  {
    id: 'post-primary-ni',
    region: 'NI',
    schoolType: 'Post-primary',
    title: 'NI Post-primary Support Programme',
    description: 'Face-to-face programme across KS3, KS4 and KS5 with recommended timing by school term.',
    workshops: [
      { id: 'ready-for-action', title: 'Year 8: Ready For Action', stage: 'Year 8', delivery: 'Face-to-face', term: 'Sept-Oct', price: null },
      { id: 'tackling-anxiety-ks3', title: 'Tackling Anxiety', stage: 'Years 8-9', delivery: 'Face-to-face', term: 'Halloween-Christmas', price: null },
      { id: 'anti-bullying-ks3', title: 'Anti-Bullying', stage: 'Years 8-10', delivery: 'Face-to-face', term: 'Halloween-Christmas', price: null },
      { id: 'taking-next-step-ks3', title: 'Taking The Next Step', stage: 'Year 10', delivery: 'Face-to-face', term: 'Jan-Feb', price: null },
      { id: 'level-up', title: 'Level Up — Transitioning to GCSE', stage: 'Year 11', delivery: 'Face-to-face', term: 'Sept-Oct', price: null },
      { id: 'vaping', title: 'The Truth About Vaping', stage: 'Year 11+', delivery: 'Face-to-face', term: 'Flexible', price: null },
      { id: 'gcse-performance', title: 'Peak GCSE Exam Performance', stage: 'Year 12', delivery: 'Face-to-face', term: 'Feb-Easter', price: null },
      { id: 'taking-control', title: 'Taking Control', stage: 'Year 13', delivery: 'Face-to-face', term: 'Flexible', price: null },
      { id: 'interview-game', title: 'Nailing The Interview Game', stage: 'Year 14', delivery: 'Face-to-face', term: 'Flexible', price: null },
      { id: 'financial-foundations', title: 'Financial Foundations', stage: 'Year 14', delivery: 'Face-to-face', term: 'Flexible', price: null },
      { id: 'leadership', title: 'Leading By Example / Senior Prefect Leadership', stage: 'KS5', delivery: 'Face-to-face', term: 'Flexible', price: null },
    ],
  },
  {
    id: 'roi',
    region: 'ROI',
    schoolType: 'Primary + Post-primary',
    title: 'ROI Programme',
    description: 'Online-first ROI school workshops, with border-area face-to-face options where practical.',
    workshops: [
      { id: 'croke-park', title: 'Croke Park Hours Staff Development', stage: 'Staff', delivery: 'Online', term: 'Aug-Sept / Jan / Apr', price: null },
      { id: 'roi-healthy', title: "HIP 'N' Healthy Programme", stage: '3rd-6th Class', delivery: 'Online', term: 'Across terms', price: null },
      { id: 'roi-ready', title: 'Ready For Action', stage: 'First Year', delivery: 'Face-to-face / Online', term: 'Sept-Halloween', price: null },
      { id: 'roi-anti-bullying', title: 'Anti-Bullying', stage: 'First-Third Year', delivery: 'Face-to-face / Online', term: 'Halloween-Christmas', price: null },
      { id: 'roi-exam', title: 'Peak Exam Performance', stage: 'Third / Sixth Year', delivery: 'Face-to-face / Online', term: 'Feb-Easter', price: null },
      { id: 'roi-teamwork', title: 'Teamwork Skills', stage: 'Transition Year', delivery: 'Face-to-face / Online', term: 'Flexible', price: null },
      { id: 'roi-confidence', title: 'Communication & Confidence', stage: 'Transition Year', delivery: 'Face-to-face / Online', term: 'Flexible', price: null },
    ],
  },
]

export const sessionSlots = [
  {
    id: 'diversity-2',
    workshopId: 'cultural-diversity',
    label: 'Diversity2 — P4/P5',
    date: '2026-05-21',
    time: '09:30–10:30',
    delivery: 'Online',
    region: 'NI',
    facilitator: 'Cormac',
    capacity: 5,
    booked: 5,
    zoomStatus: 'ready',
    calendarStatus: 'synced',
  },
  {
    id: 'diversity-3',
    workshopId: 'cultural-diversity',
    label: 'Diversity3 — P6/P7',
    date: '2026-05-21',
    time: '11:00–12:00',
    delivery: 'Online',
    region: 'NI',
    facilitator: 'Cormac',
    capacity: 5,
    booked: 2,
    zoomStatus: 'ready',
    calendarStatus: 'synced',
  },
  {
    id: 'diversity-4',
    workshopId: 'cultural-diversity',
    label: 'Diversity4 — P4/P5',
    date: '2026-05-21',
    time: '13:15–14:15',
    delivery: 'Online',
    region: 'NI',
    facilitator: 'Sinead',
    capacity: 5,
    booked: 1,
    zoomStatus: 'ready',
    calendarStatus: 'synced',
  },
  {
    id: 'diversity-5',
    workshopId: 'cultural-diversity',
    label: 'Diversity5 — P4/P5',
    date: '2026-05-22',
    time: '09:30–10:30',
    delivery: 'Online',
    region: 'NI',
    facilitator: 'Cormac',
    capacity: 5,
    booked: 1,
    zoomStatus: 'ready',
    calendarStatus: 'synced',
  },
  {
    id: 'diversity-6',
    workshopId: 'cultural-diversity',
    label: 'Diversity6 — P6/P7',
    date: '2026-05-22',
    time: '11:00–12:00',
    delivery: 'Online',
    region: 'NI',
    facilitator: 'Cormac',
    capacity: 5,
    booked: 1,
    zoomStatus: 'ready',
    calendarStatus: 'synced',
  },
  {
    id: 'p7-worries-1',
    workshopId: 'p7-worries',
    label: 'Conquering P7 Worries — Term 1',
    date: '2026-10-08',
    time: '10:00–11:00',
    delivery: 'Online',
    region: 'NI',
    facilitator: 'Karen',
    capacity: 25,
    booked: 8,
    zoomStatus: 'missing',
    calendarStatus: 'draft',
  },
]

export const bookings = [
  {
    id: 'BK-1027',
    school: "St Macartan's PS",
    region: 'NI',
    schoolType: 'Primary',
    funding: 'School funded',
    source: 'Email',
    booker: { name: 'School Admin', email: 'admin.stmacartans@example.school', phone: '02800000000' },
    teacher: { name: 'To confirm', email: '', phone: '' },
    workshop: 'Cultural Diversity',
    slot: 'Diversity2 — P4/P5, Thu 21 May, 09:30',
    classLines: [
      { group: 'Composite P4/P5', classes: 1, pupils: null },
      { group: 'Composite P6/P7', classes: 1, pupils: null },
    ],
    totalClasses: 2,
    totalExVat: 240,
    status: 'needs-teacher',
    owner: 'Karen',
    zoho: 'pending',
    calendar: 'synced',
    email: 'partial',
    createdAt: '2026-04-29T14:30:00Z',
    notes: 'Teacher details still need captured separately before reminders go out.',
  },
  {
    id: 'BK-1026',
    school: 'Ballymena Primary School',
    region: 'NI',
    schoolType: 'Primary',
    funding: 'EA',
    source: 'Website',
    booker: { name: 'School Contact', email: 'teacher.ballymena@example.school', phone: '02800000001' },
    teacher: { name: 'School Contact', email: 'teacher.ballymena@example.school', phone: '02800000001' },
    workshop: 'Cultural Diversity',
    slot: 'Diversity2 — P4/P5, Thu 21 May, 09:30',
    classLines: [
      { group: 'P4', classes: 1, pupils: null },
      { group: 'P5', classes: 1, pupils: null },
    ],
    totalClasses: 2,
    totalExVat: 240,
    status: 'confirmed',
    owner: 'Karen',
    zoho: 'synced',
    calendar: 'synced',
    email: 'sent',
    createdAt: '2026-04-28T11:15:00Z',
    notes: 'Ready for two-week reminder.',
  },
  {
    id: 'BK-1025',
    school: 'Braidside Integrated Primary School',
    region: 'NI',
    schoolType: 'Primary',
    funding: 'School funded',
    source: 'Website',
    booker: { name: 'Teacher Contact', email: 'teacher.braidside@example.school', phone: '02800000002' },
    teacher: { name: 'Teacher Contact', email: 'teacher.braidside@example.school', phone: '02800000002' },
    workshop: 'Cultural Diversity',
    slot: 'Diversity2 — P4/P5, Thu 21 May, 09:30',
    classLines: [
      { group: 'P5', classes: 2, pupils: null },
    ],
    totalClasses: 2,
    totalExVat: 240,
    status: 'confirmed',
    owner: 'Cormac',
    zoho: 'failed',
    calendar: 'synced',
    email: 'sent',
    createdAt: '2026-04-27T09:05:00Z',
    notes: 'Zoho failed due duplicate school/contact match. Needs manual review/retry.',
  },
]

export const automationEvents = [
  { id: 1, type: 'Booking saved', target: 'BK-1027', status: 'ok', time: '2m ago' },
  { id: 2, type: 'Internal alert', target: 'Karen + Cormac', status: 'ok', time: '2m ago' },
  { id: 3, type: 'Zoho deal create', target: 'BK-1027', status: 'pending', time: 'waiting' },
  { id: 4, type: 'Teacher confirmation', target: 'BK-1027', status: 'blocked', time: 'missing teacher email' },
  { id: 5, type: 'Calendar update', target: 'Diversity2', status: 'ok', time: '10m ago' },
  { id: 6, type: 'Zoho retry', target: 'BK-1025', status: 'failed', time: '1h ago' },
]
